### ISSUE TITLE
Viewing the Archived pave tab of a killscreendaily.com URL forces download

### ISSUE THREAD

**Issue by phillipsm** [harvard-lil/perma#1000]
Feels like I want my browser to render the content in the iframe instead of the download button.

http://killscreendaily.com/articles/weird-abandoned-spaces-virtual-worlds/?utm_source=hackernewsletter&utm_medium=email&utm_term=fun

![screen shot 2015-08-21 at 3 15 39 pm](https://cloud.githubusercontent.com/assets/196089/9417078/814f2b18-4817-11e5-9c45-7caf1aab67fa.png)

**Comment by jcushman** [comment]
Fixed (for now) -- let me know if you find any other examples where we don't detect content-type correctly.
