### ISSUE TITLE
Encode spaces in anchor element

### ISSUE THREAD

**Issue by phillipsm** [harvard-lil/perma#1003]
Chrome and Firefox seem to resolve http://www.epa.gov/agriculture/lsca.html#Lead-Based Paint to an anchor in the page. Perma chokes thinking that it's not a valid address.

If we replace the space (between Based and Paint) with %20, things work. Should Perma be encoding the space for us? Probably, right?

**Comment by jcushman** [comment]
I haven't played with this, but really we shouldn't be sending the fragment after the # to the server at all ...
