### ISSUE TITLE
Home page logo carousel - remove outline on chevron:focus

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#1015]
The chevron/button for advancing the logo carousel is showing an outline on focus. Looks a wee bit clunky.
![screen shot 2015-09-02 at 9 47 03 am](https://cloud.githubusercontent.com/assets/2140548/9632775/38243372-5157-11e5-9d56-632d4ae846bd.png)

**Comment by thisisdano** [comment]
Coming in the next blob.
