### ISSUE TITLE
Remove border on .navbar-nav that pops up when you click "add user"

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#1017]
For some reason there's a random black border that shows up on .navbar-nav when you're in "manage users" and you click "add user"
![screen shot 2015-09-02 at 11 23 37 am](https://cloud.githubusercontent.com/assets/2140548/9635501/bd2fb50c-5164-11e5-9998-64ae5fa53bfc.png)

**Comment by thisisdano** [comment]
This has to do with the scope of the `data-toggle: collapse` action
I think this is known and MP is looking at it.

**Comment by thisisdano** [comment]
That is to say, I wrote some bad js, and Matt needs to fix it :(

**Comment by phillipsm** [comment]
Yup. Sorry to be slow with this. I'm on it.
