### ISSUE TITLE
Cyber.law email addresses getting munged?

### ISSUE THREAD

**Issue by jdcc** [harvard-lil/perma#1028]
It's entirely possible I'm imagining things, but I think this sequence of events just took place:
1. I signed up for an account with my `cyber.law.harvard.edu` email address.
2. I received the activation email at my `law.harvard.edu` email address (no `cyber`).
3. I could only log in with my `cyber.law.harvard.edu` email address.

The header below suggests it was trying to get to the right address, but the `To` field is wrong.

Here's a bit of the email header:

```
Received: from hlsperma1.law.harvard.edu (localhost [127.0.0.1])
    by hlsperma1.law.harvard.edu (Postfix) with ESMTP id A5FDC21E6A
    for <***@cyber.law.harvard.edu>; Fri,  4 Sep 2015 18:56:58 -0400 (EDT)
MIME-Version: 1.0
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: 7bit
Subject: A Perma.cc account has been created for you
From: Perma.cc <info@perma.cc>
To: ***@law.harvard.edu
Date: Fri, 04 Sep 2015 22:56:58 -0000
Message-ID: <20150904225658.19501.69964@hlsperma1.law.harvard.edu>
```

**Comment by jcushman** [comment]
Thanks for the detailed report. We're not doing any special munging of `to` addresses, so this is probably something happening within the HLS mail server on the sending side. Should be fixed when we move to SES for transactional mail ...
