### ISSUE TITLE
Partner list rendering single column only

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#1030]
Should be dual column, no?
![screen shot 2015-09-09 at 2 07 41 pm](https://cloud.githubusercontent.com/assets/2140548/9770038/bfd5c3a4-56fb-11e5-982d-a824f05e505a.png)

**Comment by jcushman** [comment]
@thisisdano: looks like we lost the two-column CSS on the .partner-list div when merging in your redesign -- it was a very recent addition. Could you toss that back in with your next commit? I'm sure you'll do it better than I did.

**Comment by jcushman** [comment]
Bouncing this to you, anastasia -- not sure if one column or two columns feels better for the partner list at the bottom of the current about page:

https://perma.cc/about
