### ISSUE TITLE
Hamburger icon in collapsed header nav looks a little unusual

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#1031]
Not sure if this was intended, but on Chrome the middle horizontal line has a different width than the others

![screen shot 2015-09-09 at 2 09 34 pm](https://cloud.githubusercontent.com/assets/2140548/9770113/2bfdda12-56fc-11e5-87c9-f8701df09f2f.png)

**Comment by leppert** [comment]
Ice cream sandwich icon (tm)
