### ISSUE TITLE
Deploy to staging on successful develop branch testing

### ISSUE THREAD

**Issue by leppert** [harvard-lil/perma#1036]
Travis-CI can deploy to Heroku when all tests have passed. I suggest adding this hook for our `develop` branch such that a staging server is always running the most recent build of `develop`. Here's an example setup that could be utilized once [Heroku support has been merged](https://github.com/harvard-lil/perma/pull/1034):

https://github.com/leppert/perma/blob/deploy-develop-to-heroku-on-successful-travis-ci-build/.travis.yml#L37

**Comment by jcushman** [comment]
Pulled #1034 -- go for it! Let me know if you need me to configure anything.

**Comment by leppert** [comment]
@jcushman merged and working!
