### ISSUE TITLE
Warc playback not working in dano record view redesign

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#1046]
@thisisdano hasn't submitted tis PR yet, but I'm putting issue here b/c it'll need attention once he does

@phillipsm @jcushman let me know if there's a better way to do this - i.e. file issues with a future PR :)
![screen shot 2015-09-15 at 9 28 08 am](https://cloud.githubusercontent.com/assets/2140548/9877615/f93ee67c-5b8b-11e5-9a52-4f9ab60cb8cb.png)

**Comment by thisisdano** [comment]
I should say that I don't see this error on my local machines. Not sure why it's cropping up elsewhere.
