### ISSUE TITLE
Add info-bar beneath header after record creation

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#1057]
After record creation and redirect to record page, display info-bar ("you just created this record...") just beneath record page header

**Comment by thisisdano** [comment]
A newly created Record page should include a Success Status banner at the bottom of the fixed header.

This page should not include this Status on subsequent loads. It should only appear to the Record creator on the initial load.

![record-status-success](https://cloud.githubusercontent.com/assets/11464021/9991110/24d567ea-6035-11e5-82dd-dc5c3ad96b3a.png)

This Status includes:
- message
- Perma Link
- deletion option
- Create a new Perma Link button
- close button (remove Status banner)

**Comment by abziegler** [comment]
* Need to consider with POST or refer-detect for this
* Maybe use a short time window instead (like 1 min)

**Comment by phillipsm** [comment]
imp-le-mented
