### ISSUE TITLE
Allow orgs to adopt links

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#1061]
Allow orgs (e.g. journals) to adopt links created by unaffiliated users (e.g. authors). Consider whether author permission is needed for this.

**Comment by jcushman** [comment]
Update: we think the best way to do this is to add a button to the dropdown tray like "clone this Perma", which creates a *new* link with a new GUID. That way everyone keeps their own link with their own permissions.

Not clear whether there's enough demand for this to justify the effort? Could be that adopting links is mostly a holdover from the vesting mindset.

**Comment by abziegler** [comment]
Low demand, either b/c orgs don't care to 'own' their links or orgs are still making most links. We probably should put this on back-burner and revisit if/when needed.
