### ISSUE TITLE
Add remaining Record count to unaffiliated Create page

### ISSUE THREAD

**Issue by thisisdano** [harvard-lil/perma#1068]
Unaffiliated users should see a remaining record count underneath the Create field on the Create page.

![field block-unaffiliated](https://cloud.githubusercontent.com/assets/11464021/9991245/75dd53fe-6036-11e5-9ba7-efbcf5fbfeb4.png)

**Comment by anniejocain** [comment]
this should already be there

**Comment by thisisdano** [comment]
Where would I see this? I thought I was up to date with `dev.post-vesting`, but I don't see this feature on `user_management / create-link.html`.

**Comment by anniejocain** [comment]
Ah, it's because my pull request hasn't been merged in yet. Maybe we can make that happen today.

**Comment by thisisdano** [comment]
Nice!

**Comment by anniejocain** [comment]
closed in #1083
