### ISSUE TITLE
Record page tray actions should pop up a modal for execute/cancel

### ISSUE THREAD

**Issue by thisisdano** [harvard-lil/perma#1069]
Currently they direct to a new window to execute/cancel the action. This should happen in a modal popup window (like "upload" on the Create page)

**Comment by phillipsm** [comment]
I think I usually prefer a redirect to a modal.

You prefer modals, @thisisdano? Easier for the user to understand?

**Comment by thisisdano** [comment]
My gut prefers modals, since it keeps the action completion on the page you started the action — but I don't yet have a strong opinion about it.

**Comment by anniejocain** [comment]
I'm in the redirect camp myself

**Comment by phillipsm** [comment]
Let's stick with the redirect. It's in place and feels good to me.
