### ISSUE TITLE
Your Perma Links: record expand/collapse causes scroll jump

### ISSUE THREAD

**Issue by thisisdano** [harvard-lil/perma#1084]
On the Your Perma Links page:
Any record you expand/collapse that requires scrolling to access (i.e. any record more than a couple down the page) autoscrolls you to the top of the page when the expand/collapse is triggered. 

I couldn't find the error in the js!

**Comment by phillipsm** [comment]
fixed in https://github.com/harvard-lil/perma/pull/1110
