### ISSUE TITLE
Your Perma Links: Record Affiliation can be active 

### ISSUE THREAD

**Issue by thisisdano** [harvard-lil/perma#1085]
There's now a spot in the record data to display the record's affiliation.

This mirrors the same field that is scheduled to go in the Recent Perma Links section. I added it into the YPL records, but it doesn't pull live information. It's needs proper integration and logic.

![screen shot 2015-09-28 at 12 46 02 pm](https://cloud.githubusercontent.com/assets/11464021/10142181/121f093a-65df-11e5-8d6c-a6206258cf1c.png)

**Comment by anniejocain** [comment]
If it's not affiliated with an org, is it just blank?

**Comment by anniejocain** [comment]
closed in #1103
