### ISSUE TITLE
"This Folder is Empty" missing in Your Perma Links?

### ISSUE THREAD

**Issue by thisisdano** [harvard-lil/perma#1086]
I could have sworn empty folders used to show a "This is an empty folder" message. 
But I guess there never was one....

Similar to "No Users Found" message on the manage users pages.

![screen shot 2015-09-28 at 12 54 15 pm](https://cloud.githubusercontent.com/assets/11464021/10142336/243365d4-65e0-11e5-992e-5aeb562ee9a2.png)

**Comment by phillipsm** [comment]
fixed in https://github.com/harvard-lil/perma/pull/1122
