### ISSUE TITLE
History logging does not include a link's folder membership

### ISSUE THREAD

**Issue by phillipsm** [harvard-lil/perma#1096]
If a record is in an org folder and a person is a member of that org, they can move that record into any folder (including their own).

**Comment by jcushman** [comment]
Update: we want to allow anyone to move links to any of their folders, because usually that's a good thing, but we want to make sure moves are logged so we can deal with any customer service questions.

**Comment by rebeccacremona** [comment]
Hmm. It's not.....

**Comment by rebeccacremona** [comment]
When you move links around, django simple history DOES make an entry in the "change history" list, but the change in folder is not actually reflected, and reverting has no effect.

**Comment by rebeccacremona** [comment]
Changing the title works as expected: it adds an entry to "change history", and each entry lists the correct title, and you can revert as expected.

**Comment by rebeccacremona** [comment]
Changing a one-to-many relationship (created_by) also works normally.

**Comment by rebeccacremona** [comment]
see https://github.com/treyhunner/django-simple-history/issues/16

**Comment by rebeccacremona** [comment]
This is more complex than I expected; tabling for now, pending discussion.
