### ISSUE TITLE
Add ability to resend activation email to affiliated users

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#1102]
We see lots of registrar and org users who set up affiliated user accounts, but the users don't immediately activate. Then they lose the activation emails.

Could we allow registrar/org users to resend activation emails to fellow users?

**Comment by jcushman** [comment]
Love this idea. "Resend activation email" seems to be a pretty common pattern on websites that use activation emails. It could also be offered if someone tries to log in/recover password with a non-activated account.

**Comment by rebeccacremona** [comment]
See https://github.com/harvard-lil/perma/pull/1834
