### ISSUE TITLE
My link dragging seems to be broken.

### ISSUE THREAD

**Issue by phillipsm** [harvard-lil/perma#1111]
We used to be able to drag links to folders in the my links list. This seems to no longer work.

**Comment by thisisdano** [comment]
this still works for me

**Comment by phillipsm** [comment]
Oh, works for me too if I grab the Perma link and drag. I was trying the drag the whole row.

There's some funkiness here. It's a little tough to figure out what to drag. Some things are links (which display the cursor as `pointer`) and some things are appear to be draggable objects (which display the cursor as `grab`).

Kicking this down the line for future polishing.

**Comment by jcushman** [comment]
I think this now works for me -- still looking for polishing, Matt?
