### ISSUE TITLE
If we add back in Thumbnails, display on delete confirm screen 

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#1146]
On delete confirm and dark archive confirm screen, thumbnails don't work

**Comment by jcushman** [comment]
We no longer seem to be using thumbnails anywhere. Closing for now.

**Comment by phillipsm** [comment]
I think this is really nice on the delete screen. Let's keep it (?).

**Comment by jcushman** [comment]
Matt's going to try -- see #821
