### ISSUE TITLE
Availability of Perma Link metadata after deletion

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#1147]
If you delete a link, the URL still works and you can still get all the metadata about the deleted link using the "show details" button. The view page says it's been deleted, but do we want data about the link to visible?

**Comment by abziegler** [comment]
Also, you can still navigate to the source URL with the  "View Live Page" button

**Comment by jcushman** [comment]
Matt and I think this is right -- if the link has been published somehow it shouldn't turn into a total dead end, and it won't be discoverable if it isn't published. Do you have a major privacy concern?

**Comment by abziegler** [comment]
Privacy issue arises if we're identifying the user/org/registrar responsible for it, which we're not doing now but have talked about..

**Comment by jcushman** [comment]
Closing this for now. Let's remember if we change what metadata is available for a link to consider whether it should still be displayed for deleted links.
