### ISSUE TITLE
Drag and drop on my links screen is hard to use

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#1149]
A very small portion of the `link-row` is grabbable/droppable. Seems like it's only the `span .z-top` bit that contains the org name. The rest gives me a pointer cursor. Pretty close to not grabbable at all - which may be ok. If we're going to do drag and drop at all, we probably shouldn't make too hard to trigger

<img width="840" alt="screen shot 2015-10-01 at 8 27 25 pm" src="https://cloud.githubusercontent.com/assets/2140548/10237083/346bcc46-687b-11e5-809b-3b501cb8701b.png">

**Comment by jcushman** [comment]
Fixed on stage.
