### ISSUE TITLE
Can't add - delete - add with folders

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#1151]
If you add a new folder, then delete it, then try to add another, the `+` button isn't active and doesn't trigger the create folder action

**Comment by abziegler** [comment]
Looks like reason is that after delete, there's no active/highlighted folder, within which a new folder could be created. So more a UX thing than a bug. Perhaps we should default-highlight the parent folder for the folder that was just deleted?

**Comment by jcushman** [comment]
Fixed on stage.
