### ISSUE TITLE
Capture not displaying on stage

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#1157]
Still seeing this on some (but not all) capture attempts using stage

<img width="1032" alt="screen shot 2015-10-02 at 6 02 59 am" src="https://cloud.githubusercontent.com/assets/2140548/10244165/7be9c21c-68cb-11e5-8bb1-c9bbc64fd247.png">

**Comment by jcushman** [comment]
What URL is this for?

**Comment by abziegler** [comment]
Example.com

**Comment by jcushman** [comment]
Should be fixed.
