### ISSUE TITLE
No decrement on link count

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#1163]
When you create a link that's affiliated with "Yourself," it should decrement your monthly link count by 1

**Comment by abziegler** [comment]
Just tested this again as test_user@example. Created 2
![screen shot 2015-12-03 at 8 49 19 am](https://cloud.githubusercontent.com/assets/2140548/11562163/31df117c-999a-11e5-8f05-331732066eee.png)
 links and now see this:

**Comment by jcushman** [comment]
This now seems to be working on stage -- I had to switch the mysql database we were using for Heroku to one that knows about timezones.
