### ISSUE TITLE
Remove allow-top-navigation from iframe

### ISSUE THREAD

**Issue by jcushman** [harvard-lil/perma#1169]
Right now we have "allow-top-navigation" on our sandboxed iframe, which could allow a malicious site to mess with our users.

We have this set so the links will work in our error message when a user clicks a link within a capture ("you could check the Internet Archive or view the link as it exists on the live site").

To work around that, we could have those links work through some sort of inter-frame communication javascript with a whitelist, instead of allowing top navigation globally.

**Comment by matteocargnelutti** [comment]
Client-side playback doesn't have this issue (at least not exactly the same). Legacy playback will be phased out.
