### ISSUE TITLE
Manage page records no longer expanding/collapsing on touch event (mobile)

### ISSUE THREAD

**Issue by thisisdano** [harvard-lil/perma#1173]

**Comment by jcushman** [comment]
I can mess with this -- I changed the jquery stuff to handle both click and drag. I think we just need to change the event listeners for that to also listen for touch events.

**Comment by jcushman** [comment]
@thisisdano -- I think this is fixed on perma-stage.org. Can you confirm on iOS?

**Comment by jcushman** [comment]
Confirmed working on stage.
