### ISSUE TITLE
Button alignment seems off in some places

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#1178]
e.g. organization settings
![screen shot 2015-10-08 at 10 33 56 am](https://cloud.githubusercontent.com/assets/2140548/10369346/c093286e-6da7-11e5-896a-8abf3bd6ced7.png)

e.g. registrar edit
![screen shot 2015-10-08 at 10 34 03 am](https://cloud.githubusercontent.com/assets/2140548/10369366/ded37518-6da7-11e5-9a1d-a95b2de1055d.png)

**Comment by thisisdano** [comment]
I ought to be able to address the first one. The second appears like this because (I think!) I'm not able to directly edit the form. The form is autoformatted through a call from the template rather than hard-coded into the template itself.

**Comment by thisisdano** [comment]
What user type is associated with that first settings field?

**Comment by jcushman** [comment]
First button is looking good now.

@dano, what changes would you need to be able to style the registrar edit form? Right now that form is being printed by a generic bootstrap-form template -- we could potentially smarten that up rather than have to hardcode everything.
