### ISSUE TITLE
Screen for adding an existing user to an org needs styling

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#1180]
If a org or registrar user tries to add an existing user to an org, then we give notice that user already has an account and ask if would like to add user to org.

Looks like the dropdown menu hasn't been styled.
![screen shot 2015-10-08 at 10 44 10 am](https://cloud.githubusercontent.com/assets/2140548/10369650/58526196-6da9-11e5-87f6-0474ce9865ab.png)

**Comment by jcushman** [comment]
This looks good on stage ...
