### ISSUE TITLE
Weird layout for error page

### ISSUE THREAD

**Issue by cdemarco** [harvard-lil/perma#1185]
When I tried to login with an account that had not yet been activated, the page was to wide for my screen (already a widescreen monitor - running Chrome for Windows).
![image](https://cloud.githubusercontent.com/assets/5711415/10412774/835b7ed4-6f5e-11e5-89b0-37fc62096898.png)

**Comment by abziegler** [comment]
Claire has reported a couple of similar errors - could there be an issue with screen-sizing on Chrome for Windows? see also #1187

**Comment by jcushman** [comment]
Confirming this issue on up-to-date Chrome for Mac. URL /login/not-active:

![image](https://cloud.githubusercontent.com/assets/376272/11697619/603eba16-9e88-11e5-8b33-eabea58f7b06.png)

**Comment by jcushman** [comment]
@thisisdano: It's better, but something is still a bit weird here -- the row content isn't staying inside the parent div's padding. It's more visible on mobile, although the same thing happens in the desktop stylesheet. Here's a screenshot with the padding on `<div class="container cont-fixed">` highlighted:

![image](https://cloud.githubusercontent.com/assets/376272/11700506/31989ad2-9e98-11e5-9f4c-ef35df3e0066.png)

(This is in Chrome for Mac, so should be easy to test locally.)

**Comment by thisisdano** [comment]
OK — I ought to be able to get this.

**Comment by thisisdano** [comment]
Should be good in the next PR.

**Comment by jcushman** [comment]
Looking good.
