### ISSUE TITLE
Django admin log back in page gave 404

### ISSUE THREAD

**Issue by cdemarco** [harvard-lil/perma#1186]
Clicked logout and then the sign back in link and got a 404
![image](https://cloud.githubusercontent.com/assets/5711415/10412788/e5fe55c0-6f5e-11e5-9f8c-14a6e0a2b672.png)

**Comment by cdemarco** [comment]
Just to clarify, this only happened when I used the logout link from the admin console.  The dashboard logout/login appears to work well.

**Comment by jcushman** [comment]
Fixed on stage.
