### ISSUE TITLE
Adding someone who already has an account - wonky layout

### ISSUE THREAD

**Issue by cdemarco** [harvard-lil/perma#1187]
When I go to add someone as a Vesting User or Registrar User who already has an account, the screen jumps really wide so that the main content of the page overhangs the indent of the title.  Looks weird.
![image](https://cloud.githubusercontent.com/assets/5711415/10412800/32349ac6-6f5f-11e5-854c-c7728624d032.png)

**Comment by abziegler** [comment]
weird one. I wasn't able to replicate. this is on Chrome right?

**Comment by cdemarco** [comment]
Yep - chrome for windows - my work computer though, so arguably not the most up to date version.  Happy to try to recreate when I'm back in the office.

**Comment by jcushman** [comment]
Tried this on older Chrome for Windows and everything looks fine now.
