### ISSUE TITLE
Removed a Registrar User, then tried to re-add the Registrar User - Error

### ISSUE THREAD

**Issue by cdemarco** [harvard-lil/perma#1189]
When removing and re-adding Registrar Users I'm getting this error.  Could be that I'm doing it too fast.  Still has that weird margins issue too.
![image](https://cloud.githubusercontent.com/assets/5711415/10412846/ac266ff2-6f60-11e5-80ef-9cf87dec23a9.png)

**Comment by cdemarco** [comment]
Still happening - it may be that b/c I'm trying to add someone who was originally a Vesting User as a Registrar User.  Would we ever want that kind of functionality? Maybe?
![image](https://cloud.githubusercontent.com/assets/5711415/10412868/7fc37b52-6f61-11e5-816b-125c22c994cd.png)

**Comment by cdemarco** [comment]
Sorry I forgot to assign this on Saturday - going through and making sure I've assigned them all properly now.

**Comment by anniejocain** [comment]
Yes, it is because the user is an org member already. Org members cannot currently also be added as registrar members. Do we want this functionality?

**Comment by anniejocain** [comment]
Functionality doesn't currently exist. Booting this off the post vesting milestone.
