### ISSUE TITLE
Change capture engine to Firefox?

### ISSUE THREAD

**Issue by cdemarco** [harvard-lil/perma#1190]
Why would the screen capture view look any different than the live site the moment after I've created it?  Here's whitehouse.gov in the screen capture view:
![image](https://cloud.githubusercontent.com/assets/5711415/10412872/049bc122-6f62-11e5-828b-00668bc716ef.png)

Here's whitehouse.gov in the live view
![image](https://cloud.githubusercontent.com/assets/5711415/10412874/1439e50a-6f62-11e5-9564-c7b87a089f4f.png)

In this case it's just the menu that isn't rendering properly, but I'm just wondering why a screen cap isn't actually a screen cap.

**Comment by abziegler** [comment]
Not sure this is a bug. Could you test a couple more times and see if it reproduces?

**Comment by jcushman** [comment]
I have a branch that uses up-to-date Firefox for captures instead of PhantomJS, which could help with this.

**Comment by jcushman** [comment]
Moving to #1319
