### ISSUE TITLE
Secondary Link Message doesn't work

### ISSUE THREAD

**Issue by cdemarco** [harvard-lil/perma#1191]
When I click to "view the link as it exists on the live site" from this page, it just reloads this error page
![image](https://cloud.githubusercontent.com/assets/5711415/10412884/6fc99aa0-6f62-11e5-95dc-bcd26901b7a1.png)

**Comment by abziegler** [comment]
@cdemarco the URL in your image looks a little weird -- not sure it reflects the live page, but rather a concatenation of perma link and live page. Am I missing something?

**Comment by cdemarco** [comment]
So I was looking at the Perma record page, clicked a secondary link therein, and got the message "you could check the internet archive or view the link as it exists on the live site."  When you click the "view the link as it exists on the live site" URL it doesn't take you to the live site, it just reloads that page.

**Comment by jcushman** [comment]
Confirmed.

**Comment by jcushman** [comment]
Fixed on stage.
