### ISSUE TITLE
Able to move links from one Vesting Org to the other - shouldn't be

### ISSUE THREAD

**Issue by cdemarco** [harvard-lil/perma#1193]
I'm able to move links between org folders - that shouldn't be the case at the Vesting User level ...
![image](https://cloud.githubusercontent.com/assets/5711415/10413038/e759d3d0-6f69-11e5-98d7-67190001a432.png)

**Comment by cdemarco** [comment]
You can see in the image above that the link is affiliated with "Claire's Test Vesting Organization" - but I was able to move it into the Plebs Publica Law Journal folder.

**Comment by cdemarco** [comment]
For a minute it behaved properly (giving me a no symbol when I tried to move it), but then I was able to try again and move links between my links and the different vesting org folders without issue.

**Comment by abziegler** [comment]
@cdemarco were you able to move it only within the first 24 hours (aka the delete/edit window), or did you do this after that period had passed?

**Comment by cdemarco** [comment]
Oh that's an interesting distinction - again I'll try going back to recreate this.

**Comment by phillipsm** [comment]
I think we decided to allow movement between orgs (if a person is a member of both orgs)

**Comment by anniejocain** [comment]
Built to allow movement between orgs as long as member of both orgs.
