### ISSUE TITLE
Error 401 on link creation page

### ISSUE THREAD

**Issue by cdemarco** [harvard-lil/perma#1195]
Not sure what a 401 is ... here's the image.

![image](https://cloud.githubusercontent.com/assets/5711415/10413073/4b6b13b0-6f6b-11e5-951b-94efe8d40fda.png)

**Comment by jcushman** [comment]
Error 401 means you've somehow become logged out and you have to log back in again.

I just sent a pull req that shows a clearer error message:

![image](https://cloud.githubusercontent.com/assets/376272/10491345/4562a71a-7274-11e5-8cd3-83515f7d9433.png)

It's possible for the unexpected log-out to be our fault -- if this happens frequently we can look into it.
