### ISSUE TITLE
Folder page bogs down on use. Profile JS on link page.

### ISSUE THREAD

**Issue by phillipsm** [harvard-lil/perma#1206]
Some fantastic notes from @aarongustafson 

> I notice a little bit of lag when editing a bunch of links at once. I think there must be an issue with garbage collection or event assignment or something. I was editing titles and moving stuff from "My Links" to the book folder and after a few dozen the browser started to crawl. Refreshing the page helped. I have not tucked into the code yet, but if I had to guess, I would imagine the eventing for auto-save, folder filing, etc. is all assigned per-field rather than at the container level. That overhead could be the issue. Event delegation might be a better option. Alternately, DOM references may not be getting collected once the elements are destroyed; that can eat RAM

**Comment by jcushman** [comment]
We have some changes in the post-vesting branch that will help with this -- can look into this more after that goes out.

**Comment by jcushman** [comment]
Next step: let's just try to reproduce this in a few browsers and see if it's still a thing.

**Comment by matteocargnelutti** [comment]
Apparently no longer a problem with 2022 browsers.
