### ISSUE TITLE
Throttle title/notes saving for a link

### ISSUE THREAD

**Issue by phillipsm** [harvard-lil/perma#1208]
We should maybe wait 750ms (or whatever seems right) after keypress to throw the title and note field values at the API. 

A note from @aarongustafson 

> The auto-save for the titles doesn’t always catch everything. It seems to be triggered by keystroke without throttling. It might be worth putting that on a throttled timer that only saves it once the user has paused their typing for a second or a fraction of a second.

**Comment by aarongustafson** [comment]
A good way to throttle is to set the listener with a custom method and then keep clearing and resetting the timer. An example with similar requirements is testing for resize events. You don’t want to fire the whole time someone is resizing, but rather when they are done. The same goes for typing. You can check out the code I use for that [in this gist](https://gist.github.com/aarongustafson/4157402).

**Comment by jcushman** [comment]
We actually do throttle saving to one every three seconds (although the first save kicks off immediately):

https://github.com/harvard-lil/perma/blob/dev.post-vesting/perma_web/static/js/links-list.js#L35

Not sure exactly what you're experiencing, Aaron -- maybe the three second window is long enough that you're managing to leave before it kicks off, or there's some other bug in there?

**Comment by aarongustafson** [comment]
The issue comes down to it saving the value from a few seconds ago. When I
am typing, the value is updated in the preview on the right, but then the
actual saved value is missing several letters (or even words). Must be a
timing issue.

**Comment by jcushman** [comment]
> The issue comes down to it saving the value from a few seconds ago.

Ah ha! That was it. Turned out not even to be a proper race condition, just a logic error of saving the wrong value.

Thanks for the tip about clearing the timer -- that simplified the logic a lot.

**Comment by aarongustafson** [comment]
Glad I could help :-)
