### ISSUE TITLE
Length limitation on edited title

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#1209]
User report...that I've confirmed:

If user edits the title of a Perma Link, then the edited title gets clipped off on display on Record View page. 

See, e.g.: https://perma.cc/33EJ-62E3?type=source

![screen shot 2015-10-16 at 11 51 08 am](https://cloud.githubusercontent.com/assets/2140548/10546411/cf517130-73fb-11e5-839e-d591b8336a5f.png)

**Comment by jcushman** [comment]
Pretty sure this is the same as #1208 -- we were throwing away characters typed within the last few seconds before save. Maybe another good candidate to push out early.
