### ISSUE TITLE
Logo carousel not responding to admin console upload

### ISSUE THREAD

**Issue by cdemarco** [harvard-lil/perma#1210]
I've been uploading logos using the admin console upload, but they're not getting pulled into the carousel - NY Law school has asked a couple of times, and I've been putting them off, presuming that it was coming in another release, but chatted with Adam, and that shouldn't be the problem ...

Apparently some people are still really into the logos!  Can you help, Jack?

**Comment by jcushman** [comment]
Yeah, I held off on implementing this, because I wasn't sure where the carousel would end up in the new design -- it's still just static for now.

@thisisdano -- I take it we're keeping the carousel on the home page and about page, and I should go ahead and set it to auto-update?

**Comment by jcushman** [comment]
Carousel and map are now auto-updated.
