### ISSUE TITLE
Your Perma Links: Should infinite scroll be triggered by a button press instead?

### ISSUE THREAD

**Issue by thisisdano** [harvard-lil/perma#1218]
Automatic infinite scroll means you can "never" access the footer on YPL (if you have a lot of records). Perhaps this isn't much of an issue, but maybe instead of the infinite scroll we can have a "Show more records" button?

**Comment by jcushman** [comment]
Good question -- not being able to reach the footer is annoying. OTOH I think for a big folder having to click "show more" a lot would be annoying as well.

What do you think of doing a scrollable div for the record list, so it's infinite scroll inside the div but you can still scroll past the whole div to get to the footer? If we let you scroll your folder list separately from the records list that could be a usability win anyway -- e.g. if you were trying to drag and drop a bunch of links to a new folder.

**Comment by thisisdano** [comment]
Sorry so late on this — I think I like the implementation on Instagram for the web: one push to trigger infinite scroll. That way, you can access the footer (if needed) but trigger infinite scroll if desired. Obvs not a first-class issue right now!

**Comment by jcushman** [comment]
First pass low hanging fruit: let's try making both the folder list and link list overflow-scroll.

**Comment by rebeccacremona** [comment]
Or, controversially: how about we use Django pagination instead?

**Comment by rebeccacremona** [comment]
Just tested this: I'm finding that it doesn't actually work that reliably. Depending on where your cursor is, how fast you manage to scroll..... even if you get to the bottom, the links tend to catch up with you pretty quickly, and bump the footer out of sight just as soon as you get ready to click on it lol. The scrollbars are also pretty ugly. I could easily be doing this wrong, but not this technique is going to work as a first pass.

**Comment by rebeccacremona** [comment]
That's the case whether you make each column scroll independently, or the whole row as a unit.

**Comment by rebeccacremona** [comment]
I still think pagination is better, always and everywhere, unless a person is idly scrolling for content (as in a twitter feed), but we've had that argument already, and I lost lol. 

I'm going to implement Dano's suggestion: "I think I like the implementation on Instagram for the web: one push to trigger infinite scroll. That way, you can access the footer (if needed) but trigger infinite scroll if desired."

And then we can keep discussing this, until we find something we all like. But in the meantime, the footer will be available. 😉

**Comment by rebeccacremona** [comment]
overflow=scroll works when you actually set a static height for the div... which is of course what Jack was recommending above.

So we'll do that, using js to pick some height that makes sense for the viewport.

And come back for another round of arguing about infinite scroll the next time I have energy.

**Comment by rebeccacremona** [comment]
part 2 https://github.com/harvard-lil/perma/pull/2301
