### ISSUE TITLE
Unable to remove org users from organization

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#1220]
After registrar user clicked "remove" button to detach a vesting user from a vesting org, registrar user got 404 page. I have specific account details if helpful.

**Comment by phillipsm** [comment]
I'm having problems recreating this. I was signed in as a registrar member. I added a new org member and then removed that new member.

Anyone else have luck with reproducing this?

**Comment by phillipsm** [comment]
I couldn't reproduce this and haven't heard of anyone else reproducing this.
