### ISSUE TITLE
Private links visibility

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#1236]
On private Record View page we currently say: "This record is private. It’s only visible to libraries and your Archiving Organization."

Private links should be visible only to the Registrar and to the Archiving Organization. They should not be visible to all libraries.

Is this a issue with message only, or is the visibility itself too broad?

**Comment by jcushman** [comment]
Just an issue with the message. I sent a pull request that changes it to: "This record is private. It’s only visible to members of Test Journal and the Test Library registrar." Or for links outside an org folder: "This record is private. It’s only visible to you."
