### ISSUE TITLE
Document API creation of org links

### ISSUE THREAD

**Issue by jcushman** [harvard-lil/perma#1240]
Looks like we've extended the API to accept an 'organization' field when creating links -- we should prolly document that [here](https://perma-stage.org/docs/developer#create-an-archive).

That doc could also mention how to get the list of valid orgs to submit (via [this call](https://perma-stage.org/docs/developer#get-user-vesting-orgs)).

**Comment by rebeccacremona** [comment]
This is not presently the case.
