### ISSUE TITLE
We have some "vesting" language stowaways

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#1241]
On the org/user management screen, for example, we're still referring to vesting orgs and vesting users. Could we search for more stragglers across the codebase?

![screen shot 2015-12-03 at 2 45 34 pm](https://cloud.githubusercontent.com/assets/2140548/11571758/f3a65bae-99cb-11e5-8558-5eaa359f6f13.png)

**Comment by abziegler** [comment]
Found another one - on page to confirm that user wants to leave an org:
![screen shot 2015-12-09 at 10 14 27 am](https://cloud.githubusercontent.com/assets/2140548/11689004/c9ff667e-9e5d-11e5-9815-500ca92e5c76.png)

**Comment by phillipsm** [comment]
fixed in https://github.com/harvard-lil/perma/pull/1278
