### ISSUE TITLE
IE10 Record Page Resizing

### ISSUE THREAD

**Issue by cdemarco** [harvard-lil/perma#1245]
When you resize the browser window on a record page in IE9 the bar at the top ends up with some very broad spacing.  This may just be an IE9 issue, not something we need to fix - it may be responsive enough for our purposes, but here's the image:

![image](https://cloud.githubusercontent.com/assets/5711415/11591681/aaca43b8-9a67-11e5-8a92-7ed81733f562.png)

**Comment by cdemarco** [comment]
The site below also has trouble resizing with the window in IE9.  The default seems to open it as less than full browser size, and if you expand, the part of the page that displays the record stays short with an extra scroll bar:

![image](https://cloud.githubusercontent.com/assets/5711415/11591782/55e583f2-9a68-11e5-89f7-a15492929c05.png)

**Comment by cdemarco** [comment]
There's also something weird about the way the site displays when you resize the page - some sites end up cut off halfway down with a lot of white space at the bottom. 

![image](https://cloud.githubusercontent.com/assets/5711415/11592545/1fd34fce-9a6d-11e5-8210-c0b007618f9e.png)

**Comment by cdemarco** [comment]
This carries over to the record page after link creation as well:

![image](https://cloud.githubusercontent.com/assets/5711415/11592969/b3c1a0e4-9a6f-11e5-9b20-c1041b68b162.png)

**Comment by thisisdano** [comment]
Couple issues here.

Part of this is IE layout weirdness. Narrow windows will trigger the tablet
and mobile responsive layouts, which use CSS ordering rules that IE9 can't
parse (flexbox). Are very narrow screens in IE9 a realistic possibility? I
need (at least I *think* I need) to use these rules on mobile and tablet,
so *knowing a good minimum width for desktop browser windows will be
helpful. *Rebuilding this page without flexbox at narrow widths would
require a complete rebuild, and IDK how I would do it.

Can we output different html at different widths from the server side?

The sizing of the bottom area is, I believe, a javascript thing. JS
computes the size of the bottom area at page load — perhaps it should also
trigger at window resize.

I can work on the first (a bit!) and would be much slower on the second
than any dev.

**Comment by jcushman** [comment]
This applies to IE10 as well -- below about 950 pixels the top header gets wonky as in Claire's first image.

**Comment by jcushman** [comment]
@anastasia: is this still a live issue?

**Comment by jcushman** [comment]
It's perfect now.
