### ISSUE TITLE
IE9 Header/Logo

### ISSUE THREAD

**Issue by cdemarco** [harvard-lil/perma#1246]
Even on full screen, the Perma logo wraps in a weird way on the sign in page in the upper left.

![image](https://cloud.githubusercontent.com/assets/5711415/11592091/74be4b4a-9a6a-11e5-84f7-68756d539576.png)

**Comment by cdemarco** [comment]
Not just on the sign-in page - this issue continues onto the link creation page too.

**Comment by jcushman** [comment]
Logo looks fixed in IE.
