### ISSUE TITLE
Creating links in IE9

### ISSUE THREAD

**Issue by cdemarco** [harvard-lil/perma#1247]
I have tried to create links for several sites in IE9 through saucelabs, and I keep getting this blank page:

![image](https://cloud.githubusercontent.com/assets/5711415/11592359/026a7666-9a6c-11e5-8353-8d4be82b32b0.png)

I have tried logging in as different types of users, creating links for different sites, and I am still getting the same result.

**Comment by jcushman** [comment]
Looks like an IE javascript error - good catch.

**Comment by anniejocain** [comment]
Neither of my fixes worked. Anybody else want to take a crack?

**Comment by jcushman** [comment]
I'll take a shot.
