### ISSUE TITLE
Create page not fetching folder contents

### ISSUE THREAD

**Issue by anniejocain** [harvard-lil/perma#1252]
Signed in as test org user. 

Create page doesn't select a default folder and doesn't fetch any folder contents.

**Comment by jcushman** [comment]
Is this still happening for you? If so, maybe it's browser specific? This is what I'm seeing:

![image](https://cloud.githubusercontent.com/assets/376272/11602379/d88a5e92-9aa7-11e5-8207-b149356831f9.png)

**Comment by anniejocain** [comment]
Nope, doesn't seem to be an issue now.
