### ISSUE TITLE
JS error in Raphael on landing page

### ISSUE THREAD

**Issue by phillipsm** [harvard-lil/perma#1273]
![screen shot 2015-12-10 at 1 09 42 pm](https://cloud.githubusercontent.com/assets/196089/11724015/6703a188-9f3f-11e5-9195-3e4abf14d7a2.png)

**Comment by jcushman** [comment]
Seeing a few different JS errors popping in up in Rollbar related to this. Maybe it's just that we're still including the map JS in the homepage even though the map itself is gone?

**Comment by anniejocain** [comment]
Yeppers. I'll roll it into my little pull request.

**Comment by jcushman** [comment]
Homepage now js-error free.
