### ISSUE TITLE
Need Perma Links for all outside links on the landing page

### ISSUE THREAD

**Issue by thisisdano** [harvard-lil/perma#1283]
All the outside links have a little infinity box — which is a link to it's Perma Link record. But they don't have these yet. I don't have a vesting acct. Can someone make these outside links — or should we wait until the new site goes live and we can capture using all the latest bells/whistles?

**Comment by phillipsm** [comment]
Done. About a quarter or so went to private archives, so I tool the links to those out. Feels like a loss. Created a new issue to address that, https://github.com/harvard-lil/perma/issues/1292 . Maybe a good perma meeting topic, @abziegler?
