### ISSUE TITLE
How best to highlight private archives from landing page?

### ISSUE THREAD

**Issue by phillipsm** [harvard-lil/perma#1292]
The landing page wants to link to some private Perma archives. Should we make exceptions for these things that are marked as private? Should we link to the original, but drop the link to the archve?

Seems like a missed opportunity if we have to keep them in their `{% comment %} {% endcomment %}` blocks
- In Supreme Court Opinions, Web Links to Nowhere  29M5-WXFZ
- Stopping Link Rot: Aiming to End a Virtual Epidemic 4FMC-8C6W
- Death to “Link Rot”: Here's Where the Internet Goes to Live Forever P55P-ZZ28
- In Supreme Court Opinions, Web Links to Nowhere 9KZC-ENLD

**Comment by jcushman** [comment]
Design decision: don't include Perma links for articles where the archive is private, but do include links to the original. When working on news coverage bug, add back in the currently commented-out links.
