### ISSUE TITLE
Update link count available when link is dragged in folder list

### ISSUE THREAD

**Issue by phillipsm** [harvard-lil/perma#1294]
If I drag a link from my personal folder to and org folder, it'd be nice to see a realtime, javascript update of the link count (add one to the Yourself[ ] element). The opposite (org folder --> My Links) for a decrement too.

![screen shot 2015-12-14 at 4 52 05 pm](https://cloud.githubusercontent.com/assets/196089/11795131/0bf0dabc-a283-11e5-85ec-f3dbadcafc5c.png)

**Comment by jcushman** [comment]
Not sure of the cleanest way to do this -- maybe we need to add links-remaining to the API?
