### ISSUE TITLE
Record details tray has an unexpected dropdown

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#1300]
Don't know what this is:

![screen shot 2015-12-17 at 10 27 18 am](https://cloud.githubusercontent.com/assets/2140548/11873533/04494236-a4a9-11e5-82c4-690e1d6bf6e0.png)

**Comment by jcushman** [comment]
That's for staff only and allows us to indicate why something is private - because of copyright takedown, or to manually fix a missed noarchive tag or whatever.
