### ISSUE TITLE
Delete link not showing on newly created links

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#1306]
On perma-stage, link listing is displaying delete link for links still within the 24 hour delete window. Delete link is present on record view page.

![screen shot 2015-12-18 at 4 40 11 pm](https://cloud.githubusercontent.com/assets/2140548/11907965/2f93b234-a5a6-11e5-834e-f9cd767865e5.png)

Not sure if this relates to @anastasia work on foldering (which is awsome!) but maybe? It does seem to be working fine on live site.

**Comment by jcushman** [comment]
Fixed on prod.
