### ISSUE TITLE
Messaging on errors with htm files

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#1308]
User tried to capture: http://usatoday30.usatoday.com/sports/college/football/2009-coaches-contracts-database.htm  

Capture seems to have failed, and we rendered message that said: "Perma.cc can’t display this file type.  Click below to view or download this archived file (file type)." But on click we rendered message that said "Playback unavailable." 

Something wrong with capture and/or messaging?

**Comment by jcushman** [comment]
Taking a look at this ... seems to be a problem both with capture and messaging for failed captures.
