### ISSUE TITLE
Change capture engine to Firefox

### ISSUE THREAD

**Issue by jcushman** [harvard-lil/perma#1319]
We should switch to using a popular, up-to-date browser for captures, rather than PhantomJS.

Firefox is currently a better option than Chrome because it takes full-page screenshots: https://bugs.chromium.org/p/chromedriver/issues/detail?id=294

**Comment by jcushman** [comment]
Benefits -- screenshots are a lot nicer. Here's PhantomJS:

![image](https://cloud.githubusercontent.com/assets/376272/11980168/e25c2d24-a966-11e5-8900-18ce8a5ec686.png)

vs. experimental Firefox capture:

![image](https://cloud.githubusercontent.com/assets/376272/11980172/eee308ce-a966-11e5-8456-10fa9497bce1.png)

**Comment by jcushman** [comment]
Becky will try this out locally and let us know if it works well enough to deploy.

**Comment by jcushman** [comment]
Ben will tell Becky what to install in vagrant for the test.

**Comment by rebeccacremona** [comment]
(we've decided to move to headless chrome, when possible, instead)
