### ISSUE TITLE
A few spacing issues on small screen

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#1323]
user management screen:

![screen shot 2016-01-04 at 2 10 20 pm](https://cloud.githubusercontent.com/assets/2140548/12097984/0e719aae-b2ed-11e5-8c9a-923770d60097.png)

**Comment by jcushman** [comment]
Pretty sure we don't support Perma having that many users.

**Comment by abziegler** [comment]
Kind of a lot of unactivated users, no? Maybe we should re-ping after x days?

**Comment by rebeccacremona** [comment]
Fun fact: this page now take several seconds to load.
