### ISSUE TITLE
Adding a User in IE produces error message

### ISSUE THREAD

**Issue by cdemarco** [harvard-lil/perma#1324]
See my correspondence with Deborah Darin from Marquette below - read from the bottom up.

I am using a PC at work, and I use IE.   

I can try to do some things from my iPad, too, just to experiment later.  

Shouldn’t we be able to do it both ways?  

Feel free to share all my emails, it is fine.  

Thanks,

Deborah

From: Claire DeMarco [mailto:cdemarco@law.harvard.edu] 
Sent: Wednesday, January 6, 2016 1:38 PM
To: Darin, Deborah <deborah.darin@marquette.edu>
Subject: RE: Two things

 Interesting – do you mind me asking what type of computer (Mac/PC) and which browser (Firefox/IE/Chrome) you are using so we can put it in as a bug?

Thanks!

Claire

From: Darin, Deborah [mailto:deborah.darin@marquette.edu] 
Sent: Wednesday, January 06, 2016 2:36 PM
To: Claire DeMarco
Subject: RE: Two things

Claire,

Ok, that was weird.  It did work to do it your way.  You went in via org users, and I think I had tried via organizations, and then tried to add a user to the Professor Elana Olson organization, i.e., under that heading, I clicked on the name of the org and was able to attempt to add a user, but it did not take.  But I am still not sure why.  

Maybe it was because I had her in the library org that I deleted this week.  Cannot remember how I had added her to that, but that may be why it was remembering her.  It seems like the software wants you to present a user email and then choose the organization, not the other way around.  

Also, when I did it your way, the box I got did not say “email” – it was just blank.  Not sure why.  It would be good if it did say email, so the person adding knows not to just put a name there.

 Elana just emailed me and she has activated her account, and it is activated from my view, too.  

 Deborah

From: Claire DeMarco [mailto:cdemarco@law.harvard.edu] 
Sent: Wednesday, January 6, 2016 1:20 PM
To: Darin, Deborah <deborah.darin@marquette.edu>
Subject: RE: Two things
 
I am not sure how that error is coming up for you.  Here’s a set of screenshots detailing how I would do it – let’s see where our workflows diverge.  Thank you in advance for all of this – it’s incredibly helpful feedback to see where/how the site is not performing properly.

Here’s the first screen I see when I click on org users (ignore my numbers, b/c obviously I’m dealing with a much larger population of users than you are):
![1](https://cloud.githubusercontent.com/assets/5711415/12152786/6a4e8682-b484-11e5-9db2-654258cc28af.jpg)

I click “add organization user” in the upper right hand corner and this pops up:
![2](https://cloud.githubusercontent.com/assets/5711415/12152778/6252968a-b484-11e5-8a43-443d870d587e.jpg)

If I enter Professor Olson’s email address I get this message and can select the Org “Professor Elana Olson”:
![3](https://cloud.githubusercontent.com/assets/5711415/12152773/5f22900a-b484-11e5-90ed-9e3e02259e8e.jpg)

Could you try that workflow and tell me a) if it works for you, and b) how it differs from your own?

Thanks,

Claire

From: Darin, Deborah [mailto:deborah.darin@marquette.edu] 
Sent: Wednesday, January 06, 2016 2:08 PM
To: Claire DeMarco
Subject: Two things
 
Claire,

I am not sure why this happened, but when I added an organization called Professor Elana Olson, and then tried to add her as the user, I got the message below that a user with her email already exists.  Maybe that is because I had set up another organization this week for the law library and added her, but then I deleted the organization.  

![deborah darin](https://cloud.githubusercontent.com/assets/5711415/12152752/3b8dfcf6-b484-11e5-932b-ea847f875c54.jpg)

But even if that is creating some problem (can you check to see if it is deleted properly?), why can’t the same user be in more than one organization?  

Thanks.

Deborah

**Comment by jcushman** [comment]
We think this seems to be working as intended at this point -- feel free to re-open if you don't think so, @cdemarco.
