### ISSUE TITLE
Folder error for users with two accounts or more

### ISSUE THREAD

**Issue by anastasia** [harvard-lil/perma#1327]
To recreate error:
- sign in with your usual account
- save a link to an organization
- see it save without any issues
- sign out
- sign in with a second account
- save a link
- see it error
- resolve the error by clicking on a folder from the folder tree or choosing from the dropdown menu
- save again
The reason for this is that we're using localStorage to remember what folder was accessed last, but we are not name-spacing it with any user data (like email, or user id).
This is probably an edge-case but would happen if someone has a business account (library account) as well as a personal one they access on the same computer.

![Error] (https://s3.amazonaws.com/uploads.hipchat.com/26114/809789/bkd3get0Zg8MCiU/Screen%20Shot%202016-01-12%20at%2011.04.12%20AM.png)

![Folder not found] (https://s3.amazonaws.com/uploads.hipchat.com/26114/809789/Qa208Dhyode4uLa/Screen%20Shot%202016-01-12%20at%2011.04.21%20AM.png)

**Comment by jcushman** [comment]
Good catch! I like the idea of scoping to user ID, so you could switch back and forth and have both settings stick. Want to take this one on?

**Comment by anastasia** [comment]
Yup!
