### ISSUE TITLE
Link count for one organization is wrong 

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#1332]
From manage users view, the link count for UPenn Journal of International Law is displaying zero, when the actual link is ~120 and the org's folder reflects accurate count.

**Comment by jcushman** [comment]
I took a look and am pretty sure this is now working correctly for this org -- not sure what might have happened.

**Comment by abziegler** [comment]
Same org still showing two different link counts:

1096

<img width="914" alt="screen shot 2016-02-26 at 2 35 10 pm" src="https://cloud.githubusercontent.com/assets/2140548/13363219/493c3356-dc96-11e5-95b0-4d46c6174893.png">

1073

<img width="970" alt="screen shot 2016-02-26 at 2 35 46 pm" src="https://cloud.githubusercontent.com/assets/2140548/13363223/51c17234-dc96-11e5-9a5f-0d46e6a4f7b9.png">
