### ISSUE TITLE
Link count not going back up

### ISSUE THREAD

**Issue by cdemarco** [harvard-lil/perma#1335]
I created a link with the My Links folder selected and saw my link count go down.  I went back to my list and moved that link (using the expanded options, not the drag and drop) into a journal folder, but my link count did not go back up (PC/Chrome).

**Comment by cdemarco** [comment]
Oh it did go back up, but only after I navigated away from the page and came back - any way to make that a faster refresh?

**Comment by jcushman** [comment]
Is the count correct if you refresh the page?

**Comment by jcushman** [comment]
Oops, sounds like yes. I believe @anastasia has a bug open to make that count update instantly.
