### ISSUE TITLE
Images sometimes appear broken

### ISSUE THREAD

**Issue by anastasia** [harvard-lil/perma#1336]
Images are sometimes (not always) not archived:
https://perma.cc/WPR3-8JSR
https://perma-stage.org/45XT-YEV3
https://perma-stage.org/RG7W-AZNY

**Comment by jcushman** [comment]
I suspect this is because we're not scrolling the browser slow enough from the top of the page to the bottom, to trigger images that are loaded by javascript when they come into view:

https://github.com/harvard-lil/perma/blob/develop/perma_web/perma/tasks.py#L412
