### ISSUE TITLE
500 error as page title

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#1365]
A link bizarrely has a 500 error as the page title. Seems unintended. Link is: https://perma.cc/H2D9-Z4C4

<img width="1238" alt="screen shot 2016-02-17 at 8 49 06 am" src="https://cloud.githubusercontent.com/assets/2140548/13111358/5cdf17ce-d553-11e5-8f60-8e009aaf9d03.png">

**Comment by jcushman** [comment]
This is an ancient wget capture -- not sure what's up with it, but not a current issue.
