### ISSUE TITLE
Show upload option on link-captured page

### ISSUE THREAD

**Issue by jcushman** [harvard-lil/perma#1367]
When a user submits a link and we show the result, we used to also have a message that said "Capture doesn't look right? Click here to upload your own." We should re-enable that.

**Comment by anastasia** [comment]
Do we want to edit the record related to the newly created guid? Or should we just link them back to the create page?

**Comment by anastasia** [comment]
"If you don't like it, replace with own upload" (attach to same guid), allow option only in the first hour
