### ISSUE TITLE
Stats page - orientation weirdness

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#1385]
One component on the new stats page needs to be rotated 90 degrees clockwise
![screen shot 2016-03-01 at 9 02 22 am](https://cloud.githubusercontent.com/assets/2140548/13429079/73669a4c-df8c-11e5-92c2-d342629b7e5e.png)

**Comment by phillipsm** [comment]
That's the way they're supposed to look. 😀

If it looks off to you though, maybe it does to other folks and we should adjust the design?

**Comment by abziegler** [comment]
Feels a little off to me. Also looks like we're getting 0 on the total org count.

**Comment by phillipsm** [comment]
this was patched a wats back
