### ISSUE TITLE
Migrate prod to AMQP

### ISSUE THREAD

**Issue by jcushman** [harvard-lil/perma#1392]

**Comment by bensteinberg** [comment]
Is this just a matter of picking a plan at https://www.cloudamqp.com/plans.html and changing BROKER_URL?

**Comment by jcushman** [comment]
Yes, I think so. We're actually using the free CloudAMQP plan on stage, so it would be worth checking our settings there to see if any of them should apply on prod. From settings_heroku.py:

```
BROKER_POOL_LIMIT=1
BROKER_URL = os.environ.get('CLOUDAMQP_URL')
BROKER_CONNECTION_TIMEOUT = 30
BROKER_HEARTBEAT = 30
CELERY_SEND_EVENTS = False  # on the free CloudAMQP plan, celery events rapidly eat up our monthly message quota
CELERY_RESULT_BACKEND = os.environ.get('REDISCLOUD_URL')
```

**Comment by bensteinberg** [comment]
I'm going to close this, but we can reopen it or start a new issue if anything looks broken.
