### ISSUE TITLE
Screenshot View doesn't work in Firefox for images over 32,000px

### ISSUE THREAD

**Issue by pyhedgehog** [harvard-lil/perma#1414]
For many (tall enough) pages, image of screenshot is not displayed. After opening image in another tab firefox shows message `The image “...” cannot be displayed, because it contains errors.`.

Examples:
- https://perma.cc/63AP-6EHJ?type=image
- https://perma.cc/S9DV-WB4Z?type=image

Firefox version 45.0, windows 7 enterprise, amd64

**Comment by jcushman** [comment]
Hi, pyhedgehog. Thanks for the great detail in this bug report.

Confirming the issue -- apparently Firefox can't display images taller than 32,000px:

https://support.mozilla.org/en-US/questions/973667

We'll have to figure out some sort of pagination approach ...

**Comment by matteocargnelutti** [comment]
I suppose this has been addressed as part of Firefox's 2017-ish rebuild. No longer a problem 🎉 .
