### ISSUE TITLE
Folder name has weird styling during edit

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#1422]
On Stage. Chrome. Org user.

Folder edit icon isn't enabled. And when I right-click to access menu, then select 'Rename,' the field is mis-aligned (maybe intentionally?)

![screen shot 2016-03-23 at 9 47 21 am](https://cloud.githubusercontent.com/assets/2140548/13987112/68fa1cda-f0dc-11e5-9736-623d747f1d75.png)

**Comment by anastasia** [comment]
I think this is an existing bug (maybe bump?)

**Comment by jcushman** [comment]
Confirmed that the edit button works if clicked. Bumping to .61 for style issues.
