### ISSUE TITLE
Edited folder name doesn't update in dropdown

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#1423]
I edited the `.selected` folder name, but the old name remained in drop-down
![screen shot 2016-03-23 at 9 49 58 am](https://cloud.githubusercontent.com/assets/2140548/13987192/bc7a0cd0-f0dc-11e5-8282-7aed2e88ee8f.png)

**Comment by anastasia** [comment]
this is an existing bug (maybe bump?)

**Comment by jcushman** [comment]
Yep, bumped to 0.61.

**Comment by jcushman** [comment]
Deployed!
