### ISSUE TITLE
Link counter displaying on org folder

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#1425]
Stage. Chrome. Org user.

When I nav to link creation, a link counter (10) is displaying on org, even though org has no link limit
![screen shot 2016-03-23 at 9 58 24 am](https://cloud.githubusercontent.com/assets/2140548/13987458/ffe56a90-f0dd-11e5-85d8-5e410dd1638d.png)

**Comment by jcushman** [comment]
Fixed on stage.
