### ISSUE TITLE
Interstitials (e.g. ads) do bad things to capture

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#1439]
User reported this problem re: http://www.smithsonianmag.com/history/blue-versus-green-rocking-the-byzantine-empire-113325928/?no-ist

Fortune uses these interstitial ads too. I tested and got this funk, which seems broken 2X:

![screen shot 2016-03-29 at 8 50 07 am](https://cloud.githubusercontent.com/assets/2140548/14108449/7a4d636c-f58b-11e5-8c70-cc4be4e3019c.png)

**Comment by jcushman** [comment]
This particular issue is no longer triggered by Smithsonian -- feel free to re-open with link that shows the issue.
