### ISSUE TITLE
Capture fail message not displaying properly on small screens

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#1444]
Tried this URL: http://www.mondaq.com/unitedstates/x/435110/Financial+Services/Madden+v+Midland+Funding+LLC

Got capture fail message, which itself didn't display right at first (see below), but now does:

![screen shot 2016-04-04 at 11 55 42 am](https://cloud.githubusercontent.com/assets/2140548/14254382/66373d22-fa5d-11e5-8cd4-3f71d0c3dfa0.png)

**Comment by abziegler** [comment]
May be related to #1439

**Comment by anastasia** [comment]
May be resolution related (here's mine):
<img width="1280" alt="screen shot 2016-04-04 at 12 08 22 pm" src="https://cloud.githubusercontent.com/assets/1494102/14254504/01b61ff2-fa5e-11e5-8dd8-cba7aacb0cd6.png">

**Comment by jcushman** [comment]
Creating separate bug for the capture problem here (#1445), and removing 'capture error' label from this bug.

**Comment by anastasia** [comment]
https://perma.cc/U2Z7-TEHV
Added extra padding to error message, should be mostly fixed but need to double check if the code is actually solid long-term.

**Comment by jcushman** [comment]
Per @anastasia, remaining work is to get the message showing on small screens.
