### ISSUE TITLE
When registrar user adds herself to org, she loses access to other orgs

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#1447]
User report, which I confirmed with test account.

1. Registrar user A has access to orgs B, C, D b/c of registrar status
2. Registrar user A makes herself an org user of org B (which was unnecessary)
3. Registrar user A no longer as access to orgs C, D

Is there any reason to allow registrar users to make themselves org users? It seems unnecessary.

If there is reason, then we should make sure that doing so doesn't block them from other orgs.

**Comment by jcushman** [comment]
> Is there any reason to allow registrar users to make themselves org users? It seems unnecessary.

I think that's right -- we shouldn't let anyone make a registrar user also be an org user.

(There's never any need for a registrar user to be an org user for their own orgs. It could in theory make sense to let a registrar be an org user for another registrar's orgs -- but that's a weird edge case and it would be a hassle to fix all the places that we assume someone is only one or the other.)

**Comment by abziegler** [comment]
Note also that if you remove the registrar user from the org, it restores their access to all the orgs

**Comment by abziegler** [comment]
Could also add registrar user contacts on org user page, so that orgs can see who their contact is

**Comment by abziegler** [comment]
Maybe spin this out into a separate feature

**Comment by phillipsm** [comment]
did this get patched up in your user managment rewiring, @jcushman

**Comment by jcushman** [comment]
Yep, there's now an error message if you try to make a registrar user (including yourself) into an org user.
