### ISSUE TITLE
[QUESTION] public link to perma folder?

### ISSUE THREAD

**Issue by arderyp** [harvard-lil/perma#1464]
Is it possible to link to (or generate a link for) one of my account's sub folders?  We are using your API for a public project, and we provide lots of direct links off to our archives resources, but I was wondering if there is a way to provide a link to the parent folder that holds all of the project's subfolders/links.

**Comment by jcushman** [comment]
Hi, @arderyp! This doesn't exist currently. We've had a few requests for ways to link to sets of links, but linking to the folder is an interesting solution that hasn't come up before. We'll chat about it with the team and see if it feels workable.

**Comment by arderyp** [comment]
Awesome, thanks!

**Comment by abziegler** [comment]
Received another request for this. Use case is book author who doesn't want to add Perma Links to all web citations, but would like to archive those citations. Preference would be to put a note in the book appendix that points to a single URL that provides access to archives for all the web citations in the book.

**Comment by arderyp** [comment]
Nice.  Could be useful.

**Comment by bjohnson747** [comment]
Another request by a user for a feature like this: "As the number of references we can put in publications are limited, I was wondering, is it possible for me to add a link to one of my folders of cited pages, instead of having to add all the separate links?" +1

**Comment by arderyp** [comment]
Any word on this? It would be awesome to have links to folders and subfolders, which would allow users to expose organizational sets of links as they see fit.
