### ISSUE TITLE
Org users should have a way of seeing who their registrars are

### ISSUE THREAD

**Issue by jcushman** [harvard-lil/perma#1469]

**Comment by rebeccacremona** [comment]
See https://hlslil.slack.com/files/rcremona/F2BA348C8/help-org-users-contact-their-registrar.zip for mockups of some proposed tweaks.

**Comment by rebeccacremona** [comment]
Phase one: https://github.com/harvard-lil/perma/pull/1698/

**Comment by rebeccacremona** [comment]
A little prep for sending certain emails to registrars: https://github.com/harvard-lil/perma/pull/1706; https://github.com/harvard-lil/perma/pull/1707

**Comment by rebeccacremona** [comment]
With the above, plus #1831, let's consider this closed. Feel free to reopen if you disagree!
