### ISSUE TITLE
Let a user indicate that the image capture is preferred to the web capture

### ISSUE THREAD

**Issue by jcushman** [harvard-lil/perma#1470]

**Comment by jcushman** [comment]
Next steps: sketch a couple of options. Radio button in tray, or offer to link owner to change the default when they view a non-default view, or ... ?

**Comment by kilbergr** [comment]
When you visit https://perma.cc/F857-95FJ, Perma serves up the high-fidelity playback. You can direct people to a screenshot by adding the query string https://perma.cc/F857-95FJ?type=image or advising them to click.
People have asked for the ability to check a box or something that would cause Perma to redirect to the screenshot view (or similar) if people visited https://perma.cc/F857-95FJ.
Would involve adding a field to track, adding redirect behavior, and arranging things such that a person could still click to get to the "standard" view, for such links.
(special cases: when there is no screenshot; when there is only a screenshot (are there any like this?); when a user replaces our capture with a PDF upload after the fact; when a capture is in process; when a capture failed; when other redirect logic is in play, like a replacement link.....)

**Comment by kilbergr** [comment]
Three options (note the blue and typeface _would_ match):
<img width="1728" alt="Screen Shot 2022-09-29 at 1 23 02 PM" src="https://user-images.githubusercontent.com/7401870/193103464-22e37120-23e3-45dd-9e3c-81ca7179686c.png">
<img width="1522" alt="Opt2" src="https://user-images.githubusercontent.com/7401870/193104111-99ebcae9-f4e5-40a0-8bd8-67d05e864d09.png">
<img width="1522" alt="Opt3" src="https://user-images.githubusercontent.com/7401870/193107304-0049d8b6-1239-48d6-b976-1993dbdddd6b.png">
I'm not sure what you'd like done with the View mode selection on the header--should that disappear in this view?
AKA:
<img width="1522" alt="Opt3_noheader" src="https://user-images.githubusercontent.com/7401870/193109073-2c1978e5-e7fb-4821-999f-60c76224d13d.png">

**Comment by matteocargnelutti** [comment]
The radio toggle makes a lot of sense to me. It helps indirectly explain what this feature is about.

**Comment by kilbergr** [comment]
Tagging @rebeccacremona and @clare-stanton for review, but have also posted in Slack.

**Comment by kilbergr** [comment]
Takeaway from the group is: go with the radio buttons and disappear the View mode indicator in the header. ALSO, this drop down tray should be redesigned as a modal. That work may be started in the course of this ticket but hopefully will be done after this ticket instead.

**Comment by matteocargnelutti** [comment]
> ALSO, this drop down tray should be redesigned as a modal.

FWIW: This could be a great use case [for the "new" `<dialog>` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog) 😄

**Comment by kilbergr** [comment]
<img width="1162" alt="Screen Shot 2022-10-06 at 4 43 14 PM" src="https://user-images.githubusercontent.com/7401870/194414930-9a333854-8bc6-4e7e-a935-95d168de2932.png">
<img width="675" alt="Screen Shot 2022-10-06 at 4 43 20 PM" src="https://user-images.githubusercontent.com/7401870/194414932-f0b487a3-0048-4aee-88c0-a48f90270d50.png">
Well, this part works :)

**Comment by kilbergr** [comment]
So just to be clear @rebeccacremona or @jcushman --you want users to be able to set a default to view screenshot or standard, but you also want them to be able to change the view while maintaining that default, is that right?

**Comment by rebeccacremona** [comment]
@kilbergr Yes. 

If an author prefers the screenshot view because it came out great, but the high-fidelity playback is suboptimal, we want the author to be able to say, "When somebody goes to http://perma.cc/AAAA-AAAA", please send them to the screenshot view by default. If the visitor wants to go see the high-fidelity playback to see it, and then click to the screenshot again, they can click back and forth between those views just like normal; I just don't want to them to have to click to the screenshot when visiting the querystring-less URL."

**Comment by kilbergr** [comment]
So the screenshot view default matters if it's their first time viewing the page, but otherwise the capture role is what determines what they'll see.

**Comment by rebeccacremona** [comment]
- https://perma.cc/AAAA-AAAA w/`prefers_screenshot_view=False` -> playback view.
- https://perma.cc/AAAA-AAAA w/`prefers_screenshot_view=True` -> screenshot view.
- https://perma.cc/AAAA-AAAA?type=image always -> screenshot view.
- https://perma.cc/AAAA-AAAA?something=like_that -> playback view.

**Comment by kilbergr** [comment]
<img width="353" alt="Screen Shot 2022-10-12 at 5 48 53 PM" src="https://user-images.githubusercontent.com/7401870/195454464-bf99c4ed-1810-4820-8e8b-2798707d49b4.png">
TY to @lizadaly for styling help. This now stores in the db.

**Comment by kilbergr** [comment]
<img width="967" alt="Screen Shot 2022-10-12 at 5 49 27 PM" src="https://user-images.githubusercontent.com/7401870/195454558-f6dbbcdd-1afc-4ff8-b176-96e6a37de868.png">
