### ISSUE TITLE
Upload failing on PDF w/o explanation

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#1480]
Org user downloaded item as PDF, then tried to upload but got fail
Source URL: http://www.bgbl.de/xaver/bgbl/start.xav?startbk=Bundesanzeiger_BGBl&jumpTo=bgbl109s2274.pdf#__bgbl__%2F%2F*%5B%40attr_id%3D%27bgbl109s2274.pdf%27%5D__1461677341323

![upload fail](https://cloud.githubusercontent.com/assets/2140548/14819880/1978839c-0b92-11e6-806f-c8ccd8dd8c72.png)

**Comment by jcushman** [comment]
Should be fixed on prod.
