### ISSUE TITLE
Existing affiliated users can't be upgraded to registrar user

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#1499]
User report. I confirmed. Error says: "Error! [user-email] is already affiliated and cannot be added to your registrar."

Assigning to @jcushman b/c related to user management

**Comment by phillipsm** [comment]
did this get patched up in your user management rewiring, @jcushman

**Comment by jcushman** [comment]
Not quite, but the error message is more explicit: "test_org_user@example.com is an organization member and must be removed from all organizations before adding as a registrar member."

We could have it auto-upgrade, but only if the org belongs to the registrar. Maybe need to talk about how we want this to work?

**Comment by abziegler** [comment]
Sorry just saw this note, after I filed #1505 - ok with me to talk this through a little

**Comment by jcushman** [comment]
Sent a pull request that cleans up how we handle upgrading an existing org user to a registrar.

If the *current* user is an admin, we tell you all the current orgs the user belongs to and warn that those affiliations will be replaced by making them a registrar.

If the current user is a registrar, and all orgs the target user belongs to are part of that registrar, we just let you proceed -- the target user will still be able to access everything once promoted to registrar.

If the current user is a registrar, and the target user belongs to orgs managed by a different registrar, then we show an error message saying that the user will have to leave those other orgs before they can join your registrar.
