### ISSUE TITLE
Target page detects as bot

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#1503]
Haven't seen this before: https://perma.cc/JNM3-5CCM

Target URL: https://www.crunchbase.com/

**Comment by jcushman** [comment]
Seems likely that switching to Firefox or offering Webrecorder capture will fix.

**Comment by rebeccacremona** [comment]
Today, they are letting us in, even without moving from phantom js.
https://perma-stage.org/H2BJ-EZ6X

**Comment by rebeccacremona** [comment]
Two years later, this still seems fine :-)
