### ISSUE TITLE
Forcing manual org-removal of org-user to be elevated to registrar-user status

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#1505]
Consider whether there's a less manual way to do this...

![add_org_user_as_registrar_user](https://cloud.githubusercontent.com/assets/2140548/15336187/4ea3a2ec-1c43-11e6-9cc0-acebb44e9813.png)

**Comment by abziegler** [comment]
More like this, which we do for upgrade to admin status?

![registry_user](https://cloud.githubusercontent.com/assets/2140548/15336337/2265f33c-1c44-11e6-9495-24df0f9c4f38.png)

**Comment by jcushman** [comment]
Closing as dupe of #1499
