### ISSUE TITLE
Update link won't allow upload, then re-upload

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#1556]
On perma-stage, logged in as test_org_user:

1. archived example.com
2. clicked 'edit record'
3. uploaded png
4. clicked 'edit record' again
5. tried to upload different png

Did not swap out new png. Kept the first one instead.

**Comment by jcushman** [comment]
The issue here is that Cloudflare is caching the old `<img src="upload.png">` for an hour, so you can't see the new one. Seems like a good solution is to embed uploads as `<img src="upload.png?hash=foo">`, so the cached URL changes when the file changes.
