### ISSUE TITLE
Errors on attempt to make link private and attempt to access private link w/o authority

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#1558]
perma-stage, as test_org_user

Tried to make old public link private, and got this:

![perma-test-4](https://cloud.githubusercontent.com/assets/2140548/15711580/9e985258-27dc-11e6-955e-02ac87da757d.png)

Also, incognito browser, attempted to access link made public (https://perma-stage.org/A8AP-5XTJ):

![perma-test-5](https://cloud.githubusercontent.com/assets/2140548/15711628/d27683e2-27dc-11e6-9751-9207544af9eb.png)

Also, attempt to access warc of private record:

![perma-test-6](https://cloud.githubusercontent.com/assets/2140548/15711744/60ce9df0-27dd-11e6-9b0f-9f185b6bdb06.png)

**Comment by anastasia** [comment]
Unable to replicate. @jcushman ?

**Comment by jcushman** [comment]
We think these are just resource issues with the staging server -- closing.
