### ISSUE TITLE
Page title still visible when viewing a private record

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/perma#1559]
Private record's page title still showing @ top of browser
![screen shot 2016-06-01 at 11 42 09 am](https://cloud.githubusercontent.com/assets/12850389/15715831/07fb9ac8-27ee-11e6-8f0c-0315505c0ab9.png)

**Comment by jcushman** [comment]
This is working as intended. You can also see the title and original URL if you click "show record details." This is so Perma.cc doesn't inadvertently contribute to link rot by causing a published link to become a total dead end for readers if it is later marked private.

If a user requires complete privacy, they should not publish the link (for example, the 97KW-SL4Z in your screenshot).
