### ISSUE TITLE
Give user option to log-in @ private record viewing screen?

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/perma#1561]
Thought - if a user visits a private link they own and expects to be able to view it, but can't b/c they're not logged in, should we have a link somewhere on the screen they can log-in through?
https://perma-stage.org/97KW-SL4Z

**Comment by jcushman** [comment]
We're wary of adding stuff to the crowded single-link page when most users who visit logged out will be readers rather than users. Maybe we hold off on this unless we hear from users that it's something they could use?
