### ISSUE TITLE
add pep8 linter to Travis CI

### ISSUE THREAD

**Issue by bensteinberg** [harvard-lil/perma#1568]
Probably the linter should complain for a small subset of problems, though it would be good to move toward [PEP8](https://www.python.org/dev/peps/pep-0008/) compliance generally. The specific thing this would have caught is a tabs-instead-of-spaces problem in a migration; see 7303f56.
An invocation that would have found this problem is
```
pip install pep8
find . -name *.py | xargs pep8 --first --select=E101
```
A list of pep8 error codes is at http://pep8.readthedocs.io/en/latest/intro.html#error-codes.

**Comment by bensteinberg** [comment]
It looks like this is not a feature in Travis proper: https://github.com/travis-ci/travis-ci/issues/451

**Comment by jcushman** [comment]
People seem to run flake8 in before_script. E.g.:

http://eldarion.com/blog/2014/06/03/how-we-work-continuous-integration/

We could wrap it in a fab command to make it easier to tweak the inputs.
