### ISSUE TITLE
Log in screen accessible to logged_in user

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#1583]
Perma-stage, logged in as test_user:

1. If i visit someone else's Perma link, i get the logged_out record view
2. I can access the log in screen, which shouldn't happen
![test2](https://cloud.githubusercontent.com/assets/2140548/15895165/d6ac464c-2d57-11e6-804c-0035c8b878a6.png)
![test3](https://cloud.githubusercontent.com/assets/2140548/15895166/d6acef3e-2d57-11e6-9451-4457fe025757.png)

**Comment by bjohnson747** [comment]
I haven't been able to re-create this (fixed?)

**Comment by rebeccacremona** [comment]
You just fixed this, right @jcushman? Ready to close?

**Comment by jcushman** [comment]
I fixed "2. I can access the log in screen, which shouldn't happen"

@abziegler, I think a few of us haven't been able to reproduce "1. If i visit someone else's Perma link, i get the logged_out record view". Let me know if you're able to get that to happen again.
