### ISSUE TITLE
Top of playback iframe hidden by perma header

### ISSUE THREAD

**Issue by jcushman** [harvard-lil/perma#1585]
Looks like the header redesign is causing the iframe to show behind the header:

<img width="884" alt="screen shot 2016-06-08 at 4 23 09 pm" src="https://cloud.githubusercontent.com/assets/376272/15909817/0cfe20d8-2d96-11e6-932f-63f13445cec6.png">

https://perma-stage.org/XA6A-QHV3

**Comment by anastasia** [comment]
Hm..... The redesign took place in the "#collapse-detail" div, which is display:none -ed when details are not shown, so that shouldn't have affected the iframe positioning.

**Comment by bjohnson747** [comment]
+1

**Comment by anastasia** [comment]
OH, I'm able to recreate it. iFrame shows up differently on editable vs not-editable (out of org) archives
