### ISSUE TITLE
Picking which fields to publically expose through "Show record details" panel

### ISSUE THREAD

**Issue by arderyp** [harvard-lil/perma#1592]
When I'm logged in and visit one of my perma resource, I can click "Show record details", which will show me all of the metadata that I've provided for the resource.  When I visit the same resource without being logged in, the "Show record details" panel only exposes the "Source page url" and "Title" fields.  

It's certainly not a high priority issue, but it might be nice to allow the perma user to pick which fields to expose in this panel.  For example, we have helpful information in the notes field that we'd like to expose publicly.  We'd also even like to expose the folder name (or better yet: #1464)

**Comment by jcushman** [comment]
Closing in favor of #978.
