### ISSUE TITLE
Can view login pages while already logged in

### ISSUE THREAD

**Issue by anastasia** [harvard-lil/perma#1593]
Or maybe I'm missing something?

- recreate by logging in with our recently deactivated accounts (I used test_registry_member)
<img width="1280" alt="screen shot 2016-06-10 at 11 36 09 am" src="https://cloud.githubusercontent.com/assets/1494102/15969849/ce3a2430-2eff-11e6-96a1-d80658b73005.png">

<img width="571" alt="screen shot 2016-06-10 at 11 36 18 am" src="https://cloud.githubusercontent.com/assets/1494102/15969828/aaba4328-2eff-11e6-9d80-d1b8631f5cdb.png">

<img width="1280" alt="screen shot 2016-06-10 at 11 36 24 am" src="https://cloud.githubusercontent.com/assets/1494102/15969856/dae2b21a-2eff-11e6-8718-4f8f25262116.png">

**Comment by jcushman** [comment]
Weird -- I'll take a look at this.

**Comment by anastasia** [comment]
Maybe a migration issue?

**Comment by jcushman** [comment]
I'm pretty sure what happened here is that you were able to visit the login form while already logged in, which leads to confusing results when you then try to log in as someone else.

The Django project has been arguing about what to do in this situation for *[seven years](https://code.djangoproject.com/ticket/12233)*, and the fix they adopted didn't land until version 1.10. We're on 1.9. Yay!
