### ISSUE TITLE
Clean up social media presence 

### ISSUE THREAD

**Issue by anastasia** [harvard-lil/perma#1604]
- [x] twitter account should be findable on perma.cc
- [ ] slack channel should be findable for logged in users on perma.cc
- [x] twitter account should have a new header
- [x] think of plan for tweets/retweets/crossposts
- [x] all accounts should be present on blog page
- [x] add perma.cc accounts to HarvardLIL twitter bio

**Comment by bjohnson747** [comment]
1) Can we have a footer item named "Twitter" that links to https://twitter.com/permacc added? Alternatively, change the text under _Contact_ to include a link to the Perma Twitter.

2) Can't share a Slack channel via URL (at least, [through Slack itself](https://sameroom.io/blog/creating-a-portal-with-slack/))- there's also invite limits; I think it's worth reconsidering whether it's worth having the slack channel be publicly posted.

3) plan is to scale up Perma blog posts to 1/week, including crosspost to perma twitter.

4) Blog linked to from Perma Twitter, Twitter linked to from Perma Blog.

5) Perma twitter added to HarvardLIL twitter

**Comment by bjohnson747** [comment]
@anastasia will add the twitter bird to the footer

**Comment by anastasia** [comment]
Added twitter text instead of bird

**Comment by jcushman** [comment]
Last remaining checkbox is covered by #1670. Closing this ...
