### ISSUE TITLE
Edited title details don't change in display

### ISSUE THREAD

**Issue by TimMcAllister-HLS** [harvard-lil/perma#1605]
I uploaded a PDF of a page.  Edited the page title, but when I look at the perma link in incognito mode, the new page title does not show up - I see the old page title. 

Happened on perma-stage and perma.cc
https://perma-stage.org/M3MT-GU7S
https://perma.cc/FH89-C6HD

**Comment by jcushman** [comment]
This is likely an intended result of our cache. We only regenerate pages for logged-out users once per hour. So if you change a title, logged out users may not see the new version for up to an hour.
