### ISSUE TITLE
WARC archive of page not coming up

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/perma#1623]
User Perma'd https://www.aclu.org/blog/solitary-confinement-arizona-cruel-and-unusual -- https://perma.cc/J5SD-HBEH  -- the WARC shows up blank, but the screenshot view works. 
I was able to reproduce this issue from this page on my own account.

**Comment by jcushman** [comment]
This is working on stage but not on prod. I'm not sure what if anything has changed, but suggest taking another look after we deploy. Kicking out to next milestone.

**Comment by bensteinberg** [comment]
I believe this was fixed by increasing proxy_buffer_size in nginx config.
