### ISSUE TITLE
return 404 from https://api.perma.cc/robots.txt

### ISSUE THREAD

**Issue by bensteinberg** [harvard-lil/perma#1626]
At the moment, hits on https://api.perma.cc/robots.txt produce an internal server error:

```
Internal Server Error: /robots.txt

ValueError at /robots.txt
HistoryRequestMiddleware.process_response didn't return an HttpResponse object. It returned None instead.

Request Method: GET
Request URL: https://api.perma.cc/robots.txt
```

If only to reduce noise in the admins' email, this should probably return a 404.

**Comment by bensteinberg** [comment]
Same for https://api.perma.cc/favicon.ico?

**Comment by jcushman** [comment]
I'm thinking return a deny-all for api.perma.cc/robots.txt, the same way we do for perma-archives.org -- there's nothing useful at api.perma.cc to index. 404 for favicon seems good. Do you want to jump in and do this in the nginx conf file?

**Comment by bensteinberg** [comment]
Sure. I think /etc/nginx/sites-available/perma is unmanaged? I'll add 

    location /robots.txt {return 200 "User-agent: *\nDisallow: /\n";}

to the perma.cc/api.perma.cc server stanza, to match the line in the perma-archives.org stanza. I think it'll be safe to add 

    location /favicon.ico {return 404;}

to the perma.cc/api.perma.cc server stanza, since the real favicon is served from /static/img. Sound okay?

**Comment by jcushman** [comment]
It's unmanaged, yes. The tricky bit is we want this just for api.perma.cc -- regular perma.cc has a favicon and correctly returns 404 for robots.txt.

**Comment by bensteinberg** [comment]
Split api.perma.cc into its own server section.
