### ISSUE TITLE
Can move organization's shared folder

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#1634]
I'm not able to move an org entirely into MyLinks (we throw an error message that says "You can't move an organization's shared folder"), but I can move an org's folders into MyLinks. Seems inconsistent.

**Comment by abziegler** [comment]
Also, if I'm a member of 2 orgs, I have the ability to move all orgA's folders into orgB.

**Comment by jcushman** [comment]
We think this is working as intended -- see wiki: https://github.com/harvard-lil/perma/wiki/Design-Decisions#users-can-drag-links-between-org-folders-and-their-my-links-folder

If this doesn't feel right, let's revisit at a Perma meeting.
