### ISSUE TITLE
There should be an API way to download an archive

### ISSUE THREAD

**Issue by anastasia** [harvard-lil/perma#1642]
also bulk downloads would be nice

**Comment by jcushman** [comment]
API doesn't currently include the URL to download the warc. Add something like "warc_download_url": "https://perma.cc/GUID-GUID?type=warc_download"

**Comment by rebeccacremona** [comment]
That url works with wget or curl for public warcs, but we should probably also have a mechanism for link owners and admins to download private warcs.

Hmmm.
