### ISSUE TITLE
Check on upstart script configuration in new Vagrantfile

### ISSUE THREAD

**Issue by anastasia** [harvard-lil/perma#1649]
I can't sudo stop or start celery anymore

**Comment by bensteinberg** [comment]
The reason you can't stop or start celery is that the new vagrant box uses systemd, not upstart. Try 

    sudo systemctl stop celery
    sudo systemctl start celery

(You can do the same thing with `celerybeat` and `celery_background`.)

Sorry -- I should have either boosted the documentation level or been more clear about that box being a draft. I'll close this issue and make a new one for copying the box to the perma user at atlas, and updating the README.
