### ISSUE TITLE
Redirect secondary links to closest available capture

### ISSUE THREAD

**Issue by anastasia** [harvard-lil/perma#1665]
Instead of secondary links on Perma archives appearing "not found" (https://perma.cc/E2K6-RB3B click on any link) we should show the closest Perma capture available.
We should also query mementoweb (http://timetravel.mementoweb.org/) for captures and show available options to the user.

This feature would need to make it clear that the user is traveling in time.

**Comment by jcushman** [comment]
It would be cool to have two sections here, one for a close-in-time Perma link (if there is one) and one for a general mementoweb search. This way users can create a batch of links and readers will get linked between them.

**Comment by anastasia** [comment]
Currently it's impossible to tell whether a link 404s because a user has clicked on a secondary link or because a resource has failed to load (when loading the original link). Querying perma or memento for every 404 (user initiated and not) seems like a huge burden for either service. 
A small enhancement is adding a pre-filled mementoweb request URL (http://timetravel.mementoweb.org/api/json/[timestamp]/[url]) but I'm not exactly sure how much that will help vs confuse. Becky suggests that we could add a button that saying "click here to search for this link!" (one for memento or perma). Thoughts?

**Comment by anastasia** [comment]
Directing users to mementoweb, let's close this issue

**Comment by rebeccacremona** [comment]
Closing per Feb 6 comment.
