### ISSUE TITLE
investigate deleted and pending capture jobs on stats page

### ISSUE THREAD

**Issue by bensteinberg** [harvard-lil/perma#1668]

**Comment by rebeccacremona** [comment]
We've made a lot of progress identifying the cause for the "pending" jobs. 
1) https://github.com/harvard-lil/perma/commit/b0873c79ee7110ee22fd5c852d3be5c3bb1c7b81
2) adding soft celery timeouts, and raising HaltCaptureException when soft timeout is triggered
3) locating unqualified try/accept loops that caused the soft celery timeout to be swallowed. 

At this point, we should probably review all the pending capture jobs, and see if any of them have warcs that can be played back, and adjust accordingly.
