### ISSUE TITLE
Users should have a way to see that archives were unsuccessfully captured in their links list

### ISSUE THREAD

**Issue by anastasia** [harvard-lil/perma#1669]
currently users will see all captures in their links list, even if archives are "failed". There should be an indicator that some links have failed. For instance, we could have a toggle on off button for "show all captures" vs "show successful captures" or something. Or if captures were unsuccessful, they should have some sort of an indicator (like a different background color, or the word "Failed" next to the title).

**Comment by jcushman** [comment]
Becky took a pass at this that turned out to be too complicated. Next pass will maybe start with just showing the status of each link in the list?

**Comment by bensteinberg** [comment]
34f587e111699e7d2a96537ba7e37b1bef1952b2
