### ISSUE TITLE
oauth perma/slack

### ISSUE THREAD

**Issue by phillipsm** [harvard-lil/perma#1671]
if registrars are logged in, they should be able to chat through slack with the perma team. we don't want to make them auth again to slack. wire perma and slack together using oauth.

There's a UX/UI piece here too - where does the "Chat with the Perma team" button go? Maybe in the logged in drop down? Maybe it's a link in the footer? Maybe it goes in every error template?

**Comment by bensteinberg** [comment]
duplicates https://github.com/harvard-lil/perma/issues/1670

**Comment by phillipsm** [comment]
ack. thanks!
