### ISSUE TITLE
Address field(s) and geolocation in registrar records

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/perma#1676]
Add an address field that will permit automated lookup of registrar latitude and longitude, which is required for the partners map.

We can use Google Maps API to map addresses (US or international) to latitude and longitude. https://developers.google.com/maps/documentation/geocoding/start. We shouldn't have any trouble with the rate limit.

Are we okay with a single field, rather than split into address1, city, state, etc.? 

Advantage of single field: 
-  no need to worry about how to handle international addresses. 

Disadvantages: 
-  harder to enforce consistent formatting (e.g. states spelled out or abbreviated, always specify country explicitly, etc.)
-  we'd have to parse it if we wanted to do anything with the address components later, like extract country or us state

**Comment by rebeccacremona** [comment]
Perspective of the day: we don't think we like this on the sign up page. We might be up for asking registrars later, by including this field in the "edit registrar" form, and inviting registrars to update on their first login. But, we're not sure we want to open that can of worms: people will wonder why we want their address, etc. We enjoy the functionality of the geocoding button inside the admin interface, but I think consensus was tending in the direction that it's not worth a lot of admin time right now to go add a lot of addresses/coordinates for registrars, especially because the team probably wants to rethink how partners are displayed. (Might have misheard that last bit.)

So, we might go ahead and release some of this under a feature flag, if that's feasible, in case we want some version of it in the future.

**Comment by jcushman** [comment]
Update: let's merge Becky's code and get some partners geocoded ...

**Comment by rebeccacremona** [comment]
Done here https://github.com/harvard-lil/perma/commit/34df6cd4e59a545db903d693f934a903c5e70cfc
