### ISSUE TITLE
Partners map should be global now...

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/perma#1677]
...since we have international partners.

Should we replace the existing map entirely, or offer both somehow? If we want to offer both, then this needs some design attention.

**Comment by abziegler** [comment]
World map by itself seems sufficient to me. The map is more to connote breadth of community. One possibility: https://www.amcharts.com/svg-maps/?map=world

**Comment by rebeccacremona** [comment]
I love amcharts! https://osc.hul.harvard.edu/dash/mydash/geomap/1/last30/alldash/

**Comment by jcushman** [comment]
Update: let's do this! We like the idea of having a big mostly-empty world map to encourage more global partners.

(This could be low-hanging fruit if we just swap in global map data for the US map data.)

**Comment by jcushman** [comment]
Done.
