### ISSUE TITLE
IE support

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/perma#1681]
The FAQ says that we support IE 8+
```
Which web browsers does Perma.cc support?
Perma.cc works on Chrome, Firefox, Safari and IE8+.
```
I don't know if we hold ourselves to that, but, since Microsoft has dropped support for IE 8, 9, and 10, maybe we should as well. And do we test with Microsoft Edge? Would that free us up in any way? (some possibilities: faster cross-browser testing, slicker/cleaner CSS, lighter weight version of JQuery? hmmm. other things?)

**Comment by jcushman** [comment]
Last time we discussed this, we decided to bump support to IE10+ based on usage logs. Looks like we missed the FAQ -- could you update it?

**Comment by rebeccacremona** [comment]
Sure.

**Comment by rebeccacremona** [comment]
https://github.com/harvard-lil/perma/pull/1700
