### ISSUE TITLE
Should coveralls exclude templates directory, etc.?

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/perma#1693]
https://github.com/coagulant/coveralls-python#tips-for-coveragerc-config

**Comment by jcushman** [comment]
The exclusion list is currently hacked into `fab test` -- feel free to move to .coveragerc if that feels cleaner:

https://github.com/harvard-lil/perma/blob/develop/perma_web/fabfile/dev.py#L33

You can see everything that's contributing to coverage here -- looks like templates are not currently counted for or against:

https://coveralls.io/github/harvard-lil/perma

(Sorting by lines missed is a good way to find targets for improvement.)

It sounds like templates can be included in test coverage if we add a package for that, and maybe they actually should be?

https://pypi.python.org/pypi/django_coverage_plugin

**Comment by rebeccacremona** [comment]
Interesting. There's some weirdness, I think, in the percent changes it's reporting. It's definitely reported different coverage percents when I've made commits that exclusively touch template files. I'll try to be more observant and see if I can figure out why.
