### ISSUE TITLE
airbrake js 404 locally (running via vagrant)

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/perma#1699]
I often see lines like this in my local logs:
```
[21/Sep/2016 19:45:43] "GET /static/vendors/airbrakejs/client.min.js.map HTTP/1.1" 404 1721
```
I haven't noticed any problems in production, though there the js is bundled. Are we missing a file? If so, is it causing any problems?

**Comment by anastasia** [comment]
Source maps allow for better debugging of minified js files, they don't actually make or break the code on their own. We can either include the .map file or you can disable source mapping in your browser settings. If you use Chrome, here's how you'd do it: http://stackoverflow.com/a/18425964/2247227. Thoughts?

**Comment by rebeccacremona** [comment]
Oh! I didn't even register that the file extension was special. Thanks for the info!

I know there's been some conversation about moving to a different asset pipeline incorprating Bower etc. I have to imagine some part of that project would be producing two version of our assets, one for local use and one for prod, and that source maps would be included in the dev version but not the prod. So maybe the thing to do is for me to ignore the 404 for now, and if it ever becomes unbearable, take that as a good excuse to try overhauling the asset pipeline?
