### ISSUE TITLE
problem archiving airbnb page

### ISSUE THREAD

**Issue by phillipsm** [harvard-lil/perma#1705]
https://www.airbnb.com/s/New-York--NY--United-States?guests=2&checkin=10%2F21%2F2016&checkout=10%2F23%2F2016&ss_id=6k1socfw&source=bb bombs out. why?

**Comment by bensteinberg** [comment]
I just got it to work -- try again and let me know. I've just been changing the queueing systems, though that should not have caused your capture to fail twice.

**Comment by phillipsm** [comment]
weird. I'm trying to capture the 500 i get, but perma just stops for me
![screen shot 2016-09-26 at 5 24 40 pm](https://cloud.githubusercontent.com/assets/196089/18852401/3ad3695e-840e-11e6-8dca-4f88b184f095.png)
![00j0j_hvzd6oxra1r_1200x900](https://cloud.githubusercontent.com/assets/196089/18852411/4622273c-840e-11e6-9685-876319d1ef47.jpg)

**Comment by phillipsm** [comment]
one of my failed captures, https://perma.cc/B8MS-NF3T

**Comment by rebeccacremona** [comment]
Too late to reproduce :-(
