### ISSUE TITLE
Fix invalid html

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/perma#1710]
Example: on the signup pages, there are cards for each kind of sign up (individual, libraries, courts, etc.). The cards are links for all the pages except the one you are on...... where the anchor tag is simply switched to an <a> tag. With an href attribute! Etc. Fix in a way that doesn't break site styling.

There might be other instances of things like this too, haven't looked.
https://validator.w3.org/

**Comment by rebeccacremona** [comment]
Another example: the link list on the create page uses divs with "link_id" attributes. We should put that in data-link_id regular html id attributes don't work for some reason.

**Comment by rebeccacremona** [comment]
Another example: dl lists in single-link.html lack dd elements, and have input elements as children of dl.

**Comment by rebeccacremona** [comment]
ul as child of ul in terms_of_service.html

**Comment by bensteinberg** [comment]
closed with e036bb7
