### ISSUE TITLE
Forbes articles: only ad/splash page is captured, not article

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/perma#1711]
Forbes article links don't capture article; only the splash page is captured in both WARC and screenshot.

ex: http://www.forbes.com/sites/bethhoffman/2013/12/13/new-fda-rules-will-not-reduce-antibiotic-use-on-farm

in Perma: https://perma.cc/L7UY-EY8H

**Comment by bjohnson747** [comment]
Received another user email re: this issue

**Comment by bjohnson747** [comment]
It seems captures now say "capture failed", instead of the poor splash page capture that was happening before. (ex. http://www.forbes.com/sites/scottmendelson/2015/04/17/star-wars-is-hollywoods-biggest-original-franchise/#1328901150cd)

**Comment by bensteinberg** [comment]
closed in 65193e1
