### ISSUE TITLE
Captures failing from the www.hanford.gov/ site

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/perma#1761]
Attempted to create Perma link for http://www.hanford.gov/pageaction.cfm/calendar?IndEventId=6727 and hanford.gov front page.

Both returned a "capture failed" - https://perma.cc/5FTV-SDX6 ,  https://perma.cc/3TAJ-6RQ6

(the spinning 'capturing' symbol also continue to spin for several minutes on both atttempts and has yet to stop - I had to open a new window to try to open these Perma links that were in my My Links.)

**Comment by rebeccacremona** [comment]
This works now: https://perma-stage.org/55W9-TBWT
