### ISSUE TITLE
Potentially deletable code

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/perma#1765]
Making a list here of stuff that doesn't seem to be in use, that maybe we can remove (which will have the effect of boosting test coverage ;-):
- ~~the app at /monitor~~
- ~~in /perma_web/perma/tasks.py the function "retry_on_error"~~
- ~~in /perma_web/perma/utils.py: the function "get_png_size"~~
- ~~the truncatesmart templatetag~~
- ~~the file_exists templatetag~~
- ~~the count_archives templatetag~~
- ~~@ssl_optional decorator in middleware.py~~

**Comment by rebeccacremona** [comment]
- link_management.py[46:47], 
```
    if links_remaining < 0:
        links_remaining = 0
```
That should never be allowed to happen, especially in a world where we charge people for extra links. If we're concerned Perma can somehow let a user get into a state where links_remaining < 0, how about we replace this with an assert and/or a message to the error log, so that we can pinpoint how/when and fix it?

**Comment by rebeccacremona** [comment]
Per @jcushman: The whole folder_contents view seems to be an unmaintained fallback for non-JS browsers that click the folder tree: https://perma-stage.org/manage/links/folder/24?iframe=1
Possibly that whole thing should just be ripped out?

**Comment by jcushman** [comment]
Deletable file: `perma_web/static/css/_placeholders-global.scss`

Then commented-out line in `perma_web/static/css/_perma-imports.scss` importing that file can also be removed.

**Comment by rebeccacremona** [comment]
The JS in the FAQ page either needs to be updated to work in Webpack land, or removed entirely. I vote for removal: I don't believe it actually accomplishes anything desirable. Instead of data attributes, we should use regular hashes (tied to ids) and the standard focusfix.js to make sure they work.
