### ISSUE TITLE
Language change on Perma link page?

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/perma#1772]
I think the wording "looks wrong?" implies a decent chance there's an issue. It also odd to me that that's the text that leads in to the user viewing the Screenshot view --
 I know the WARC is the recommended archive to view, but is the WARC looking wrong the main reason we want people to consider accessing the Screenshot View?

**Comment by abziegler** [comment]
Text prompts user to review the warc playback (which is primary capture), and if something looks wrong, then to check screenshot.
