### ISSUE TITLE
Text repeats on front page

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/perma#1777]
The text "Websites change, go away, and get taken down. When linked citations lead to broken, blank, altered, or even malicious pages, that’s called link rot." appears twice on the front page. 

The 2nd appearance of it (under "Meet the Perma Link"), under 'Committed to Preservation', is part of a longer paragraph, but that subheader seems to imply different text than appears there

**Comment by abziegler** [comment]
No change required
