### ISSUE TITLE
Registrar claims to have two orgs but actually has one

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/perma#1799]
when searching registrars overall, this one claims it has two orgs - when clicking into it, it shows only one

![screen shot 2016-11-07 at 6 44 49 pm](https://cloud.githubusercontent.com/assets/12850389/20118500/add08582-a5d2-11e6-9de4-be162f120820.png)

Viewing the registrar itself:
![screen shot 2016-11-07 at 6 44 58 pm](https://cloud.githubusercontent.com/assets/12850389/20118499/adcf2dfe-a5d2-11e6-86d0-7a53fd98f86d.png)

**Comment by rebeccacremona** [comment]
Aha. Deleted orgs are included in that count.

**Comment by rebeccacremona** [comment]
Fixed in https://github.com/harvard-lil/perma/pull/2232
