### ISSUE TITLE
Should be no text decoration on :hover for capture-type on record view screen

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#1805]
text-decoration should be 'none' when you hover here..

![perma2](https://cloud.githubusercontent.com/assets/2140548/20282019/e8543ce6-aa80-11e6-8832-21dc39b7ed02.png)

**Comment by rebeccacremona** [comment]
https://github.com/harvard-lil/perma/commit/371e641285a349aec8e06b8ba2e7b8b32adaaa42

Note: because perma-stage.org has a lot more characters than perma.cc, there is some overlapping of elements at medium screen sizes on stage. That won't be an issue on production.
