### ISSUE TITLE
Orgs and subfolders of orgs shouldn't display link count

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#1806]
![perma3](https://cloud.githubusercontent.com/assets/2140548/20282325/466efc20-aa82-11e6-835d-a7a47dce6544.png)

**Comment by abziegler** [comment]
P.S. this seems to only affect newly created folders/sub-folders

**Comment by rebeccacremona** [comment]
https://github.com/harvard-lil/perma/commit/371e641285a349aec8e06b8ba2e7b8b32adaaa42
