### ISSUE TITLE
TOS language to be updated

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/perma#1809]
Below is the beginning of the Perma TOS -the italicized section needs to be updated, as "vesting" is no longer a Perma function.

Effective Date: September, 23, 2013
Use of the website http://perma.cc/ (the “Site”) and [...]
Perma.cc helps authors and journals create links for citations in legal and scholarly works. Through the Site, authors and journals can create links to and direct us to store archival copies of web pages cited in legal and scholarly works, for purposes of scholarship and research. _Some users can “vest” those links and archival copies, allowing longer-term preservation. Visitors to the Site can access those links and archival copies under certain conditions._ The services provided by us through or in connection with the Site are referred to collectively as the “Service.”

**Comment by jcushman** [comment]
Updating TOS requires notice to users and is probably not worth it for this.
