### ISSUE TITLE
thumbnail should be png of archive in slack/twitter...

### ISSUE THREAD

**Issue by phillipsm** [harvard-lil/perma#1839]
we're looking close with everything else in our slack share, just need a nice thumbnail. would be fantastic to have a thumnnail of the archive, but if that's tough, let's include our perma logo
![screen shot 2016-12-17 at 6 39 38 pm](https://cloud.githubusercontent.com/assets/196089/21290444/7246632c-c488-11e6-9b70-12ffbb8a4a8e.png)

**Comment by anastasia** [comment]
Perma logo should now be included
