### ISSUE TITLE
Think about robots.txt and archiving policy

### ISSUE THREAD

**Issue by phillipsm** [harvard-lil/perma#1842]
We should likely look past the robots.txt and similar directives when archiving a USG site ( since copyright cannot be claimed by the site author).

Should we make other changes to our robots.txt logic at the same time? Maybe we [follow IA's lead (we should figure out what that is exactly)](https://twitter.com/nthmost/status/809857038155059200) and look past robots.txt always?

**Comment by rebeccacremona** [comment]
Policy decision MADE. Oh yeah.
