### ISSUE TITLE
add capture duration to public API

### ISSUE THREAD

**Issue by bensteinberg** [harvard-lil/perma#1851]
Include the delta of capture_start_time and capture_end_time from the CaptureJob model in https://api.perma.cc/v1/public/archives/

**Comment by rebeccacremona** [comment]
Addressed by https://github.com/harvard-lil/perma/commit/2dfd03bfde551c2c68431682602aa79854dfc60c and https://github.com/harvard-lil/perma/commit/45b741c78d7285d2bc5d6488036a3192760f60c1 and https://status.perma.cc/monitor (and possibly others)
