### ISSUE TITLE
url string truncated on single archive page

### ISSUE THREAD

**Issue by phillipsm** [harvard-lil/perma#1852]
the source page URL value seems to be truncated. we should be seeing http://www.coalitionforpublicsafety.org/ and not http://www.coalitionforpu for 5DCV-75Y7

<img width="1294" alt="screen shot 2017-01-10 at 4 13 12 pm" src="https://cloud.githubusercontent.com/assets/196089/21825071/3d192376-d750-11e6-9927-464f8ef176e7.png">

(likely at the template level?)

**Comment by phillipsm** [comment]
oh. just noticed this in another archive. (must not being a char limit, but a css property. the char is cut down the middle. 
<img width="192" alt="screen shot 2017-01-10 at 4 49 22 pm" src="https://cloud.githubusercontent.com/assets/196089/21826415/5f5e4b32-d755-11e6-9abc-bb2ee92ea0c6.png">

**Comment by bensteinberg** [comment]
closed in eb8d6e0
