### ISSUE TITLE
mementos not showing at timetravel.memento.org for 2016

### ISSUE THREAD

**Issue by phillipsm** [harvard-lil/perma#1854]
we should get results back from perma from 2016, right?

 http://timetravel.mementoweb.org/list/20161218034043/http://example.com

**Comment by bensteinberg** [comment]
We're in http://labs.mementoweb.org/aggregator_config/archivelist.xml FWIW

The icon URI should change.

**Comment by rebeccacremona** [comment]
![image](https://user-images.githubusercontent.com/11020492/76015420-2fc43480-5ee9-11ea-8723-50212135eeae.png)
