### ISSUE TITLE
capture for nleomf.org not working

### ISSUE THREAD

**Issue by phillipsm** [harvard-lil/perma#1855]
#http://www.nleomf.org/facts/officer-fatalities-data/causes.html produces an image capture but [no warc capture](https://perma.cc/4DTR-4FUL)

<img width="1294" alt="screen shot 2017-01-10 at 4 36 13 pm" src="https://cloud.githubusercontent.com/assets/196089/21825782/184aa490-d753-11e6-9810-47695ef8d54d.png">

**Comment by rebeccacremona** [comment]
Closing in favor of #1878

**Comment by rebeccacremona** [comment]
Also, now plays back beautifully!
