### ISSUE TITLE
searching Internet Archive for broken perma link not working

### ISSUE THREAD

**Issue by anastasia** [harvard-lil/perma#1857]
the link seems to have a bunch of referrer information that IA doesn't know how to deal with.
<img width="1280" alt="screen shot 2017-01-10 at 4 58 34 pm" src="https://cloud.githubusercontent.com/assets/1494102/21826613/3700d460-d756-11e6-8208-a40075d505e9.png">

We should maybe also change it to using timetravel's simple API:
http://timetravel.mementoweb.org/api/json/2016/http://www.nleomf.org/facts/officer-fatalities-data/causes.html

**Comment by rebeccacremona** [comment]
Addressed in https://github.com/harvard-lil/perma/pull/2235
