### ISSUE TITLE
return 400 instead of throwing an error when someone uses a string instead of an int for a folder ID in the API

### ISSUE THREAD

**Issue by bensteinberg** [harvard-lil/perma#1864]
First, return 400 instead of throwing an error.

Second, do this more generally for ill-formed API calls.

Third, improve the docs.

**Comment by rebeccacremona** [comment]
AFAIK the only time this happens is during a capture request:
`curl -H 'Content-Type: application/json' -X POST -d '{"url": "http://example.com", "title": "This is an example site", "folder": "hi-there"}' http://api.perma.test:8000/v1/archives/?api_key=24e84d01b85574ee3ad5ce753a767488eed3c9d4`

I think everywhere else, folder is provided in the URL, so validation is handled by the route regex.
```
curl http://api.perma.test:8000/folders/hi-there -> 404
curl http://api.perma.test:8000/folders/hi-there/archives -> 404
```

**Comment by rebeccacremona** [comment]
@bensteinberg, over a year later, do you have any other "ill-formed API calls" in mind? I should probably check any code that accept json data. But, glancing at stack traces, I'm not seeing anything in particular pop up as an issue.

**Comment by bensteinberg** [comment]
Ha! Of course I can't remember any other examples, if I ever knew any.
