### ISSUE TITLE
nleomf.org site doesn't like to be warced (?)

### ISSUE THREAD

**Issue by phillipsm** [harvard-lil/perma#1878]
[obama's hlr piece](http://harvardlawreview.org/2017/01/the-presidents-role-in-advancing-criminal-justice-reform/) cites a [nleomf.org site](http://www.nleomf.org/facts/officer-fatalities-data/causes.html)  with a [busted perma archive](https://perma.cc/UJ58-FZSA)

**Comment by bensteinberg** [comment]
duplicates 1855?

**Comment by rebeccacremona** [comment]
This is a playback issue: the warc plays back fine in Electron.

**Comment by rebeccacremona** [comment]
Glory be, no longer busted!!
