### ISSUE TITLE
Variety WARC capture having issues

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/perma#1880]
http://variety.com/2008/scene/markets-festivals/phineas-and-ferb-1200548546/ - screenshot works, the WARC capture doesn't seem to capture successfully.

**Comment by bjohnson747** [comment]
example https://perma.cc/52Y6-AJBW

**Comment by rebeccacremona** [comment]
Can't reproduce: seems fine now! Feel free to reopen if captures of variety start misbehaving again.

**Comment by rebeccacremona** [comment]
example https://perma-stage.org/4AJX-23G2
