### ISSUE TITLE
Django edit-user admin should show deleted orgs to which user currently belongs

### ISSUE THREAD

**Issue by jcushman** [harvard-lil/perma#1887]
If a user belongs to deleted orgs, they aren't shown in the django admin (e.g. /admin/perma/linkuser/7975/change/). Use something like this hack to make sure current memberships are always shown:

http://stackoverflow.com/a/16685089/307769

**Comment by jcushman** [comment]
@rebeccacremona -- I have a partial fix for this, where deleted orgs that a user belongs to will still show under "Chosen organizations" in the admin (/admin/perma/linkuser/6/change/ or whatever). But due to Django admin's form validation they won't be removed if you try to remove them (because they don't exist). Is that better than what we have now, or equally confusing?

**Comment by rebeccacremona** [comment]
Apologies, I just saw this note now. The solution you came up with (show deleted memberships + help text to that effect) seems like a good one to me. It may indeed still be confusing, but it will at least be transparently confusing :-)

**Comment by rebeccacremona** [comment]
Observed this works on perma-stage.org (see user rebecca.cremona@.......)
