### ISSUE TITLE
Image links on homepage are broken

### ISSUE THREAD

**Issue by acoravos** [harvard-lil/perma#1895]
Below the "built to last" section. Screenshot here: https://www.dropbox.com/s/1yd5n7wlli36sxq/Screenshot%202017-02-25%2014.21.48.png?dl=0

**Comment by rebeccacremona** [comment]
Interesting! This works fine for me (see my screenshot). What browser are you using?
`
![fine](https://cloud.githubusercontent.com/assets/11020492/23334584/e94275c4-fb6f-11e6-9c4d-daab8a2b7d2e.png)

**Comment by acoravos** [comment]
Chrome. Though on second thought I am using HTTPS Everywhere, and when I inspected the element and looked up what might be happening, it said it might be due xml/https request issues. So realizing it might be due to the plugin I'm using. 

Yup: for confirmation, when I use Safari it's fine. And when I disable/re-enable HTTPS Everywhere it's fine. 

https://www.eff.org/HTTPS-everywhere

**Comment by rebeccacremona** [comment]
Huh. I wonder why HTTPS everywhere objects. We do serve our content over https, and all these images have src similar to src="/static/img/supporting-partners/IA-bw.gif".

**Comment by acoravos** [comment]
Likely it was something else? I re-enabled it and it's working fine again. Thanks for digging in.
