### ISSUE TITLE
Monitor for unusual activity

### ISSUE THREAD

**Issue by jcushman** [harvard-lil/perma#1908]
User signups, links created per day ...

**Comment by bensteinberg** [comment]
We're already doing part of this (recency of links created) at https://status.perma.cc/monitor, by virtue of https://github.com/bensteinberg/perma-status/blob/master/monitor.py, and keeping an eye on it with https://uptimerobot.com/. (The statistic we're watching is the ratio of time from now to the last completed capture, to the time from now to 20 captures ago.) This system has the merit of using the public API -- tracking user signups/logins would need special privileges, presumably.

See also https://github.com/harvard-lil/perma/issues/768
