### ISSUE TITLE
Unable to "create folder" on IE 11

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#1922]
User reporting that create, edit, delete icons missing in IE 11:

![snap](https://cloud.githubusercontent.com/assets/2140548/23862070/6a4c356e-07e2-11e7-812e-6406cfaba8f7.png)

Here's what they should look like:

![screen shot 2017-03-13 at 11 45 37 am](https://cloud.githubusercontent.com/assets/2140548/23862167/b7a5fe58-07e2-11e7-9e69-9e384aa939c2.png)

**Comment by rebeccacremona** [comment]
We have not been able to reproduce; have not heard about this from any other users or been asked to follow up.
