### ISSUE TITLE
Images broken in fivethirtyeight archives

### ISSUE THREAD

**Issue by anastasia** [harvard-lil/perma#1923]
https://perma-dev.org/KTH4-5U3G

**Comment by anastasia** [comment]
getting differing results on dev vs prod: https://perma-dev.org/Z24C-FLLK https://perma.cc/6BTD-CLQ7

**Comment by rebeccacremona** [comment]
And not working right now. https://perma.cc/JWB8-Y5NP Made a local capture and got this...
Damn. This content security thing is a more common problem than I understood in (https://github.com/harvard-lil/perma/issues/2021)
```
W238-6284 step 3: Fetching media
Error fetching media Message: {"errorMessage":"Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: \"script-src 'unsafe-inline'\".\n","request":{"objectName":"","statusCode":200,"headers":{"Cache":"no-cache","Content-Type":"application/json;charset=UTF-8"}}}
Screenshot: available via screen
```

**Comment by rebeccacremona** [comment]
Should be fixed by https://github.com/harvard-lil/perma/pull/2034
