### ISSUE TITLE
Need to correct Perma Docs- citing links page

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/perma#1932]
Need to switch the image under https://perma.cc/docs/perma-link-creation#citing-perma-links to the attached. (This one doesn't have "archived at" in its name).

<img width="635" alt="screen shot 2017-03-20 at 2 11 26 pm" src="https://cloud.githubusercontent.com/assets/12850389/24115291/3f2ef0d2-0d79-11e7-8057-fbf9172dec26.png">

**Comment by abziegler** [comment]
Why do we need to? @bjohnson747

**Comment by rebeccacremona** [comment]
Brett says this is so that the example follows the Blue Book's recommended formatting.

I think this shouldn't be an image, both for accessibility, and so that people can cut and paste. If the idea is to include a screenshot of a permalink citation "in the wild", let's find one and link to it.

**Comment by rebeccacremona** [comment]
The original is a screenshot from http://cdn.harvardlawreview.org/wp-content/uploads/2014/06/vol127_west.pdf. I'm going to keep it, add a caption and a link to the source, and add a text version underneath, where the bluebook is mentioned.
