### ISSUE TITLE
slack preview image could be improved

### ISSUE THREAD

**Issue by phillipsm** [harvard-lil/perma#1936]
do other sites square off the favicon (or whatever the element slack is using for that thumb)

<img width="804" alt="screen shot 2017-03-21 at 6 48 14 pm" src="https://cloud.githubusercontent.com/assets/196089/24174525/594d2eb8-0e67-11e7-9965-10b10435f789.png">

**Comment by anastasia** [comment]
X is the new ∞

**Comment by anastasia** [comment]
seems to have been fixed by Slack, closing
<img width="695" alt="screen shot 2018-02-05 at 12 10 02 pm" src="https://user-images.githubusercontent.com/1494102/35818256-8ab6c934-0a6d-11e8-9ccd-acb443d657bc.png">
