### ISSUE TITLE
Bulk add, or remove, users

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/perma#1939]
Add a way to bulk add, say, org users. 

As a second component of this, a way to bulk remove users could be useful as well. (user emailed re both of these)

**Comment by rebeccacremona** [comment]
We don't current handle user-related actions like creation, deletion, etc. via the API. If we did, we could model this on working with batches of links.

**Comment by rebeccacremona** [comment]
Closing in favor of https://github.com/harvard-lil/perma/issues/1550
