### ISSUE TITLE
API documentation and API key live in different places

### ISSUE THREAD

**Issue by anastasia** [harvard-lil/perma#1940]
Making interacting with the API a little bit awkward. Maybe this needs to be rethought?

**Comment by rebeccacremona** [comment]
If it's frustrating for you, must be frustrating for everybody, but can you clarify what you experienced here? I would expect docs to live in a different place from my api key. Would a link to api docs from inside the settings page?

**Comment by anastasia** [comment]
A link would definitely help. Currently we're asking the user to memorize how to get to their API Key:

<img width="818" alt="screen shot 2017-12-05 at 5 04 25 pm" src="https://user-images.githubusercontent.com/1494102/33633335-6a772f20-d9de-11e7-84a7-e9cfdc713a80.png">


I've also seen documentation where, if you are signed in and have an active key, they helpfully replace any placeholder key with yours. That could be nice to do in the future (something like Your key is: 123)
