### ISSUE TITLE
create a better 403 error message

### ISSUE THREAD

**Issue by phillipsm** [harvard-lil/perma#1952]
see our 404 and 500 templates to get started

**Comment by jcushman** [comment]
Template currently looks like this:

![image](https://cloud.githubusercontent.com/assets/376272/24620249/ec5ad23e-186a-11e7-867c-961f7b60abe7.png)

**Comment by rebeccacremona** [comment]
Ooh. This will be easy in Django 1.10. https://docs.djangoproject.com/en/1.11/releases/1.10/#csrf
