### ISSUE TITLE
Trouble accurately capturing Russian websites

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/perma#1969]
Perma has some trouble making good, accurate captures of some Russian sites.
ex: http://www.duma.gov.ru/news/274/434078/?sphrase_id=2412226
captures as: https://perma.cc/2SJF-3KCR

User uses PDF of the site instead, which works, but still doesn't really accurately represent the site.

**Comment by rebeccacremona** [comment]
Aha. This is a actually just a playback issue: if I download the warc and view it using Ilya's electron view, they all play back perfectly. https://github.com/webrecorder/webrecorderplayer-electron/releases/tag/v1.0.3. I'll see about updating our pywb.

**Comment by rebeccacremona** [comment]
Hmm. Nope, upgrading from 0.33 to 0.33.1 doesn't help.
