### ISSUE TITLE
Check for invalid characters on archive creation 

### ISSUE THREAD

**Issue by anastasia** [harvard-lil/perma#1975]
https://perma.cc/DRA5-3SRB is 
https://www.ntanet.org/wp-content/uploads/proceedings/2014/141-phillips-plumley-effort-compliance-endogenous-taxpayer-decisions.pdf\x00

**Comment by rebeccacremona** [comment]
Looks like Jack fixed this while porting the api from Tasty Pie to DRF. Test specifically for this case.: https://github.com/harvard-lil/perma/blame/70c750f34997e15f088b2d5199e3129d10790c14/perma_web/api/tests/test_link_validation.py#L56.
