### ISSUE TITLE
Send perma an email digest of frontend errors

### ISSUE THREAD

**Issue by anastasia** [harvard-lil/perma#1976]
Could be a good thing to do? Otherwise we just forget /manage/errors exists

**Comment by rebeccacremona** [comment]
Let's investigate why we are getting so many of these, and let's look into text encoding (e.g. " [{&quot;function&quot;: &quot;&quot;, &quot;column&quot;: 0, &quot;line&quot;: 9591, &quot;file&quot;: &quot;https://172.69.60.83/static/bundles/stats.d1d1971406e7.js&quot;}]"

**Comment by rebeccacremona** [comment]
Looks like sometimes, we don't have a stack trace:
```
  File "/srv/www/perma/perma_web/perma/tasks.py", line 1351, in send_js_errors
    formatted_errors = map(lambda err: err.format_for_reading(), errors)
  File "/srv/www/perma/perma_web/perma/tasks.py", line 1351, in <lambda>
    formatted_errors = map(lambda err: err.format_for_reading(), errors)
  File "/srv/www/perma/perma_web/perma/models.py", line 1497, in format_for_reading
    formatted['stack'] = json.loads(self.stack)[0]
IndexError: list index out of range
```

**Comment by rebeccacremona** [comment]
Yeah, evidently occasionally the stacktrace is a unicode cast of an empty list.

```
print(problem.stack)
u'[]'
```
