### ISSUE TITLE
Sporadically failing to capture or playback certain images

### ISSUE THREAD

**Issue by anastasia** [harvard-lil/perma#2035]
captured https://theintercept.com/
on https://perma-stage.org/8ZHW-SNUE

None of the images appear, either, but don't report any errors.
This is how an image is shown in the DOM:
```<div class="ResponsiveImage HomeFeature-image" style="margin-top:0px;padding-top:100%;" data-reactid=".ti.1.3.0.0.1"><noscript data-reactid=".ti.1.3.0.0.1.0">&lt;img src="//user-content.perma-stage.org/warc/8ZHW-SNUE///prod01-cdn07.cdn.firstlook.org/wp-uploads/sites/1/2017/05/recrop-mehdi-hasan-donald-trump-saudi-arabia-1494967352-440x440.jpg" class="ResponsiveImage-image" height="440" width="440"&gt;</noscript></div>```

Live website's image attribute:
```<div class="HomeFeature-image-block" data-reactid=".ti.1.3.0.0"><div class="ResponsiveImage HomeFeature-image" style="margin-top: 0px; padding-top: 50%;" data-reactid=".ti.1.3.0.0.1"><img class="ResponsiveImage-image" src="//prod01-cdn07.cdn.firstlook.org/wp-uploads/sites/1/2017/05/recrop-mehdi-hasan-donald-trump-saudi-arabia-1494967352-article-header.jpg" width="1440" height="720" data-reactid=".ti.1.3.0.0.1.0"></div></div>```

potentially something like lazy-loading is used, where a noscript tag gets appended at first and then rewritten as an img tag when that section of the site comes into view.

**Comment by rebeccacremona** [comment]
Interesting. I'm getting at least a few images. https://perma-stage.org/W85B-K5Q9

**Comment by rebeccacremona** [comment]
Another one of these fun hit-and-miss web issues.....
