### ISSUE TITLE
Patch holes in API test coverage

### ISSUE THREAD

**Issue by jcushman** [harvard-lil/perma#2054]
Known edge cases for our API that don't currently have test coverage (line numbers may not be up to date):

utils.py:
- [ ]    line 86: should raise Http404 if requested API item does not exist (we don't currently test what happens if *any* item doesn't exist -- not sure if we need to do this for one endpoint or all)
    
authentication.py:
- [ ]    line 18: can authenticate via api_key instead of django auth
    
serializers.py:
- [ ]    line 193: should object on attempt to create link with no url
- [ ]    line 213: should object on attempt to archive a URL that returns a non-integer content-length header (not actually sure if this is worth testing, since we just catch and ignore)
- [ ]    line 221: should object on attempt to archive a URL that returns a redirect loop
- [ ]    line 227: should object on attempt to upload a file without supplying a file: POST /archives {'file':''}, or PATCH /archives/:id {'file':''}
        (this is what happens when user submits a blank file upload form in our frontend)
    
views.py:
- [ ]    line 48: should object on attempt to search links with an invalid filter value, such as ?date=not_a_date
- [ ]    line 199: should object on attempt to PUT non-nested folder: PUT /folders/:id
- [ ]    line 244: can get capture_job by capture_job.id rather than link guid: GET /capture_jobs/:id
- [ ]    line 337: should object on attempt to archive a link having already reached link limit
- [ ]    line 346: should set new link status to private if org defaults to private
- [ ]    line 377: can set 'human' when submitting new link for archiving: POST /archives {'url':'http://example.com', 'human':true}

**Comment by rebeccacremona** [comment]
Thanks for adding this list to Github! I have some of these tests prepared, but then got side tracked refactoring/re-structing the tests. I'll try to merge in what I've got soon.
