### ISSUE TITLE
PDF in Perma Link displaying only 1st page on mobile

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/perma#2056]
PDF at http://www.nyulawreview.org/sites/default/files/pdf/NYULawReview-77-6-Daines.pdf was made into a Perma Link: https://perma.cc/M3MM-P95L

On desktop, Perma Link PDF displays in full, no problem. On mobile, Perma Link only lets 1st page be viewed (issue re-created in both safari and chrome on mobile).

**Comment by rebeccacremona** [comment]
I think we should leave this for Apple to fix: it's a long-standing issue with mobile Safari with no satisfactory workarounds. For some discussion, see the following thread on StackOverflow and similar: https://stackoverflow.com/questions/15480804/problems-displaying-pdf-in-iframe-on-mobile-safari

**Comment by bjohnson747** [comment]
Jack had the idea for a button that, on mobile, let's the user "view PDF", which would take them directly to the doc/out of the iFrame.

**Comment by rebeccacremona** [comment]
Reports are that on some people's iOS devices, even switching to Chrome or Firefox doesn't help. So, we'll try something like this:

![download_button](https://user-images.githubusercontent.com/11020492/27405345-3d26bc1a-569f-11e7-937a-d06d84e7988a.png)

**Comment by bjohnson747** [comment]
That looks great. (Should it be changed to - when mobile is detected - saying "Perma.cc can't display this file *on mobile* but [...]"

**Comment by rebeccacremona** [comment]
For the record: this is still a thing. Just checked https://discussions.apple.com/thread/250075244 with my shiny new iPhone.

**Comment by Sean-In-The-Library** [comment]
Still a problem in Oct, 2023

**Comment by rebeccacremona** [comment]
@Sean-In-The-Library alas, yes, unfortunately we think this is unsolvable at this time https://github.com/harvard-lil/perma/issues/3358
