### ISSUE TITLE
Ad on site crashing Perma capture

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/perma#2059]
http://www.telegraph.co.uk/technology/apple/9283706/Jonathan-Ive-interview-simplicity-isnt-simple.html
Page appears to capture correctly, but when the perma archive is viewed with ad-blocker turned off, it crashes the window.

**Comment by rebeccacremona** [comment]
Recreated locally: capture is fine. But, playback is inconsistent. Most of the time, hangs. With javascript off, playback is fine. 

![image](https://user-images.githubusercontent.com/11020492/30824627-23591986-a1fe-11e7-8c2e-3906e3d1c9d3.png)

**Comment by rebeccacremona** [comment]
Clarification of "fine": you get most content and ads. Most obviously missing a section of ads with the header "recommend by Outbrain."

**Comment by rebeccacremona** [comment]
If left open indenfinitely (not in Perma's iframe, lots of ads load, lots of in-browser bidding, but nothing obviously ill-behaved

**Comment by rebeccacremona** [comment]
Evidently responsible: http://js-sec.indexww.com/ht/p/184224-249976729910975.js

Attempt playback in Firefox while recording performance profiling. When Firefox offers to stop a tab that is slowing down your browser, let it, and then stop the profiling. Observe that almost all the time is spent in the captured version of //js-sec.indexww.com/ht/p/184224-249976729910975.js

**Comment by rebeccacremona** [comment]
Loading capture in Chrome, that Chrome Helper process begins using 100% CPU......

**Comment by rebeccacremona** [comment]
Oh, this was fixed long ago.
