### ISSUE TITLE
Mark Captures as Pending instead of Failed when status is pending

### ISSUE THREAD

**Issue by anastasia** [harvard-lil/perma#2082]
<img width="894" alt="screen shot 2017-08-05 at 1 19 01 pm" src="https://user-images.githubusercontent.com/1494102/28997381-b15442c4-79e0-11e7-93a6-9a2007396037.png">

<img width="1280" alt="screen shot 2017-08-05 at 1 19 37 pm" src="https://user-images.githubusercontent.com/1494102/28997382-c432a1a6-79e0-11e7-8f4e-2919dc000972.png">

**Comment by rebeccacremona** [comment]
Fixed in https://github.com/harvard-lil/perma/commit/f570188054fec3b8319049aad712bdf4d6c9d699
