### ISSUE TITLE
Get travis to work with Trusty

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/perma#2088]
We're hitting snooze on this for now:
https://github.com/harvard-lil/perma/pull/2081

**Comment by bensteinberg** [comment]
Fixed in https://github.com/harvard-lil/perma/pull/2110 -- but that PR is closed for the moment.

**Comment by bensteinberg** [comment]
Fixed in https://github.com/harvard-lil/perma/pull/2141
