### ISSUE TITLE
Indiegogo pages refuse to be Perma'd

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/perma#2093]
When Perma-ing an Indiegogo page, it stops the process, believing that Perma is a bot. 
The WARC capture displays "Link not found", and the screenshot view shows the below. 
ex. link: https://perma.cc/8T9S-Y5AN?type=image
![cap](https://user-images.githubusercontent.com/12850389/29090110-851b4f4a-7c4c-11e7-9062-645ab354e76b.png)

**Comment by bjohnson747** [comment]
Emailing Indiegogo to see if we can be added to a whitelist

**Comment by rebeccacremona** [comment]
No longer seeing this. Might wait a bit and see if it sticks, then close.

**Comment by rebeccacremona** [comment]
Still no longer seeing this. Fingers crossed.
