### ISSUE TITLE
FTP protocol not supported for captures

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/perma#2094]
Currently FTP protocol not supported for Perma captures. (let brett know if you need more info/the example link)

**Comment by bensteinberg** [comment]
The first issue is not to do bad "validation" in `perma_web.api.serializers.validate_url`, but then there's the point that an FTP server does not (of course) return HTTP headers, which we rely on in `run_next_capture`. Best approach here to be discussed.

**Comment by bensteinberg** [comment]
Here's an example link: ftp://ftp.fao.org/docrep/fao/011/i0100e/i0100e.pdf

**Comment by bjohnson747** [comment]
bump - this came up again with a different user ([their link](ftp://ftp.fao.org/docrep/fao/011/ak357e/ak357e00.pdf))

**Comment by rebeccacremona** [comment]
I'm not sure we should support this: 

No support in IE11 or Microsoft Edge, Chrome to mark all ftp sites as insecure (https://www.theregister.co.uk/2017/09/15/chrome_to_label_ftp_sites_insecure/), https://support.mozilla.org/en-US/questions/1173126

**Comment by bensteinberg** [comment]
As discussed, let's consider getting FTP URIs with paramiko or the like.

**Comment by bjohnson747** [comment]
+1 another user request for FTP capture support
