### ISSUE TITLE
Manage registrar view

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/perma#2097]
We're going to want to be able to find all our eligible-to-pay registrars in this view. 
![registrars](https://user-images.githubusercontent.com/11020492/29282904-907bb51e-80f2-11e7-8775-99431a0579f6.png)

**Comment by rebeccacremona** [comment]
We might also want to be able to filter by montly/annual, sort or filter by paid/not paid, and, possibly, if we have lots of different prices, possibly sort by price.

**Comment by jcushman** [comment]
Maybe a good moment to think again about the Django admin interface -- could do all of that by adding an item or two to a list in there.

**Comment by abziegler** [comment]
For it. I'm on much better terms with django-admin these days.

**Comment by rebeccacremona** [comment]
Included in upcoming pull request.
