### ISSUE TITLE
display toggles (default to screenshot, etc)

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/perma#2105]
In response to some sites (dictionary.com) having issues redisplaying WARC playback correctly due to ads, having a toggle to default to screenshot view would be nice.

(edit 12/5 splitting old the below into a separate issue)
~Also nice would be capture toggles: capture/don't capture ads, don't capture javascript, etc. Advanced capture mode.~

**Comment by rebeccacremona** [comment]
duplicate with #1470
