### ISSUE TITLE
More efficient playbacks?

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/perma#2107]
In this stanza of code, we use a regex inside a list comprehension inside a loop to "remove any redirects if we also have a non-redirect capture for the same URL, to prevent redirect loops"
https://github.com/harvard-lil/perma/blob/develop/perma_web/warc_server/pywb_config.py#L164

Instead, why don't we add a field to the CDXline model "is_redirect", populate it on creation, and use Django filtering here? I'm guessing that would be more efficient.

**Comment by jcushman** [comment]
Interesting! Have you profiled this as a performance problem?

If not, my suggestion would be to start by adding some timing statements so we can print (a) the total server time spent on rendering a complex playback and (b) the time spent on the stanza you identified.

My guess is this would reveal that optimizing that stanza won't have any measurable effect on total playback time and isn't worth extra effort, but that optimizing some other part would. 

The reason for my guess is I think running a regex across a few hundred URL-length strings (one per captured url), once during the playback of a page, will be so fast that it's not worth messing with. But I could be wrong! That's the fun of optimizing ...

**Comment by rebeccacremona** [comment]
WR has its own solution for preventing redirect loops.
