### ISSUE TITLE
Playback url

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/perma#2112]
Can we playback a url starting in a more clever way, like Web Recorder app does? These warcs playback fine when downloaded and view in the desktop app, but are blank in Perma: https://perma.cc/VV6S-LYAZ

(beautiful screen captures exposed, at least)

**Comment by rebeccacremona** [comment]
Interesting. Could we iterate through Perma's collection and look for all cases where Perma's `capture.playback_url` doesn't match the first/best bookmark found by WR when analyzing the warc, and adjust Perma's records? Probably. That has the potential to fix a lot of broken Forbes captures, at least. Worth investigating, post launch.

**Comment by matteocargnelutti** [comment]
Hi 2019 @rebeccacremona . Your 2022 client-side playback integration solved this problem 👏 🎉 .
