### ISSUE TITLE
API documentation for archive view does not match result

### ISSUE THREAD

**Issue by leonidg** [harvard-lil/perma#2116]
The response for `https://api.perma.cc/v1/user/archives/` does not match the [documentation](https://perma.cc/docs/developer#view-all-archives-of-one-user).  Here is an example for user `law.annualsurvey@nyu.edu` (I called with `limit=`):

<pre>
{   u'meta': {   u'limit': 1,
                 u'next': u'https://api.perma.cc/v1/user/archives/?api_key=bdce593fff5dd3d7c4a97cd1142ac1f8c17090ec&limit=1&offset=1',
                 u'offset': 0,
                 u'previous': None,
                 u'total_count': 107},
    u'objects': [   {   <b>u'archive_timestamp': u'2017-09-01T19:15:02Z',</b>
                        <b>u'capture_time': 15,</b>
                        <b>u'captures': [   {   u'content_type': u'text/html; charset=utf-8',
                                             u'playback_url': u'//perma-archives.org/warc/9PHF-BA7P/http://www.law.nyu.edu/news/Ndidi-Oriji-NBCUniversal-advertising-standards-and-practices-comedy',
                                             u'record_type': u'response',
                                             u'role': u'primary',
                                             u'status': u'success',
                                             u'url': u'http://www.law.nyu.edu/news/Ndidi-Oriji-NBCUniversal-advertising-standards-and-practices-comedy',
                                             u'user_upload': False},
                                         {   u'content_type': u'image/png',
                                             u'playback_url': u'//perma-archives.org/warc/9PHF-BA7P/id_/file:///9PHF-BA7P/cap.png',
                                             u'record_type': u'resource',
                                             u'role': u'screenshot',
                                             u'status': u'success',
                                             u'url': u'file:///9PHF-BA7P/cap.png',
                                             u'user_upload': False},
                                         {   u'content_type': u'image/x-icon',
                                             u'playback_url': u'//perma-archives.org/warc/9PHF-BA7P/http://www.law.nyu.edu/sites/default/files/favicon.ico',
                                             u'record_type': u'response',
                                             u'role': u'favicon',
                                             u'status': u'success',
                                             u'url': u'http://www.law.nyu.edu/sites/default/files/favicon.ico',
                                             u'user_upload': False}],</b>
                        u'created_by': {   u'first_name': u'Leonid',
                                           u'full_name': u'Leonid Grinberg',
                                           u'id': 14558,
                                           u'last_name': u'Grinberg',
                                           u'short_name': u'Leonid'},
                        u'creation_timestamp': u'2017-08-31T19:15:02Z',
                        <b>u'description': u'When Ndidi Oriji \u201903 graduated from NYU Law, her mother gave her an unusual gift: a piece of construction paper with the summary of a play-pretend court case she had written as a child\u2014inspired by the television show',</b>
                        u'guid': u'9PHF-BA7P',
                        u'is_private': False,
                        u'notes': u'',
                        u'organization': {   u'default_to_private': False,
                                             u'id': 390,
                                             u'name': u'Annual Survey of American Law',
                                             u'registrar': u'New York University Law Library',
                                             u'shared_folder': {   u'has_children': True,
                                                                   u'id': 9031,
                                                                   u'name': u'Annual Survey of American Law',
                                                                   u'organization': 390,
                                                                   u'parent': None}},
                        <b>u'private_reason': None,</b>
                        <b>u'queue_time': 121,</b>
                        u'title': u"Ndidi Oriji '03 combines her skills in law and entertainment in her work at NBCUniversal | NYU School of Law",
                        u'url': u'http://www.law.nyu.edu/news/Ndidi-Oriji-NBCUniversal-advertising-standards-and-practices-comedy',
                        <b>u'warc_size': 935483</b>}]}
</pre>

I bolded the things that are different; most don't matter (because they're just additional info), but it looks like what is documented as an `assets` list in the documentation is now replaced by `captures` with different information.

Also, the documentation suggests that the response should have a `folders` list (presumably showing which folders[*] the archive is located in).  That is absent here.

[*] I am not totally sure why it's plural, as the UI implies that each archive can only be in one folder?

**Comment by leonidg** [comment]
Oh, there is a very similar issue with `https://api.perma.cc/v1/archives/<guid>` as well.

**Comment by rebeccacremona** [comment]
Fixed!
