### ISSUE TITLE
No way to get IDs for subfolders?

### ISSUE THREAD

**Issue by leonidg** [harvard-lil/perma#2117]
I may be wrong on this, but I think the combination of #2115 and #2116 make it impossible to get any IDs, and therefore info for, subfolders.

* The `https://api.perma.cc/v1/folders/<folder id>/` endpoint will note whether the folder has children, but not say anything about them (consistent with the documentation).
* As #2115 explains, the `https://api.perma.cc/v1/user/organizations/<organization ID>/folders/` endpoint appears to be broken; I am not sure, but I assume that that response would have included subfolders.
* As #2116 explains, the `folders` list is missing for both endpoints that reveal details of archives.
* This isn't really an answer for the API, but as far as I can tell, the UI does not reveal the folder ID either.

**Comment by leonidg** [comment]
Ah, ok, having perused the source, I have discovered `/folders/<folder id>/folders/`.  So never mind, although I would add that to the documentation. :)

**Comment by rebeccacremona** [comment]
Fixed in 2356
