### ISSUE TITLE
American Banker site - capture issues

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/perma#2122]
https://www.americanbanker.com/news/ny-could-set-national-standard-with-cybersecurity-proposal

Example capture: https://perma.cc/MQ2K-UZ3D - appears to have an ad page overlay that makes the capture not complete/successful. Perhaps similar solution to the Forbes fix for this?

**Comment by rebeccacremona** [comment]
Funny, the whole capture plays back perfectly.... it's just that stupid div in the way. You can delete it with dev tools lol.

I think some javascript is being shut down by our security policies, which is causing the button to not update to a clickable "Continue to site". Production webrecorder has the same difficulty, so this will be a thorny one.

**Comment by matteocargnelutti** [comment]
Another playback problem fixed by the new client-side player 😮 !
