### ISSUE TITLE
Add server/browser/version to Link model?

### ISSUE THREAD

**Issue by bensteinberg** [harvard-lil/perma#2129]
In the era of scaled capture, where multiple machines might be running Celery tasks, should we store what machine was responsible for a capture? IP address? Browser and version, almost certainly.
This information is available in the celery logs, but could be difficult or impossible to get without log aggregation, and in any case shouldn't be available beyond the limits of log retention.

**Comment by rebeccacremona** [comment]
To CaptureJob

**Comment by matteocargnelutti** [comment]
(Cross-referenced in https://github.com/harvard-lil/perma-capture/issues/73)
