### ISSUE TITLE
Upgrade cryptography to 1.9+ to allow build on stretch

### ISSUE THREAD

**Issue by bensteinberg** [harvard-lil/perma#2130]
See https://github.com/pyca/cryptography/issues/3605 and https://github.com/pyca/cryptography/pull/3603 -- our current cryptography, 1.8.1, won't build with openssl 1.1.0f, which is what's in Debian stretch.

**Comment by jcushman** [comment]
Looks like this means update `requests` ...

**Comment by bensteinberg** [comment]
Yep. This issue is mainly a reminder to me to pull on that dependency chain, and documentation for the update to requests.
