### ISSUE TITLE
User agent causes capture problem with some sites (all .ashx? some particular hosts?)

### ISSUE THREAD

**Issue by bensteinberg** [harvard-lil/perma#2131]
Captures of http://www.lockelord.com/newsandevents/publications/2016/09/~/media/29B6061AB4C248ACB398C08993C4E44B.ashx result in error pages with text like "The specified URL cannot be found. Please contact your system administrator with the following incident ID to resolve. Incident ID: 15f0c5c66f0-535f5d7b":

<img width="1552" alt="screen shot 2017-10-11 at 12 56 29 pm" src="https://user-images.githubusercontent.com/3776423/31454506-a949f4b6-ae83-11e7-84e8-ccc120111166.png">

I thought this might be an artifact of the new capture server, but I got the same result with the old capture server, e.g. https://perma.cc/G32G-VQ6S

**Comment by bensteinberg** [comment]
```
-sh-4.1$ curl -A "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36" -I http://www.lockelord.com/newsandevents/publications/2016/09/%7E/media/29B6061AB4C248ACB398C08993C4E44B.ashx
HTTP/1.1 200 OK
Cache-Control: private, max-age=604800
Content-Length: 96120
Content-Type: application/pdf
Expires: Thu, 19 Oct 2017 14:29:57 GMT
Last-Modified: Fri, 16 Sep 2016 01:15:41 GMT
x-a: MDLOC
x-s: 02
X-Frame-Options: SAMEORIGIN
Date: Thu, 12 Oct 2017 14:29:57 GMT
x-e: AP9A

-sh-4.1$ curl -A "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.37 Safari/537.36" -I http://www.lockelord.com/newsandevents/publications/2016/09/%7E/media/29B6061AB4C248ACB398C08993C4E44B.ashx
HTTP/1.1 404 Not Found
Connection: Close
Content-Type: text/html

-sh-4.1$
```

**Comment by rebeccacremona** [comment]
We just heard about another instance of this exact behavior: http://www.jonesday.com/dlcarden/

Can reproduce via curl.

Both sites work if you curl with a different user agent: `curl -A "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/534.30 (KHTML, like Gecko) Chrome/12.0.742.112 Safari/534.30"` (chosen at random from a Stackoverflow discussion on user agents). 

Note that the lockelord site should be https, and the payload is a pdf.

**Comment by rebeccacremona** [comment]
Should we consider this #phantomjs-only? Presumably when using Firefox or Chrome, we'll happily use the real user agent?

**Comment by bjohnson747** [comment]
Another site that uses a similar service, blocking Perma: venable.com

**Comment by rebeccacremona** [comment]
Confirmed that #2628 fixes this for those three domains; confirmed still broken on prod, so it definitely worked.
