### ISSUE TITLE
allow 3DES stream cipher for TLS connections?

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/perma#2171]
In https://github.com/harvard-lil/perma/commit/4215ca5a6289381b1e6872ec48678792b077ed83, we upgraded from requests[security]==2.11.1 to requests[security]==2.18.4. Behind the scenes, that upgraded urllib3 to a version higher than 1.16 (which was bundled inside requests 2.11).

urllib3 1.16 is the last version that included 3DES in it's list of default ciphers (https://github.com/shazow/urllib3/pull/958/files).

As a result, every attempt we make to speak to websites like http://library.cqpress.com/cqalmanac/document.php?id=cqal70-1292316 fails. For instance, [here](https://github.com/harvard-lil/perma/blob/develop/perma_web/perma/models.py#L870), before we even attempt a capture.

We can override, and allow 3DES if we want. Minimal demonstration (though we'd probably want/need to do this at the requests level):
```python
import urllib3
from urllib3.util.ssl_ import create_urllib3_context
from urllib3 import PoolManager

http = urllib3.PoolManager()
r = http.request('GET', 'https://library.cqpress.com/cqalmanac/document.php?id=cqal70-1292316')
# this will fail with something like urllib3.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:661)

#solution adapted from https://lukasa.co.uk/2017/02/Configuring_TLS_With_Requests/
CIPHERS = (
    'ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+HIGH:'
    'DH+HIGH:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+HIGH:RSA+3DES:!aNULL:'
    '!eNULL:!MD5'
)

ctx = create_urllib3_context()
ctx.set_ciphers(CIPHERS)
p = PoolManager(ssl_context=ctx)
r = p.urlopen('GET', 'https://library.cqpress.com/cqalmanac/document.php?id=cqal70-1292316')
assert r.status == 200
```

**Comment by rebeccacremona** [comment]
I'd like to see how common this is. I'll check against the list of recent failed capture jobs.

**Comment by rebeccacremona** [comment]
If we decide we want to, here's a discussion of how to do it for any random domain, instead of a single domain at a time (which lukasa is dead against): https://github.com/requests/requests/issues/1308

**Comment by rebeccacremona** [comment]
The example site listed here has since updated their SSL situation, and no longer use 3DES

**Comment by leppert** [comment]
The intent is to close this ticket but we should check whether the behavior on Scoop is different.

**Comment by rebeccacremona** [comment]
On reflection: this is less of a Scoop behavior question, and more of a Perma + Scoop question. Perma currently [validates the submitted URL](https://github.com/harvard-lil/perma/blob/develop/perma_web/api/serializers.py#L227-L256) before putting a capture job on the queue for a user, so that they get immediate feedback, instead of presenting them with a failed capture job after the fact.

If this is still relevant (and it may not be, 2017 was a long time ago), we'll still fail in python land, before ever handing anything off to Scoop.

...which reminds me to make a card in the Scoop + Perma project: we should talk about whether we want to keep this kind of validation.

**Comment by rebeccacremona** [comment]
After doing some reading, I'm going to take the liberty of removing @matteocargnelutti's assignment and closing this after all... and will write up a thing about Perma/python URL validation vs Scoop in that project.
