### ISSUE TITLE
IA "expat" errors

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/perma#2201]
Investigate why we are getting dozens of "expat" errors from the task to upload warcs to IA

Task perma.tasks.upload_to_internet_archive with id 4b9f2071-be7f-43c5-9e51-e4f7871836cb raised exception:
"ExpatError('syntax error: line 1, column 49',)"

**Comment by anastasia** [comment]
- create a daily report instead of stacktrace emails
- catch common IA failure errors

**Comment by anastasia** [comment]
could be related to this, as we're sometimes experiencing similar problems: https://github.com/jjjake/internetarchive/issues/178
