### ISSUE TITLE
Upgrade celery

### ISSUE THREAD

**Issue by jcushman** [harvard-lil/perma#2206]
We're on celery 3, which sends its own custom error messages, which have over-long subject lines that come through as `<no subject>` in Outlook.

We should upgrade to celery 4, which drops the custom error messages, and hopefully will just send messages through Django's existing logger (maybe with a tweak to the logging settings).

**Comment by rebeccacremona** [comment]
Done in https://github.com/harvard-lil/perma/pull/2714/ . We'll have to see about logging settings.
