### ISSUE TITLE
Batch link project: track TODOs here

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/perma#2293]
## Nits

- [x] Typo: "expost" button should read "export"
- [x] Missing setting: 'BULK_UPLOADS' needs to be added to TEMPLATE_VISIBLE_SETTINGS
- [x] Importing settings: api/view.py imports settings from perma.settings. Django docs say we should import settings like this `from django.conf import settings` to make sure that everything works as expected (including giving you the flexibility to change your directory structure).https://docs.djangoproject.com/en/2.0/topics/settings/#using-settings-in-python-code
- [x] Let's call this model LinkBatches (discussed, perhaps not communicated!)
- [x] Let's squash these migrations into one
- [x] Batch/LinkBatch model needs a `__unicode__(self)` method so that it prints/displays nicely (instead of the default ` <Batch: Batch object>`)
- [x] Let's double check to make sure we use the word "batch" vs "bulk" consistently across the code and UI
- [x] If RUN_TASKS_ASYNC = False, only the first link in a batch will capture successfully. Let's make sure developers get notified of that when reading the code. Comment in settings_common? Some consistency check that prints a warning to the console on server start?
- [x] Batch model's "accessible_to" method tweak: I think this can be condensed to `return user.is_staff or self.created_by == user`
- [x] Total total nit: would "saved_folder" be better "target_folder"?
- [x] Let's catch a specific exception in the safe_get method, rather than the blanket Exception

## JS Investigations
- [x] We want the progress bar template (and any other new templates )to be inside the `{% templates %}` block... but this turns out to open a big can of worms... the progress bar template doesn't work if put there! To be investigated...

## Error Handling
- [x] A CaptureJob now needs to be created for every attempted creation of a PermaLink. The current draft of the batch link creation code handles the case where we get so far as:
    ```
    serializer = self.serializer_class(data=data, context={'request': request})
    if serializer.is_valid(): 
    ```
    But we can actually return in a number of places above that, wherever `raise_validation_error` is called, or if an unexpected exception gets raised somewhere. Let's tweak this code so that a CaptureJob is always created. Strategy might include creating a CaptureJob object at the very top of the function and changing relevant fields (status, batch, link, etc.) further down in the function as appropriate. We can figure out how to save the object most efficiently/robustly/dry-ly.
- [x] A CaptureJob should store error messages, if any.
- [x]  The modals should display those error messages, when present. If, for some reason, no CaptureJob is present, or no PermaLink is present, the modal shouldn't show an empty red box where the PermaLink is normally displayed.
- [x] Is there error handling included in the js that uses Promises? I don't see any, but I haven't worked with Promises before. If there isn't, let's add error handling to handle the failure of any or all Promises.

## Modal functionality
- [x] It would be wonderful if, for improved UX, the modal for creating batch links "swapped out" the input field and interface on submit, rather than doing some work, and then when that work is over, 'redirecting' to a second modal where you can track the progress of the batch. Let's see if we can devise some ajax cleverness / abstract out some of the functionality to smooth this out and possibly speed it up a bit, recognizing that modal to inspect old batches is quite similar (can we reuse js and templates in both modals, etc.?) 
- [x] We need the batch modal to reset, so that when, after creating a batch, you exit the modal, and click on "create multiple" again, you get a fresh modal, ready to create a new batch, rather than a report on the status of your last-created batch. We should be able to do this without requiring a refresh of the page.
- I wonder how time consuming it is to build the csv on load. Maybe we can contrive to only build the csv when the "export" button is clicked. I think some creepy js would work: you can alter the href of a link AFTER is is clicked using:
    ```
        let link = document.getElementById('my_link');
        link.onclick = function(){
            link.href = "http://new-destination.com";
            return true;
        }
    ```
    Whether that works with `data:` and whether we are comfortable with that craziness are separate questions. Update: not doing, can reconsider if people complain about big batches.

## API behavior
- [x] Jack thinks the API would be a lot more natural if the route to create a LinkBatch accepted a list of URLs. That does sound natural; what's a good way to achieve that cleanly? We could try some trick like https://github.com/harvard-lil/perma/compare/develop...rebeccacremona:bulk-experimenting#diff-a57c92b5a3cdb16770f3a7dd00291c11R122 to use the api function as though it were a normal function, calling it once per provided URL... but this code is a peculiar enough to make me nervous. Better plan? A normal util function? Let's discuss.
- [x] If we retrieve the batch in the link-creating API route, we should make sure it's a batch that user created.
    ```
    if perma.settings.BULK_UPLOADS:
        batch = safe_get(Batch, request.data.get('batch_id', None))
        CaptureJob(link=link, human=request.data.get('human', False),
                            submitted_url=link.submitted_url, batch=batch).save()
    ```
- [ ] ~Should we cache, in a field on the LinkBatch model, whether that Batch is "done"?~

## Styling
- The recently-added css for making the folder list scroll.... has completely broken the Batch History sidebar. Whoops. To be discussed.

A work in progress. This is just a few things we'll want to be sure to catch, while we're polishing:
- [x] Let's make sure the modal works at all screen sizes. The Upload Your Own modal seems to be a good model. We'll want to avoid setting the modal width to a certain pixel size via a scss variable.
- [x] Let's try to use html classes, and target those classes in the css, rather than setting css straight in js, e.g. `$input_area.prop("disabled", true).css("cursor", "not-allowed");`
- [x] Let's keep all the styles for a particular selector together; duplicating the selector can help organize related css, but makes it easier to accidentally duplicate directives

## Accessibility
- [x] The input fields in the modals need `<label>`s. We can hide them using Bootstrap's `sr-only` class so the design doesn't change.
- [x] The "buttons" in the modals should be true html `button` elements rather than `a` elements. See https://github.com/rebeccacremona/a11y-games/blob/master/app/buttons-and-links/info.md for discussion.
- [x] We need to capture keyboard focus when the modals are open so that you can't tab, using your keyboard or assistive technology, to the background while the modal is still open. See https://github.com/harvard-lil/accessibility-tools/tree/master/code/modals for discussion and tricks.
- [x] We shouldn't be able to scroll the background content when the modal is open. (Looks like this is a problem across Perma: let's see if we can fix all the modals at once.)
- [x] It's generally considered a better practice to put the "create" button (primary action) before the cancel button (secondary action).
- [x] Let's add an "x" to the top of the modal for easy dismissal. (Escape key works already, yay!)

## Batch History sidebar
- [x] Let's confirm that this consistently returns the most recent batches, without needing a sort clause: 
    ```
    // populate batches list
    APIModule.request("GET", "/batches/", {"limit": 15}).done(function(data)...
    ```
## Django Admin
- [x] Let's add LinkBatches to the Django admin

## Docs

- [ ] User-facing docs (with a screenshot or two, once the styles stabilize)
- [x] API docs
- [x] Dev docs (only works completely with async=True, etc.)

## Tests

- [ ] Tests via python for the api routes
- [ ] Functional tests for a least some of the modal functionality: dropdown populated as expected, dropdown works, batch creation possible.

Tests are possibly going to be finicky because tests currently run with async=False, which means only the first link in the batch will actually get handled correctly

**Comment by leonidg** [comment]
With regard to generating the CSV only on click, another option is to make the button just set `window.location` to that data?  I haven't actually tried it, but I think it might work, and it would also be better in terms of the button-vs-link thing.

**Comment by rebeccacremona** [comment]
That's an interesting idea! I haven't tried it either. We should experiment.
