### ISSUE TITLE
Playback of http in Chrome

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/perma#2295]
I'm hoping it's just this PDF, but surely not.... https://perma.cc/3V9S-2YAE. Observe the 404 is for https, and the resource is at http.

Works fine on Webkit browsers.

**Comment by rebeccacremona** [comment]
I think this is fixed w/WR playback. After that is deployed to prod, check the above link in Chrome, and if it works, let's close this issue.

**Comment by rebeccacremona** [comment]
Whoa, today, with WR on prod, in Chrome, I'm getting the dreaded "oh snap" error.

Looks fine in Firefox.

**Comment by rebeccacremona** [comment]
This is still true.

**Comment by matteocargnelutti** [comment]
Another playback issue that can't be reproduced with the new client-side playback system 🎉 !
