### ISSUE TITLE
Docker docs!

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/perma#2379]
Add Docker dev environment docs to install.md!!!! draft here https://github.com/harvard-lil/perma/pull/2203

Also, we need to make sure a fresh clone works. Right now, you have to create a settings.py, and settings.example.py needs updating. 

We should consider adding a blank or blankish settings.py to the repo.

**Comment by jcushman** [comment]
The goal is that `settings_dev.py` provides everything a fresh clone needs, without creating a `settings.py` -- sounds like that's not currently true?

It wouldn't make sense to add settings.py to the repo -- the purpose of settings.py as opposed to settings_dev.py is to store things that shouldn't be in source control.

**Comment by rebeccacremona** [comment]
I think I worked out the assorted (3) reasons it appeared to a few people that you needed a settings.py to run Perma: you are right, we actually don't. Writing new docs/fixing up in my python3 branch.
