### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-7O9F0E/mysql-python/

### ISSUE THREAD

**Issue by SykesStudio** [harvard-lil/perma#2380]
When I run  pip install -r requirements.txt, I get the following:

Collecting mysql-python==1.2.5 (from -r requirements.txt (line 76))
  Using cached https://files.pythonhosted.org/packages/a5/e9/51b544da85a36a68debe7a7091f068d802fc515a3a202652828c73453cad/MySQL-python-1.2.5.zip
    Complete output from command python setup.py egg_info:
    sh: mysql_config: command not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-7O9F0E/mysql-python/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "setup_posix.py", line 43, in get_config
        libs = mysql_config("libs_r")
      File "setup_posix.py", line 25, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    EnvironmentError: mysql_config not found

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-7O9F0E/mysql-python/

Any suggestions on how to resolve this on CENTOS 7????

**Comment by rebeccacremona** [comment]
Hmm. I've never tried installing Perma on Centos, but first instinct is that mysql is not installed on your system, or something is amiss with your installation. Here's a similar discussion on StackOverflow that you might find helpful. https://stackoverflow.com/questions/5178292/pip-install-mysql-python-fails-with-environmenterror-mysql-config-not-found#5178698

**Comment by rebeccacremona** [comment]
Closed: presumed resolved.
