### ISSUE TITLE
Memento creation response has is_private set to false for noarchive sites

### ISSUE THREAD

**Issue by grantat** [harvard-lil/perma#2410]
Hello,

I found that when archiving a site with a `noarchive` meta tag, such as https://www.nytimes.com/2018/06/28/us/politics/trump-supreme-court-kennedy.html, the JSON response for the memento created has the key "is_private" set to false. 

A sample request:

```shell
$ curl -H 'Content-Type: application/json' -X POST -d '{"url": "https://www.nytimes.com/2018/06/28/us/politics/trump-supreme-court-kennedy.html"}' https://api.perma.cc/v1/archives/?api_key=your-api-key
```

snippet of the response:

```shell
{
   ...
    "is_private": false,
    "private_reason": null,
    "user_deleted": false,
    "archive_timestamp": "2018-06-29T20:24:34.431658Z",
    "organization": null
}
```

However, when I request memento details after creation it returns "is_private" = true:

```shell
{
   ...
    "is_private": true,
    "private_reason": "policy",
    "user_deleted": false,
    "archive_timestamp": "2018-06-29T20:24:34Z",
    "organization": null
}
```

Is there a way to wait for the capture of these details or is the best bet just stick with the chain of requests?

**Comment by rebeccacremona** [comment]
My apologies that we never replied to this question.

In case you are still using the Perma API, here's what was happening:

When you POST a request to create a Perma Link, the `Link` object is created immediately; you are returned the JSON with the GUID etc. immediately. At that moment, unless you yourself requested that the Perma Link be private, it is in fact public, the default. Your request is then placed on a queue and processed asynchronously, which, depending on a number of factors, may take some time. During that asynchronous capture process, the target site is retrieved and we check to see if the site explicitly requests that Perma.cc not display public archives of its contents. If we detect that it has, we toggle the Perma Link to private, in that moment. (At the time you filed this issue, the presence of a `noarchive` meta tag was sufficient to cause Perma to toggle the Perma Link to private; that is no longer the case.)

So, there is no way for us to return `False` with the response to your initial POST; a person must, indeed, wait until the capture is complete.

The best wait to know when the capture is complete is to poll the [CaptureJob API route](https://perma.cc/docs/developer#get-archive-status) with the `Link`'s GUID: requests like
```
curl -H "Authorization: ApiKey <your-key-here>" https://api.perma.cc/v1/capture_jobs/ABCD-1234/
```
will report that a given `Link`'s `CaptureJob` is one of {'pending','in_progress', 'completed','deleted','failed','invalid'}. You'll want to wait for `completed` or `failed`.
