### ISSUE TITLE
Docker-compose does not set up a complete environment

### ISSUE THREAD

**Issue by peterk** [harvard-lil/perma#2411]
I wanted to try out the docker-compose version to quickly get an environment up and running. However, the frontend does not seem to start automatically and the database looks uninitialized. Is there more documentation on how to get the environment up and running or are there plans to make the Docker setup more complete?

**Comment by rebeccacremona** [comment]
Yes! We're actually working on this right now. 

The current, experimental setup isn't polished: there's a bit of documentation here https://github.com/harvard-lil/perma/pull/2203. There's a list of aliases that help make the docker commands shorter ("Suggested Helpers") and then a short list of commands (which use those aliases) to initialize the database and startup the front end ("Up and Running"). There is a to-be-fixed bug with our default settings: for now, you also need to create a file `perma_web > perma > settings > settings.py` and add this to it: `from .deployments.settings_dev import *`

Let me know if you have any trouble!

**Comment by peterk** [comment]
Great! Created a fresh install and following #2203 it is necessary to do a 

`docker-compose exec web python manage.py migrate`

...before starting the webserver. After that the GUI will come online and user registration will work. Checking archiving now.

**Comment by rebeccacremona** [comment]
The migrations are run as part of `dfab dev.create_db` https://github.com/harvard-lil/perma/blob/develop/perma_web/fabfile/dev.py#L144

**Comment by peterk** [comment]
Posting a URL for archiving yields an internal server error (500) that isn't shown in the docker-compose logs unfortunately. Maybe the error log is written somewhere else? Will try to dig more tomorrow.

**Comment by rebeccacremona** [comment]
Presuming you are running with the default settings (DEBUG=True), you'll be able to see Django's error page by looking at the response in your browser's developer tools, via the "Network" tab. 

I did not mention this, from our regular installation docs:
```
Perma serves content at several hosts. To ensure that URLs resolve correctly,
add the following domains to your computer's hosts file:

    127.0.0.1 perma.test api.perma.test perma-archives.test
```

If that does not fix your problem, and if you have created `settings.py`, based on the above discussion, I'd recommend deleting your database volume (`docker-compose down`, `docker volume rm perma_db_data`) and creating new DBs using the dfab command.

This should be smoother soon!

**Comment by peterk** [comment]
Found the error. For some reason the second database (for CDX data) was never created. Cleaned up database volume and reinstalled and now everything works. Thank you!

**Comment by rebeccacremona** [comment]
@peterk we just moved to python 3, and in the process, overhauled our setup. We accordingly updated the [installation docs](https://github.com/harvard-lil/perma/blob/develop/install.md) and added instructions for [common tasks and commands](https://github.com/harvard-lil/perma/blob/develop/developer.md#common-tasks-and-commands). 

It's still a work in progress, but should be smoother than what you experienced!
