### ISSUE TITLE
django_extensions in Dockerland

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/perma#2414]
Investigate whether this still applies: https://github.com/harvard-lil/perma/blob/develop/perma_web/fabfile/dev.py#L46

**Comment by jcushman** [comment]
I tried out removing `--reloader-type stat` so runserver_plus uses the inotify reloader. Right now it works and starts reloading right away, but *finishing* reloading takes like 15 seconds longer. So I think it's still preferable to use `--reloader-type stat`.
