### ISSUE TITLE
Capturing Youtube pages works poorly

### ISSUE THREAD

**Issue by peterk** [harvard-lil/perma#2429]
Youtube pages are not captured properly. E.g. trying [this page](https://www.youtube.com/watch?v=9wU683lci64) yields results like below.

Capture:
![perma_yt_1](https://user-images.githubusercontent.com/19284/43627589-4781bd88-96f7-11e8-8185-0deb9053d01c.jpg)

Captured screenshot:
![image](https://user-images.githubusercontent.com/19284/43627538-14834e7e-96f7-11e8-989c-88ada20287fb.png)

I guess this may be because of limitiations in phantomjs. Are there any plans to switch to Chrome headless instead?

**Comment by rebeccacremona** [comment]
Yes, I think this is phantomjs showing its age. I occasionally get the more-informative screenshot below:

<img width="642" alt="screen shot 2018-08-03 at 1 07 58 pm" src="https://user-images.githubusercontent.com/11020492/43655925-8d46f082-971e-11e8-8853-d9adb8ed5ce7.png">

We've been wanting to switch to headless Firefox or headless Chrome for a long time; our latest attempt got close but ran aground. We're planning to replace our whole capture engine this year (!), which will include getting access to more modern browsers for use during capture. But if that seems to be taking longer than expected, I can easily believe we'll make another push this autumn to get the Firefox/Chrome code working.
