### ISSUE TITLE
Why not provide image download

### ISSUE THREAD

**Issue by tetsaicn** [harvard-lil/perma#2430]
Must now be built using dockerfile,It's not easy to use, it's more inconvenient,if you upload image to docker hub,just download and use,but now building very bad,stuck stuck and stuck,few minutes? few hours & many restart and not working.

**Comment by rebeccacremona** [comment]
Hi. That sounds frustrating. I can't reproduce the problem: I just built the image fresh twice with no difficulties. Maybe there was a networking problem?

**Comment by tetsaicn** [comment]
@rebeccacremona  sure,problem is networking,but if you upload it to docker hub,it's will fast and easy.
I have successfully built, I plan to upload image to docker hub.
