### ISSUE TITLE
Replacing a capture gets "Link not found", which is then cached

### ISSUE THREAD

**Issue by bensteinberg** [harvard-lil/perma#2435]
When you upload an image to replace a capture, the page tries to load it before the upload is complete, so you get a 404 from perma-archives.org, which Cloudflare then caches. We should not try to get the archive immediately, or we shouldn't cache it in this situation.

(I thought we had an issue about this already, but couldn't find one.)

**Comment by rebeccacremona** [comment]
Here's where we issue the PATCH and refresh the page: https://github.com/harvard-lil/perma/blob/develop/perma_web/static/js/single-link-permissions.module.js#L82

We refresh on `.done`; that doesn't seem too early, but I'll dig in, and will also investigate whether we can set an appropriate cookie at `perma-archives.org` for users logged in at `perma.cc` without ruining everything.

**Comment by rebeccacremona** [comment]
`.done` does wait until the Promise is resolved. https://api.jquery.com/deferred.done/

We call `link.write_uploaded_file(uploaded_file, cache_break=True)` and `link.clear_cache()` in the PATCH api route. We use the usual `default_storage.store_file(out, destination, overwrite=True)` to save the new warc, as during the normal capture process, via the same utility. I wonder if the S3 save function is async...

**Comment by rebeccacremona** [comment]
The file is uploaded to S3 via https://github.com/jschneier/django-storages/blob/master/storages/backends/s3boto3.py#L513, where `obj` is a bucket. In boto3, with the default config, uploads take place via threads (https://boto3.readthedocs.io/en/latest/reference/services/s3.html#S3.Client.upload_fileobj and https://boto3.readthedocs.io/en/latest/reference/customizations/s3.html#boto3.s3.transfer.TransferConfig), via a `concurrent.futures.ThreadPoolExecutor`, but `future.result()` is called (https://docs.python.org/3.5/library/concurrent.futures.html#concurrent.futures.Future.result). So the perma api call shouldn't be returning until the file is done uploading. (Linking to the most recent version of boto3, but I confirmed that the code in our virtualenv works the same way).

**Comment by rebeccacremona** [comment]
(I don't totally get the relationship between these boto3 methods and boto3's `Object` object, but it doesn't look like there's any move to rewrite/alter that method anywhere)

**Comment by rebeccacremona** [comment]
This doesn't feel like a fruitful path.... just to see, I can add a sleep of say 45s on the js side before the page reload, push to perma-dev, and see if that makes a difference. Can't test locally, of course, since this is a perma-cloudflare-s3 interaction.

**Comment by rebeccacremona** [comment]
Wait why can't I reproduce this right now on perma-dev?

**Comment by rebeccacremona** [comment]
Or on stage.

**Comment by rebeccacremona** [comment]
Okay, still happening on prod...... This is bizarre.......

**Comment by rebeccacremona** [comment]
Here's the other weird thing about this..... Cloudflare is set to cache things for an hour. When this 404 situation occurs, it resolves MUCH faster than that.

**Comment by rebeccacremona** [comment]
Okay wait..... right now I have this link 404ing in one logged in window, and returning well in another, and the iframes have different targets:
```
<iframe class="archive-iframe" src="//perma-archives.org/warc/GM66-2JMU/id_/file:///GM66-2JMU/upload.gif?version=049011718852240727" sandbox="allow-forms allow-scripts allow-top-navigation allow-same-origin">
        </iframe>

<iframe class="archive-iframe" src="//perma-archives.org/warc/GM66-2JMU/id_/file:///GM66-2JMU/upload.png?version=02350027464470379" sandbox="allow-forms allow-scripts allow-top-navigation allow-same-origin">
</iframe>
```

**Comment by rebeccacremona** [comment]
Okay..... 
```
    def clear_cache(self):
        cache.delete(Link.get_cdx_cache_key(self.guid))
        cache.delete(Link.get_warc_cache_key(self.warc_storage_file()))
```
This isn't going to clear all the caches, across multiple minions. Also, API minions are making the call the clear the cache, but the relevant cache for playback is on the playback minions.

**Comment by rebeccacremona** [comment]
Fantastic: I can reproduce this locally by:
1) Using redis (toggling on in docker-compose, adding settings to settings.py)
2) Commenting out the line in the api PATCH method that clears the redis cache (https://github.com/harvard-lil/perma/blob/develop/perma_web/api/views.py#L485)
3) Making a new capture, waiting until it loads.
4) Replace the capture with an uploaded screenshot -> 404
5) Pop into the django shell in another terminal tab
6) Retrieve the link, and run `l.clear_cache()`
7) Refresh the browser tab, and now the upload is found and displays.

So! Possible solutions:
- instead of every minion running its own redis, we use one hosted redis like https://aws.amazon.com/elasticache/redis/ for all of Perma, or, at least, all the application minions and all the playback minions
- we work out some mechanism for instructing all minions, or all minions of a particular type, to clear their caches

TBD

**Comment by bensteinberg** [comment]
In possible solution number 2, are you saying that on every replacement we should flush all redis caches?

**Comment by rebeccacremona** [comment]
No: on replacement, run something like (https://github.com/harvard-lil/perma/blob/develop/perma_web/api/views.py#L485 => https://github.com/harvard-lil/perma/blob/develop/perma_web/perma/models.py#L1182) against all caches.

Here's the AWS giant redis in the sky offering: https://aws.amazon.com/elasticache/redis/

**Comment by bensteinberg** [comment]
Solved, with possibility number 1, by pointing the application at a single Redis cache.
