### ISSUE TITLE
Prevent out-of-office responses to info@perma

### ISSUE THREAD

**Issue by jcushman** [harvard-lil/perma#2440]
I wonder if it would work just to switch to using a Mailgun mailing list instead of Route. Alternatively we could find some way to add an `Auto-submitted: auto-generated` or `X-Auto-Response-Suppress: OOF, DR, RN, NRN, AutoReply` header.

**Comment by bensteinberg** [comment]
A test to a test mailing list appeared to have the desired effect, so I changed info@perma.cc from a route to a mailing list. Closing, but reopen if we see or hear of more out-of-office responses.

**Comment by rebeccacremona** [comment]
I just got Brett's out-of-office message, so I think this is not yet working.

**Comment by rebeccacremona** [comment]
Resolved by changing our email-handling strategy.
