### ISSUE TITLE
Upload PDF broken

### ISSUE THREAD

**Issue by stites** [harvard-lil/perma#2443]
(c/p'd an issue template for this)

- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
As the title says, the "Upload PDF" which is only available in the first 24h, seems broken.

### Steps to reproduce
- go to example.com
- with browser, print as PDF: "example.pdf"
- log into perma account
- enter "https://example.com/" in "Create Perma Link" and press button to create
- at redirect archive page, press "Show record details"
- under "Upload file*" section, click "browse" and insert "example.pdf"
- click "Upload" 

**Expected result:** Page refreshes with "example.pdf" as the main content
**Actual result:** Main content is "Link not found"

### Screenshots
Before upload (at link https://perma.cc/C2HT-ZVQM ):
![perma-bug-1](https://user-images.githubusercontent.com/1694705/43910623-528960fe-9bcb-11e8-815a-96c55d78ea56.png)

After upload (at link https://perma.cc/C2HT-ZVQM ):
![perma-bug-2](https://user-images.githubusercontent.com/1694705/43910678-79fe8ae2-9bcb-11e8-8833-5919c99e9760.png)

**Comment by rebeccacremona** [comment]
Thanks for the detailed report!! 

This is actually: https://github.com/harvard-lil/perma/issues/2435. It's a Cloudflare caching issue: your replacement PDF is actually there. If you check back later, the link will be fine. We're actively working on a solution.

**Comment by stites** [comment]
Perfect -- thank you!

**Comment by rebeccacremona** [comment]
@stites This should be working now. Don't hesitate to let us know if you encounter any further weirdness!
