### ISSUE TITLE
Weekly report of URLs that fail to capture

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/perma#2454]
Or a field in CaptureJob for indicating that the reason for a failure has been diagnosed

**Comment by bjohnson747** [comment]
One user particularly interested in seattletimes.com - my capture attempts generally (though not always) succeeded on seattletimes articles, but frequently 'capture failed' on the seattletimes.com homepage.

**Comment by bjohnson747** [comment]
-marketwatch.com fails capture (in my tests, per Perma admin, it stopped at 'taking screenshot')
