### ISSUE TITLE
URIs of the form https://perma-archives.org/warc/YYYYMMDDHHMMSS/{URI-R} not working?

### ISSUE THREAD

**Issue by phonedude** [harvard-lil/perma#2458]
I'm seeing this with all URIs of this form, but here's an example:

curl -I https://perma.cc/S3FJ-NKZG
HTTP/1.1 200 OK
Date: Sat, 18 Aug 2018 04:33:42 GMT
Content-Type: text/html; charset=utf-8
Connection: keep-alive
Set-Cookie: __cfduid=da187c0d0b2be01a95d203516f21f9d9a1534566822; expires=Sun, 18-Aug-19 04:33:42 GMT; path=/; domain=.perma.cc; HttpOnly; Secure
Memento-Datetime: Sun, 30 Aug 2015 17:16:22 GMT
Link: <http://papers.ssrn.com/sol3/papers.cfm?abstract_id=1639996>; rel="original"; datetime="Sun, 30 Aug 2015 17:16:22 GMT",<https://perma.cc/S3FJ-NKZG>; rel="memento"; datetime="Sun, 30 Aug 2015 17:16:22 GMT",<https://perma-archives.org/warc/timegate/http://papers.ssrn.com/sol3/papers.cfm?abstract_id=1639996>; rel="timegate",<https://perma-archives.org/warc/timemap/*/http://papers.ssrn.com/sol3/papers.cfm?abstract_id=1639996>; rel="timemap"; type="application/link-format"
Vary: Cookie, Host
Cache-Control: public, max-age=3600
Strict-Transport-Security: max-age=15768000
CF-Cache-Status: EXPIRED
Expires: Sat, 18 Aug 2018 05:33:42 GMT
Set-Cookie: __cflb=2623844457; path=/; expires=Sun, 19-Aug-18 03:33:42 GMT
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
CF-RAY: 44c1a9f11b1857a1-IAD

and then when hitting the TimeGate:

curl -IL "https://perma-archives.org/warc/timegate/http://papers.ssrn.com/sol3/papers.cfm?abstract_id=1639996"
HTTP/1.1 302 Found
Date: Sat, 18 Aug 2018 04:20:19 GMT
Connection: keep-alive
Set-Cookie: __cfduid=db138a9d5d13a01cc9638c2580a7a337d1534566019; expires=Sun, 18-Aug-19 04:20:19 GMT; path=/; domain=.perma-archives.org; HttpOnly; Secure
Location: https://perma-archives.org/warc/20150729024059/http://papers.ssrn.com/sol3/papers.cfm?abstract_id=1639996
Cache-Control: max-age=0
Vary: accept-datetime
Link: <https://perma-archives.org/warc/20150729024059/http://papers.ssrn.com/sol3/papers.cfm?abstract_id=1639996>; rel="memento"; datetime="Wed, 29 Jul 2015 02:40:59 GMT", <http://papers.ssrn.com/sol3/papers.cfm?abstract_id=1639996>; rel="original", <https://perma-archives.org/warc/timemap/*/http://papers.ssrn.com/sol3/papers.cfm?abstract_id=1639996>; rel="timemap"; type="application/link-format"
Strict-Transport-Security: max-age=15768000
Set-Cookie: __cflb=477376694; path=/; expires=Sun, 19-Aug-18 03:20:19 GMT
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
CF-RAY: 44c19652ca3123f6-IAD

HTTP/1.1 503 Service Unavailable
Date: Sat, 18 Aug 2018 04:20:19 GMT
Content-Type: text/html; charset=utf-8
Connection: keep-alive
Set-Cookie: __cfduid=db138a9d5d13a01cc9638c2580a7a337d1534566019; expires=Sun, 18-Aug-19 04:20:19 GMT; path=/; domain=.perma-archives.org; HttpOnly; Secure
CF-Cache-Status: MISS
Set-Cookie: __cflb=477376694; path=/; expires=Sun, 19-Aug-18 03:20:19 GMT
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
CF-RAY: 44c196533a5223f6-IAD

![image](https://user-images.githubusercontent.com/5322165/44295781-fb911080-a27d-11e8-8ffd-9b13155aefb8.png)

text = 

Playback Unavailable

We’re having trouble playing back this record’s Capture View. If this problem persists, please let us know.

Error message: warcs/TP/6A/56/TP6A-56RF.warc.gz: 403 Client Error: Forbidden for url: https://perma.s3.amazonaws.com/generated/warcs/TP/6A/56/TP6A-56RF.warc.gz

earlier I was also having problems with TimeMaps, but I can't replicate it now:

curl -iL "https://perma-archives.org/warc/timemap/*/http://papers.ssrn.com/sol3/papers.cfm?abstract_id=1639996"
HTTP/1.1 200 OK
Date: Sat, 18 Aug 2018 04:36:52 GMT
Content-Type: application/link-format; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Set-Cookie: __cfduid=d27a0e7dcd7f9903ab603c2daab8e3c1d1534567012; expires=Sun, 18-Aug-19 04:36:52 GMT; path=/; domain=.perma-archives.org; HttpOnly; Secure
Cache-Control: public, max-age=3600
Strict-Transport-Security: max-age=15768000
CF-Cache-Status: EXPIRED
Expires: Sat, 18 Aug 2018 05:36:52 GMT
Set-Cookie: __cflb=477376694; path=/; expires=Sun, 19-Aug-18 03:36:52 GMT
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
CF-RAY: 44c1ae92b98a9f72-IAD

<https://perma-archives.org/warc/timemap/*/http://papers.ssrn.com/sol3/papers.cfm?abstract_id=1639996>; rel="self"; type="application/link-format"; from="Wed, 29 Jul 2015 02:40:59 GMT",
<http://papers.ssrn.com/sol3/papers.cfm?abstract_id=1639996>; rel="original",
<https://perma-archives.org/warc/timegate/http://papers.ssrn.com/sol3/papers.cfm?abstract_id=1639996>; rel="timegate",
<https://perma-archives.org/warc/20150729024059/http://papers.ssrn.com/sol3/papers.cfm?abstract_id=1639996>; rel="memento"; datetime="Wed, 29 Jul 2015 02:40:59 GMT",

**Comment by rebeccacremona** [comment]
Yes! We accidentally broke this during a recent security update. We have a fix in our next release, which should actually be going live later today.

Thanks for the report!

(related https://github.com/harvard-lil/perma/issues/2442)

**Comment by phonedude** [comment]
ok -- thanks!  sorry I didn't see the previous issue.

**Comment by rebeccacremona** [comment]
Not at all: I closed it when we merged in the PR!

**Comment by rebeccacremona** [comment]
This should be working now: 

https://perma-archives.org/warc/*/http://lil.law.harvard.edu/
https://perma-archives.org/warc/timegate/http://lil.law.harvard.edu/
https://perma-archives.org/warc/20180806192203/https://lil.law.harvard.edu/

If you notice anything is still acting up, don't hesitate to let us know!
