### ISSUE TITLE
html view of timemaps

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/perma#2459]
1) why, on stage, is `{% url %}` not working, just for `landing`?
2) on all tiers, the html view for timemaps have broken links: they are relative links, so point at things like `https://user-content.perma-dev.org/login` and `https://user-content.perma-dev.org/about` rather than `https://perma-dev.org/login` and `https://perma-dev.org/about`
3) why do we have a special redirect in nginix config that, on prod, redirects requests when you click timemap footer links to urls like `https://perma-archives.org/warc/*/http://example.com/docs/developer`?

**Comment by rebeccacremona** [comment]
I think the solution is to get these templates to use absolute URLs, pointing to the application url

**Comment by jcushman** [comment]
Re: the nginx redirect on prod, I think that is there to catch url rewrite leaks. So the intended case is if you're playing back `/warc/1234-ABCD/http://example.com`, and it manages to leak a request to `/foo.html`, the request gets redirected to `/warc/1234-ABCD/http://example.com/foo.html`.

Agreed that the general solution is to use absolute urls.

**Comment by rebeccacremona** [comment]
Switched to absolute URLs in https://github.com/harvard-lil/perma/pull/2460, and also added a (temporary?) line to force the use of the correct urlconf when pywb is rendering templates. We still don't understand exactly why the api urlconf shows up as having been set for the thread here (https://github.com/harvard-lil/perma/blob/develop/perma_web/warc_server/pywb_config.py#L430), but I'd like to deploy the current set of fixes we have before spending too much more time investigating.

**Comment by rebeccacremona** [comment]
closing: we can investigate the urlconf situation separately.
