### ISSUE TITLE
Include styled and non-styled timemap urls + MIME type in memento "link" headers

### ISSUE THREAD

**Issue by phonedude** [harvard-lil/perma#2471]
I uncovered this in the previous issue, and it might still be related to https://github.com/harvard-lil/perma/issues/2442 and https://github.com/harvard-lil/perma/issues/2458

but when TimeMap links for URLs of the form:

https://perma-archives.org/warc/89ZB-BWVX/http://www.library.umass.edu/

don't return TimeMaps, they return HTML pages:

% curl -I https://perma-archives.org/warc/89ZB-BWVX/http://www.library.umass.edu/
HTTP/1.1 200 OK
Date: Sun, 02 Sep 2018 19:46:13 GMT
Content-Type: text/html; charset=utf-8
Content-Location: https://perma-archives.org/warc/89ZB-BWVX/http://www.library.umass.edu/
Memento-Datetime: Fri, 03 Nov 2017 21:11:50 GMT
Link: <https://perma-archives.org/warc/89ZB-BWVX/http://www.library.umass.edu/>; rel="memento"; datetime="Fri, 03 Nov 2017 21:11:50 GMT", <http://www.library.umass.edu/>; rel="original", <https://perma-archives.org/warc/*/http://www.library.umass.edu/>; rel="timemap"; type="application/link-format", <https://perma-archives.org/warc/timegate/http://www.library.umass.edu/>; rel="timegate"
[deletia]

% curl -I https://perma-archives.org/warc/*/http://www.library.umass.edu/
HTTP/1.1 200 OK
Date: Sun, 02 Sep 2018 19:48:31 GMT
Content-Type: text/html; charset=utf-8
[deletia]

perhaps I'm not supposed to see URIs like https://perma-archives.org/warc/89ZB-BWVX/http://www.library.umass.edu/ but the TimeMap link is wrong (though the TimeGate link works fine).

**Comment by rebeccacremona** [comment]
Thanks! I'm afraid I don't understand.

In Perma's current setup, links of the form https://perma-archives.org/warc/89ZB-BWVX/http://www.library.umass.edu/ are for a specific memento within a single warc (89ZB-BWVX). 

Links of the form https://perma-archives.org/warc/*/http://www.library.umass.edu/ deliver a styled html page with timemap info; links of the form https://perma-archives.org/warc/timemap/*/http://www.library.umass.edu/ deliver an unstyled timemap payload. Links of the form https://perma-archives.org/warc/timegate/http://www.library.umass.edu/ redirect to the most recent memento we have for a given URL, including the timestamp in the URL.

I think my description above matches the contents of the "Link" header from your above: 

```
Link: 
https://perma-archives.org/warc/89ZB-BWVX/http://www.library.umass.edu/; rel="memento"; 

http://www.library.umass.edu/; rel="original", 

https://perma-archives.org/warc/*/http://www.library.umass.edu/; rel="timemap"; 

https://perma-archives.org/warc/timegate/http://www.library.umass.edu/; rel="timegate"
```

I'm not particularly knowledgeable about the memento protocol: does that meet expectations?

**Comment by rebeccacremona** [comment]
Ah, having written all that out: would it be more standard/ better for you if instead of `https://perma-archives.org/warc/*/http://www.library.umass.edu/; rel="timemap"; `, which points to the styled version, we listed `https://perma-archives.org/warc/timemap/*/http://www.library.umass.edu/; rel="timemap"; `, the unstyled version?

**Comment by phonedude** [comment]
Hi Rebecca,

Yes, the rel="timemap" without a MIME type is assumed to point to the application/link-format type. one way to specify different kinds of TimeMaps is to use different MIME types, like:

curl --silent memgator.cs.odu.edu/timemap/link/www.cs.odu.edu/~mln/ | tail -5
<http://web.archive.org/web/20180901214847/http://www.cs.odu.edu/%7Emln/>; rel="last memento"; datetime="Sat, 01 Sep 2018 21:48:47 GMT",
<https://memgator.cs.odu.edu/timemap/link/http://www.cs.odu.edu/~mln/>; rel="timemap"; type="application/link-format",
<https://memgator.cs.odu.edu/timemap/json/http://www.cs.odu.edu/~mln/>; rel="timemap"; type="application/json",
<https://memgator.cs.odu.edu/timemap/cdxj/http://www.cs.odu.edu/~mln/>; rel="timemap"; type="application/cdxj+ors",
<https://memgator.cs.odu.edu/timegate/http://www.cs.odu.edu/~mln/>; rel="timegate"

you could list the styled version with type="text/html"

**Comment by rebeccacremona** [comment]
Fixed in https://github.com/harvard-lil/perma/pull/2699
