### ISSUE TITLE
Overhaul bookmarklet

### ISSUE THREAD

**Issue by bensteinberg** [harvard-lil/perma#2543]
It looks for www.perma.cc, which is no longer extant.

**Comment by bjohnson747** [comment]
Got question from a user attempting to use this - I tested (freshly added from the Tools menu) both Chrome and Firefox - in both cases, it returned a 522 error:

<img width="1054" alt="Screen Shot 2019-07-25 at 4 14 21 PM" src="https://user-images.githubusercontent.com/12850389/61905982-599b8e80-aef8-11e9-8918-388236cc55e9.png">
