### ISSUE TITLE
Cookie problem

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/perma#2568]
https://www.ncea.org/NCEA/Proclaim/Catholic_School_Data/NCEA/Proclaim/Catholic_School_Data/Catholic_School_Data.aspx wants a tracking cookie. During playback, that's failing, and so it's trying to redirect to https://www.ncea.org/NoCookies.html, which does not appear in the archive, so the user gets a 404.

Same problem with pywb and WR playback. Production WR doesn't seem to have a problem. Something about our iframe?

**Comment by abziegler** [comment]
Not sure if this is same issue, but here's another that wants to place a cookie https://perma.cc/9DD5-SZ8U, and when it doesn't get to it redirects to "authorize cookies" page and then playback eventually seems to timeout

**Comment by matteocargnelutti** [comment]
Happy to report that client-side playback solves this problem! 
Tested both archives mentioned above (`6QHG-P49H`, `9DD5-SZ8U`), was able to play them back 🎉 .
