### ISSUE TITLE
Subscription Info in Perma Admin

### ISSUE THREAD

**Issue by clare-stanton** [harvard-lil/perma#2570]
In order to more easily track subscription trends, it would be nice to expose some more info on the list view in the admin console on perma.cc. 

In the list view of Users add: 

Cached Subscription Rate
Link Limit 

and if possible: 

Creation Date (of subscription, not Perma account)

**Comment by rebeccacremona** [comment]
Can do! 

For creation date: do want to know when the person first exited their trial? Or when their most recent subscription started? (Not sure we have any repeat customers yet, but just supposing we do.) The start date of their most recent subscription is easier, but no reason I can't start storing the other one.

**Comment by clare-stanton** [comment]
I suppose most recent subscription - long term even I think that'd be better for tracking month to month. Thanks!
