### ISSUE TITLE
Monitor changes to pywb's Dockerfile

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/perma#2586]
It occurs: we should probably also be watching for changes to pywb's Dockerfile, since it is the base of Webrecorder's Dockefile, which we are customizing.....

**Comment by bensteinberg** [comment]
I may have set up a notifier.

**Comment by rebeccacremona** [comment]
For now, I'll check every Monday to see if it's been updated. I'll close this issue the first time we see the notifier work.
