### ISSUE TITLE
no warc download button for some Perma Links

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/perma#2616]
like https://perma.cc/0upUSSNF7rH (which is broken; see https://github.com/harvard-lil/perma/issues/1792)

**Comment by bensteinberg** [comment]
This link has no `warc_size`: see https://github.com/harvard-lil/perma/blob/8c365dc9c1470e1408dd2a6dc459b0f1d4818e59/perma_web/perma/templates/archive/single-link.html#L192
