### ISSUE TITLE
Update to pywb 2.3.1

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/perma#2651]
To get this fix https://github.com/webrecorder/pywb/issues/474

We should be able to remove our workaround at the same time.

We'll have to check out the Webrecorder Dockerfile and pywb Dockerhub situation... so far as I know, they are still building from develop, instead of a pinned release... might be worth reaching out to ask why.

**Comment by bensteinberg** [comment]
I believe this can be closed?

**Comment by rebeccacremona** [comment]
I don't think so. I think we're still using pywb develop from 5/21/19: https://github.com/harvard-lil/webrecorder/blob/perma/perma/webrecorder/Dockerfile#L2
