### ISSUE TITLE
status.perma.cc and maintenance page

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/perma#2652]
During recent excitement, a user inquired, "Please advise why your status says you are up and you are down. thank you." Let's consider making status.perma.cc savvy to our maintenance status.

**Comment by rebeccacremona** [comment]
FWIW: I just visited status.perma.cc and status.perma.cc/monitor during a deployment, and saw the maintenance page as expected.

So, this issue is not about events where the maintenance page is up, but rather, is about true outages.

**Comment by bensteinberg** [comment]
I believe the way this should work is that the status page should be visible during deployment, not masked by the maintenance page, and that the deployment process should update the message on the status page. I think I have this all set up correctly now, but will wait to close this until we can check it during our next production deployment.

**Comment by bensteinberg** [comment]
By the way, the code that makes the status page is now at https://github.com/harvard-lil/perma-status

**Comment by bensteinberg** [comment]
This works now.
