### ISSUE TITLE
Playback redirect loop

### ISSUE THREAD

**Issue by clare-stanton** [harvard-lil/perma#2667]
https://hlslil.freshdesk.com/a/tickets/7054
https://hlslil.freshdesk.com/a/tickets/7002

**Comment by bjohnson747** [comment]
issue link: https://americanarchivist.org/doi/pdf/10.17723/aarc.75.2.c53274126p37p074

**Comment by matteocargnelutti** [comment]
Cannot reproduce this issue with client-side playback 🥳 .
