### ISSUE TITLE
Sandboxed iframes?

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/perma#2688]
`Capture.use_sandbox` remakes:
```
    def use_sandbox(self):
        """
            Whether the iframe we use to display this capture should be sandboxed.
            Answer is yes unless we're playing back a PDF, which currently can't
            be sandboxed in Chrome.
```
Still true?

**Comment by rebeccacremona** [comment]
Yep, still true. Safari as well. And..... our workaround doesn't cover situations like https://perma.cc/K56C-SVUX

**Comment by matteocargnelutti** [comment]
This is a browser limitation. Chrome behaves differently than Firefox in that context. Unfortunately not much we can do about it.
