### ISSUE TITLE
Look for py2/3 remarks

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/perma#2690]
We are now solidly in python 3.
Look for and clean up any things like:
```
    # In Python 3: def __str__(self):
    def __unicode__(self):
        return u"LinkBatch %s" % (self.pk,)
```

**Comment by matteocargnelutti** [comment]
I would consider the following out of scope for this issue: https://github.com/harvard-lil/perma/blob/develop/perma_web/perma/templatetags/current_query_string.py#L17 

Closing.
