### ISSUE TITLE
Check up on browser extensions

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/perma#2693]
Let's verify that our browser extensions still install and work.

**Comment by matteocargnelutti** [comment]
> Let's verify that our browser extensions still install and work.

They do 😃.

The Chrome one is on Manifest v2, which is deprecated, and will be automatically deactivated in January 2023 (https://developer.chrome.com/docs/extensions/mv3/mv2-sunset/) 

<img width="728" alt="Screen Shot 2022-07-29 at 6 10 16 PM" src="https://user-images.githubusercontent.com/625889/181851793-212e4f9c-aa0a-4b0e-bd67-a579c664dc21.png">

Mixed signals on the Firefox front, as they are moving towards manifest v3:  https://blog.mozilla.org/addons/2022/05/18/manifest-v3-in-firefox-recap-next-steps/ 

Closing and moving discussions about upcoming releases to https://github.com/harvard-lil/perma-extension
