### ISSUE TITLE
warcprox_controller = None?

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/perma#2731]
We just got a flurry of these during teardown:
```
Traceback: 

File "/usr/local/share/perma/perma_web/perma/tasks.py" in run_next_capture
  1299.             teardown(link, thread_list, browser, display, warcprox_controller, warcprox_thread)

File "/usr/local/share/perma/perma_web/perma/tasks.py" in teardown
  769.         warcprox_controller.warc_writer_processor.writer_pool.close_writers()  # blocking

AttributeError
'NoneType' object has no attribute 'warc_writer_processor'
```
The code in question is:
```
    if warcprox.controller:
        warcprox_controller.warc_writer_processor.writer_pool.close_writers()  # blocking
```

I think that's a bug: `warcprox.controller` vs. `warcprox_controller`

**Comment by rebeccacremona** [comment]
We just got several more of these, even though this fix was deployed over an hour ago:
```
    if warcprox_controller:
        warcprox_controller.warc_writer_processor.writer_pool.close_writers()  # blocking
```
I don't understand at all. `warcprox_controller = WarcproxController(options)`. I see no code that could set it to None.

However... I believe that every time we've seen this error, the capture job says:
```
status: deleted
superseded: true
Step count: 0.0
Step description: Starting capture
```

See related https://github.com/harvard-lil/perma/issues/2729.

What are these users up to? I see the URLs are often for paywalled/authed resources... maybe quickly deleting, immediately after hitting go, is a shortcut people have figured out for getting to the upload form?

**Comment by bensteinberg** [comment]
Note that at least some of these errors were down to a deployment problem, so maybe ok to close?
