### ISSUE TITLE
Buzzfeed URL consistently eats all RAM on the server...

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/perma#2788]
...and hard-times out. Look into that. Hopefully without eating all the RAM on your laptop.

https://www.buzzfeed.com/karthikshankar/why-i-published-a-list-of-sexual-predators-in-academia?bffbdialogue.

**Comment by matteocargnelutti** [comment]
No longer an issue with that specific url (tested Aug 10 2022)
