### ISSUE TITLE
Safari and playback

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/perma#2801]
1) Aw, snap: https://perma-stage.org/2UP4-2YXY
2) images missing: https://www.courier-journal.com/kentucky-derby/

**Comment by matteocargnelutti** [comment]
<img width="563" alt="Screen Shot 2022-08-05 at 11 45 06 AM" src="https://user-images.githubusercontent.com/625889/183113325-78770afe-af1f-4555-9311-9c4b36521c96.png">
