### ISSUE TITLE
Warc not found

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/perma#2804]
I'm concerned I might have broken https://github.com/harvard-lil/perma/pull/2761 in https://github.com/harvard-lil/perma/pull/2796....

Last night, we got another:
Exception Type: OSError at /GUID
Exception Value: File does not exist: generated/warcs/......warc.gz

Which we haven't been getting, and it was not accompanied by an email from the retry code.

I don't see how I could have broken it, and have tested locally.... but am suspicious.

**Comment by matteocargnelutti** [comment]
No signal in logs over the past two years
