### ISSUE TITLE
Mementos with long form URIs return HTTP 404? How to discover their short form URIs?

### ISSUE THREAD

**Issue by maturban** [harvard-lil/perma#2814]
I am aware of some changes you made in how Perma WARCs are replayed ([https://github.com/harvard-lil/perma/pull/2699](https://github.com/harvard-lil/perma/pull/2699)). For example, you are now using `perma.cc` instead of `perma-archives.org` for links to TimeGates, TimeMaps, and others.
 
I have a set of URIs of the form `https://perma-archives.org/warc/YYYYMMDDHHMMSS/{URI-R}` (e.g.,http://perma-archives.org/warc/20170921154658/https://csrc.nist.gov/), but these URIs now return `404`.

For example, when requesting http://perma-archives.org/warc/20170921154658/https://csrc.nist.gov/, the redirect points to https://perma.cc/timemap/html/, which returns an `HTTP 404` (see **Example 1** below).
 
But in January 2019, the same URI redirected to https://perma-archives.org/warc/20170921154658/https://csrc.nist.gov/ which resolved as a `HTTP 200` (see **Example 2**).
 
I also tried to use TimeMaps to find the corresponding short form URIs (i.e.,  `https://perma.cc/AAAA-AAAA`), with no success. For example, for the URI http://perma-archives.org/warc/20170921154658/https://csrc.nist.gov/, I downloaded the TimeMap of https://csrc.nist.gov/ (using https://perma.cc/timemap/link/https://csrc.nist.gov/), but the results show that the earliest memento is now from 2019 (see **Example 3**)

In some cases, we get empty TimeMaps, which means we no longer have access to any archived versions of those pages (see **Examples 4 & 5** below).  We discovered 18 such cases.

**So I have two questions:**
(1) Does Perma.cc still use the long form URIs (i.e., `https://perma-archives.org/warc/YYYYMMDDHHMMSS/{URI-R}`) in addition to the short URIs (e.g., `https://perma.cc/AAAA-AAAA`)?
(2) If not, how can I find the corresponding short form URIs to the set of long form URIs that I have?

**Here are some curl sessions and examples, if needed:**

**Example (1)**: The URI http://perma-archives.org/warc/20170921154658/https://csrc.nist.gov/ currently returns `HTTP 404`

```
$ curl -IL http://perma-archives.org/warc/20170921154658/https://csrc.nist.gov/
HTTP/1.1 301 Moved Permanently
Date: Mon, 30 Mar 2020 20:32:48 GMT
Connection: keep-alive
Cache-Control: max-age=3600
Expires: Mon, 30 Mar 2020 21:32:48 GMT
Location: https://perma.cc/timemap/html/
Server: cloudflare
CF-RAY: 57c49a206f2be0f2-IAD
 
HTTP/2 404 
date: Mon, 30 Mar 2020 20:32:48 GMT
content-type: text/html; charset=utf-8
set-cookie: __cfduid=d767b922343bc90efcff9a9284afbc0651585600368; expires=Wed, 29-Apr-20 20:32:48 GMT; path=/;
domain=.perma.cc; HttpOnly; SameSite=Lax; Secure
vary: Cookie, Host
cf-cache-status: EXPIRED
expires: Mon, 30 Mar 2020 21:32:48 GMT
cache-control: public, max-age=3600
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
set-cookie: __cflb=0H28vJJdLkHc3TMWPG8Cy4vT7tg7Bz3agq3uGe3Zvep; Secure; SameSite=None; path=/; expires=Tue,
31-Mar-20 19:32:48 GMT; HttpOnly
server: cloudflare
cf-ray: 57c49a213e0573f1-IAD
```

**Example (2)**: http://perma-archives.org/warc/20170921154658/https://csrc.nist.gov/ was `200 OK` in January 2019:

```
WARC/1.0
WARC-Type: response
WARC-Target-URI: http://perma-archives.org/warc/20170921154658/https://csrc.nist.gov/
WARC-Date: 2019-01-13T20:00:52Z
WARC-Record-ID: <urn:uuid:ee0ec410-176d-11e9-8bd1-a5dd2bf8919f>
Content-Type: application/http; msgtype=response
Content-Length: 442
 
HTTP/1.1 301 Moved Permanently
Date: Sun, 13 Jan 2019 19:59:40 GMT
Server: cloudflare
Vary: Accept-Encoding
Location: https://perma-archives.org/warc/20170921154658/https://csrc.nist.gov/
Set-Cookie: __cflb=2607265279; Secure; path=/; expires=Mon, 14-Jan-19 18:59:40 GMT; HttpOnly
Cache-Control: max-age=3600
Transfer-Encoding: chunked
Connection: keep-alive
CF-RAY: 498a71d7c5669586-IAD
Expires: Sun, 13 Jan 2019 20:59:40 GMT
 
 
WARC/1.0
WARC-Type: request
WARC-Target-URI: https://perma-archives.org/warc/20170921154658/https://csrc.nist.gov/
WARC-Date: 2019-01-13T20:00:52Z
WARC-Concurrent-To: <urn:uuid:ee0a0920-176d-11e9-8bd1-a5dd2bf8919f>
WARC-Record-ID: <urn:uuid:ee0fae70-176d-11e9-8bd1-a5dd2bf8919f>
Content-Type: application/http; msgtype=request
Content-Length: 536
 
GET /warc/20170921154658/https://csrc.nist.gov/ HTTP/1.1
:path: /warc/20170921154658/https://csrc.nist.gov/
pragma: no-cache
accept-encoding: gzip, deflate
upgrade-insecure-requests: 1
user-agent: Web Science and Digital Libraries Group (@WebSciDL); Project/archives_fixity; Contact/Mohamed Aturban
(maturban@odu.edu)
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
cache-control: no-cache
:authority: perma-archives.org
:scheme: https
:method: GET
Host: perma-archives.org
 
 
WARC/1.0
WARC-Type: response
WARC-Target-URI: https://perma-archives.org/warc/20170921154658/https://csrc.nist.gov/
WARC-Date: 2019-01-13T20:00:52Z
WARC-Record-ID: <urn:uuid:ee11aa40-176d-11e9-8bd1-a5dd2bf8919f>
Content-Type: application/http; msgtype=response
Content-Length: 58084
 
HTTP/1.1 200 OK
x-archive-orig-pragma: no-cache
date: Sun, 13 Jan 2019 19:59:41 GMT
cf-cache-status: MISS
status: 200
memento-datetime: Thu, 21 Sep 2017 15:46:58 GMT
content-type: text/html; charset=utf-8
x-archive-orig-cache-control: no-cache, no-store, must-revalidate
x-archive-orig-x-ua-compatible: IE=Edge
x-archive-orig-server: Microsoft-IIS/7.5
server: cloudflare
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
vary: Accept-Encoding
strict-transport-security: max-age=15768000
x-archive-orig-strict-transport-security: max-age=31536000
expires: Sun, 13 Jan 2019 23:59:41 GMT
cache-control: public, max-age=14400
set-cookie: __cfduid=dc3349dc6d341e5e8c1ea8611e9f285331547409580; expires=Mon, 13-Jan-20 19:59:40 GMT; path=/;
domain=.perma-archives.org; HttpOnly; Secure
CMSCsrfCookie=MsBuqUgmiKSgE5RwPBYwLeIUhKkLZERTryJmyAIj; HttpOnly;
Path=/warc/20170921154658/https://csrc.nist.gov/; Secure
ASP.NET_SessionId=g51albvupce3g2mt4yy11fn1; HttpOnly; Path=/warc/20170921154658/https://csrc.nist.gov/; Secure
__cflb=886552886; Secure; path=/; expires=Mon, 14-Jan-19 18:59:41 GMT; HttpOnly
x-archive-orig-date: Thu, 21 Sep 2017 15:46:57 GMT
cf-ray: 498a71d82ef0c18b-IAD
link: <https://perma-archives.org/warc/20170921154658/https://csrc.nist.gov/>; rel="memento"; datetime="Thu, 21
Sep 2017 15:46:58 GMT", <https://csrc.nist.gov/>; rel="original",
<https://perma-archives.org/warc/timemap/*/https://csrc.nist.gov/>; rel="timemap"; type="application/link-format",
<https://perma-archives.org/warc/https://csrc.nist.gov/>; rel="timegate"
x-archive-orig-x-frame-options: SAMEORIGIN
x-archive-orig-expires: -1
x-archive-orig-Content-Length: 56362
...
```

**Example (3)**: The TimeMap of https://csrc.nist.gov/ does not contain any memento close to http://perma-archives.org/warc/20170921154658/https://csrc.nist.gov/:
 
```
curl -i https://perma.cc/timemap/link/https://csrc.nist.gov/
HTTP/2 200 
date: Mon, 30 Mar 2020 20:33:30 GMT
content-type: application/link-format
content-length: 1073
set-cookie: __cfduid=d155350c4bf9e394b1e7878c3504c83501585600410; expires=Wed, 29-Apr-20 20:33:30 GMT; path=/;
domain=.perma.cc; HttpOnly; SameSite=Lax; Secure
x-memento-count: 7
cache-control: public, max-age=3600
vary: Cookie, Host
strict-transport-security: max-age=15768000
cf-cache-status: HIT
age: 589
expires: Mon, 30 Mar 2020 21:33:30 GMT
accept-ranges: bytes
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 57c49b2848d47493-IAD
 
<https://csrc.nist.gov/>; rel=original,
<https://perma.cc/timegate/https://csrc.nist.gov/>; rel=timegate,
<https://perma.cc/timemap/link/https://csrc.nist.gov/>; rel=self; type=application/link-format,
<https://perma.cc/timemap/link/https://csrc.nist.gov/>; rel=timemap; type=application/link-format,
<https://perma.cc/timemap/json/https://csrc.nist.gov/>; rel=timemap; type=application/json,
<https://perma.cc/timemap/html/https://csrc.nist.gov/>; rel=timemap; type=text/html,
<https://perma.cc/R84B-LJWJ>; rel=memento; datetime="Thu, 13 Jun 2019 15:06:56 GMT",
<https://perma.cc/YB67-WAAA>; rel=memento; datetime="Fri, 14 Jun 2019 00:35:56 GMT",
<https://perma.cc/N76Q-GYWN>; rel=memento; datetime="Fri, 14 Jun 2019 00:38:09 GMT",
<https://perma.cc/272M-Y224>; rel=memento; datetime="Fri, 14 Jun 2019 00:42:23 GMT",
<https://perma.cc/Z5WL-42XB>; rel=memento; datetime="Fri, 14 Jun 2019 01:03:04 GMT",
<https://perma.cc/4TGM-QZL6>; rel=memento; datetime="Fri, 14 Jun 2019 01:11:06 GMT",
<https://perma.cc/3JSH-FG8G>; rel=memento; datetime="Fri, 14 Jun 2019 01:13:35 GMT",

```

**Example (4)**: We tried to download the TimeMap for https://www.tmall.com/ which returned an empty TimeMap, or an `HTTP 404`: 

```
        curl -i https://perma.cc/timemap/link/https://www.tmall.com/
        HTTP/2 404 
        date: Fri, 10 Apr 2020 14:45:06 GMT
        content-type: text/html; charset=utf-8
        set-cookie: __cfduid=d33c8b6ca83b8e59d2edfa9bc3f5657af1586529906; expires=Sun, 10-May-20 14:45:06 GMT; path=/; domain=.perma.cc; HttpOnly; SameSite=Lax; Secure
        x-memento-count: 0
        cache-control: public, max-age=3600
        vary: Cookie, Host
        cf-cache-status: HIT
        age: 16
        expires: Fri, 10 Apr 2020 15:45:06 GMT
        expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
        server: cloudflare
```

**Example (5)**: Examples of long form URIs that we were not able to find ANY short form URIs for:

    - http://perma-archives.org/warc/20170731024959/https://www.tmall.com/ 
    - http://perma-archives.org/warc/20170203233757/https://www.cms.gov/cciio/index.html 
    - http://perma-archives.org/warc/20141021173834/http://databank.worldbank.org/data/home.aspx 
    - http://perma-archives.org/warc/20151101192051/http://www.homedepot.com/ 
    - http://perma-archives.org/warc/20161118165253/https://studentloans.gov/myDirectLoan/index.action 
    - http://perma-archives.org/warc/20151009235521/http://readwrite.com/ 
    - http://perma-archives.org/warc/20160914003340/https://www.texas.gov/   
    - http://perma-archives.org/warc/20170220021805/https://www.sam.gov/portal/SAM/ 
    - http://perma-archives.org/warc/20151101193342/http://www.spiegel.de/ 
    - http://perma-archives.org/warc/20150404172754/https://www.att.com/ 
    - http://perma-archives.org/warc/20150820154813/http://ici.radio-canada.ca/ 
    - http://perma-archives.org/warc/20170925035325/https://www.dropbox.com/?landing=dbv2 
    - http://perma-archives.org/warc/20161105175946/http://www.hostgator.com/ 
    - http://perma-archives.org/warc/20150123144122/http://www.usa.gov/page-not-found   
    - http://perma-archives.org/warc/20151002194849/http://eric.ed.gov/ 
    - http://perma-archives.org/warc/20160204202605/https://www.icloud.com/ 
    - http://perma-archives.org/warc/20171003185440/https://travel.state.gov/content/travel/en/404.html 
    - http://perma-archives.org/warc/20171022230759/https://www.consumer.ftc.gov/

**Comment by rebeccacremona** [comment]
Hi! Thanks for your report and questions. 

I'll read in more detail on Monday, but in case this answers any of your questions, here is the email I sent to the memento dev list about Perma's new memento support in February. I will, again, consider this properly on Monday, but I suspect the "more details" section may be relevant. It is possible that all those URLs pointed to private Perma Links in the past, which are no longer exposed via memento, or that some-or-many of them were not the "top-level" targets of a user-initiated captures (see #2 in more details below). 

Or my code is busted, in which case I will fix it. If it's broken, this is not an area of the codebase that should be hard to fix.

Until Monday,
Rebecca

```
--------- Forwarded message ---------
From: Rebecca Cremona <rebecca.cremona@gmail.com>
Date: Wed, Feb 5, 2020 at 2:57 AM
Subject: New Memento support at Perma.cc
To: Memento Development <memento-dev@googlegroups.com>


Good evening!

Tomorrow (Weds Feb 4, 2020), Perma.cc will begin the process of deploying completely reimplemented support for timegates, timemaps, and memento-related headers on Perma Link/memento playbacks. Our timemaps, timegates, and memento-related headers have been broken since early last summer; we apologize for the frustration, and that it took us so long to address.

We expect the full re-indexing to take several hours, possibly up to a full day. During this time, Perma will initially return 404 for all timemap and timegate queries; partial results will be exposed in real time as the index is re-built. I'll post to this list again when it's complete.

Timemaps will subsequently be available at:

https://perma.cc/timemap/link/<url> (replacing https://perma-archives.org/warc/timemap/*/<url>)
https://perma.cc/timemap/json/<url> (newly available)
https://perma.cc/timemap/html/<url> (non-standard, browser-friendly format, replacing https://perma-archives.org/warc/*/<url>)

and timegates will be available at:

https://perma.cc/timegate/<url> (replacing https://perma-archives.org/warc/timegate/<url>)

We will 301 redirect from the old routes to the new ones.

More details are below, if anyone is interested or might be tripped up by our changes.

We hope this whips Perma's Memento support into shape. We've run the validator (http://mementoweb.org/tools/validator) against our staging server (https://perma-stage.org), and it looks good, but I can now easily tweak the output as needed.

If anyone has questions, concerns, recommendations, etc., just let me know!

All best,
Rebecca

~
Rebecca Cremona
Developer
Harvard Library Innovation Lab
rcremona@law.harvard.edu

----------
More Details:
In addition to addressing the various known bugs in our former implementation, we're making three changes of note:

1) Apropos of https://groups.google.com/forum/#!topic/memento-dev/sys8DeUtmWU: Perma.cc plays back all mementos within an iframe. Sawood asks, "Should the parent/wrapper URI be returned in Memento related Link headers or the inner iframe URI (or both maintain their independent URI-Ms)?" 

It is not at present possible to play back a Perma.cc memento without its wrapping iframe, and so we will now be return the parent/wrapper URI as the URI-M (e.g. https://perma.cc/AAAA-AAAA, rather than https://perma-archives.org/warc/AAAA-AAAA/<url>. The inner iframe URI is now strictly for internal use.

2) Relatedly, it is not at present possible to request the playback of anything but a complete Perma Link. That is to say, if a Perma user made a capture of lil.harvard.edu at https://perma.cc/B2ND-UEGX, you can play back https://perma.cc/B2ND-UEGX, but you can't playback the archived copy of lil.law.harvard.edu/assets/css.main in isolation, all by itself. Therefore, we will only be exposing timemaps and timegates for the top-level captured URLs, not for every resource in our warcs. 

We will therefore be returning 404 for a lot more timemap and timegate queries than we did in the past.

We may be able readdress this in the future, if we can implement support for isolated playback of individual assets within a Perma Link.

3) Only publicly-available Perma Links will be listed in timemaps or redirected to via timegates. Users should no longer uselessly get redirected to private, deleted, or potentially transient (e.g. less than 24-hours old, and still subject to user deletion) Perma Links. If, via a non-standard mechanism, a user encounters a playback of a Perma Link they would not be able to discover via a timemap or a timegate, that playback will NOT include headers like link or memento-datetime in the response, to avoid confusion.
```

**Comment by phonedude** [comment]
Hi Rebecca,

Thanks for the response.  Mohamed can provide the details, but all of those URLs in question were top-level pages, and pages for which we were able to replay fully in the past.  Perhaps they became private later, but we have full responses for them in the past.

This is part of our longitudinal study of replay 16k mementos from 17 different archives over the last 1.5 years:

[Collecting 16K archived web pages from 17 public web archives](https://arxiv.org/abs/1905.03836)

We look forward to Monday's response as well.

Thanks!

Michael

**Comment by rebeccacremona** [comment]
Alright, this isn't great.

Looking manually in our database, our earliest user-requested capture of `https://csrc.nist.gov/` is indeed from Thu, 13 Jun 2019 15:06:56 GMT, https://perma.cc/R84B-LJWJ, as correctly reported by the timemap. 

We do have a capture of `http://csrc.nist.gov/publications/nistpubs/800-37-rev1/sp800-37-rev1-final.pdf` from Thu, 21 Sep 2017 15:46:50 GMT, https://perma.cc/WM9J-UD38. Inspecting that warc, I see that its last record is a request for `https://csrc.nist.gov/`. `https://csrc.nist.gov/publications/nistpubs/800-37-rev1/sp800-37-rev1-final.pdf` redirects to `/publications/detail/sp/800-37/rev-1/final`, which returns HTML that includes the frame-busting javascript:
```
<script type="text/javascript">
    if (self.location != top.location) {
        document.getElementById("navbar").style.display = 'none';
        document.getElementById("body-section").style.display = 'none';
        document.getElementById("footer").style.display = 'none';
        document.getElementById("frameBusterDiv").style.display = 'block';
        setTimeout("top.location.replace('https://csrc.nist.gov/')", 2000);
    }
</script>
```

I suspect that javascript is somehow implicated in our having the homepage's source in this warc, but it's hard to say exactly why the capturing browser requested it: we can see that the capturing browser was -not- redirected to the homepage, because the screenshot, taken just before ending the recording session, shows the requested PDF publication's page and not the homepage.  

In any case, `https://csrc.nist.gov/` was not the "top-level", user-submitted URL for this capture, the URL that plays back when you visit https://perma.cc/R84B-LJWJ, and that is why it's not exposed in our timemaps.

Similarly, we don't have any top-level captures of `tmall.com`: it looks like we have a few item detail pages from that domain, and two of your manifests:

```
>>> tmall = Link.objects.filter(submitted_url__icontains='tmall.com')
>>> tmall.count()
10
>>> for link in tmall: print(link.guid, link.submitted_url)
... 
3RCE-ZP9G http://manifest.ws-dl.cs.odu.edu/manifest/http://webarchive.loc.gov/all/20131201012526/http://tmall.com/
82BL-PS93 https://detail.tmall.com/item.htm?spm=a220m.1000858.0.0.5ee23c03HqDUmi&id=606213446914&skuId=4244639152209&is_b=1&cat_id=2&q=%25BA%25A3%25BF%25B5%25CD%25FE%25CA%25D3+h10+%25C8%25C8%25CF%25F1%25D2%25C7
928R-DPVA http://manifest.ws-dl.cs.odu.edu/manifest/http://archive.is/20130204165948/http://www.tmall.com/
J36M-4P6U https://dissona.tmall.com/shop/view_shop.htm?spm=a220m.1000858.0.0.scaVKK&rn=72fe7e923cfad2052b32892cdbdd8b0f
M5VQ-UUQ8 https://www.tmall.com/mlist/regular_dwTkBlH_o103nt30JQcpQw.html
Q44Q-2MAC https://dissona.tmall.com/shop/view_shop.htm?spm=a220m.1000858.0.0.scaVKK&rn=72fe7e923cfad2052b32892cdbdd8b0f
TJ3K-AK5Z https://detail.tmall.com/item.htm?spm=a220m.1000858.0.0.5ee23c03HqDUmi&id=606213446914&skuId=4244639152209&is_b=1&cat_id=2&q=%25BA%25A3%25BF%25B5%25CD%25FE%25CA%25D3+h10+%25C8%25C8%25CF%25F1%25D2%25C7
TK87-TS7W https://vanessahogan.tmall.com/?scene=taobao_shop
WS2M-BECF https://detail.tmall.com/item.htm?id=539662720791
ZB6W-593T https://detail.tmall.com/item.htm?spm=a220m.1000858.0.0.5ee23c03HqDUmi&id=606213446914&skuId=4244639152209&is_b=1&cat_id=2&q=%25BA%25A3%25BF%25B5%25CD%25FE%25CA%25D3+h10+%25C8%25C8%25CF%25F1%25D2%25C7
```

Similarly, I don't find any requests to capture `cms.gov/cciio/index.html`, though I do see five of your manifests:
```
>>> cms = Link.objects.filter(submitted_url__icontains='cms.gov/cciio/index.html')
>>> cms.count()
5
>>> for link in cms: print(link.guid, link.submitted_url)
... 
29Y5-BQ5W http://manifest.ws-dl.cs.odu.edu/manifest/http://wayback.archive-it.org/all/20130521174746/http://www.cms.gov/cciio/index.html
2AVZ-KTFZ http://manifest.ws-dl.cs.odu.edu/manifest/http://webarchive.loc.gov/all/20140102212724/http://www.cms.gov/cciio/index.html
2R2P-69AA http://manifest.ws-dl.cs.odu.edu/manifest/http://arquivo.pt/wayback/20140909161118/http://www.cms.gov/cciio/index.html
3JAZ-EEAH http://manifest.ws-dl.cs.odu.edu/manifest/http://webarchive.loc.gov/all/20130520041213/http://www.cms.gov/cciio/index.html
JEL4-SJXS http://manifest.ws-dl.cs.odu.edu/manifest/http://webharvest.gov/congress113th/20141207133531/http://www.cms.gov/cciio/index.html
```

For `databank.worldbank.org/data/home.aspx`, I only find your manifests, and for home depot's domain, I only find detail pages and your manifests. None of the detail pages (for instance, https://perma.cc/9KHA-8LNW) are captures of the homepage in disguise; I checked one of them to see if it incidentally contained the source of the homepage as well: at least 9KHA-8LNW does not.

I fear it's the same story for the rest of the URLs on your list. It is possible we picked some of them up incidentally along the way (e.g. `http://www.usa.gov/page-not-found` as a user documented that an Obama-era webpage 404'ed immediately after Trump was inaugurated), but I don't think we have any user-requested captures targeting those pages.

Let's talk via email about how much this affects your research; I sincerely hope not too much. We want to support your use, but we're optimized for our normal use case, where an author requests that we record a browser's complete rendering of a target webpage, and then includes that Perma Link in a piece of their writing, in case the live version of the target webpage disappears or changes. Indexing into warcs and pulling out pieces for selective playback is far enough from that, that we just haven't been able to prioritize it. We no longer maintain an index of all the URLs within our warcs; we only have an index of the user-supplied target URLs. 

An inquiry like I did with csrc.nist.gov above should be able to match the internal "long-form" perma-archives.org URLs that you have with the Perma Links/warcs that contain them, in cases where the present timemaps don't serve. I could at least produce an export of the data needed to do that; if the list is short enough, I might be able to produce a mapping for you myself.

Sorry that present Perma doesn't support the same level of introspection into warcs that earlier versions of Perma did. When we upgraded our playback backend, we didn't have the resources to re-implement that feature.

Regretfully,
Rebecca

**Comment by phonedude** [comment]
Hi Rebecca, 

ACKing receipt.  We'll follow up via email in the coming days.

Thanks for your time investigating this,

Michael

**Comment by rebeccacremona** [comment]
(Closing since we don't plan to maintain an index of all the URLs within our warcs; we only maintain an index of the user-supplied target URLs; perhaps to be re-considered if the entire collection is [migrated to wacz](https://github.com/harvard-lil/perma/issues/2981))
