### ISSUE TITLE
Warcprox and SSL

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/perma#2844]
```
2020-10-05 16:40:52,145 [ERROR] mitmproxy.py 352: problem handling 'CONNECT wrha.mb.ca:443 HTTP/1.1': SSLError(1, '[SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:1056)')
```
This is not the same as https://github.com/harvard-lil/perma/issues/2696

**Comment by rebeccacremona** [comment]
Two more:
https://binbaz.org.sa/audios/2255/105-%D9%85%D9%86-%D8%A8%D8%A7%D8%A8-%D8%AD%D9%82-%D8%A7%D9%84%D8%B2%D9%88%D8%AC-%D8%B9%D9%84%D9%89-%D8%A7%D9%84%D9%85%D8%B1%D8%A7%D8%A9

and https://hrsd.gov.sa/ar/faq/%D9%85%D8%A7%D9%87%D9%8A-%D8%A7%D9%84%D9%85%D9%87%D9%86-%D8%A7%D9%84%D9%85%D9%82%D8%B5%D9%88%D8%B1%D8%A9-%D8%B9%D9%84%D9%89-%D8%A7%D9%84%D8%B3%D8%B9%D9%88%D8%AF%D9%8A%D9%8A%D9%86-%D8%9F

**Comment by rebeccacremona** [comment]
See also https://github.com/internetarchive/warcprox/issues/115

**Comment by matteocargnelutti** [comment]
Cross referenced in: #3121
