### ISSUE TITLE
Check if we are approaching folder max ID?

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/perma#2904]
...and make sure this folder isn't lost, somewhere.
```
IntegrityError at /api/v1/folders/113589/
(1690, "BIGINT UNSIGNED value is out of range in '(`perma`.`perma_folder`.`lft` + -(992))'")
```

**Comment by bensteinberg** [comment]
I wonder if this is not ID overflow, but because the number in the query is negative, and the value is supposed to be unsigned. Maximum value of an unsigned BIGINT is `2^64 - 1`.
