### ISSUE TITLE
mphillips@law.harvard.edu email address included on emails generated from perma.cc web contact form

### ISSUE THREAD

**Issue by arderyp** [harvard-lil/perma#2925]
I am getting bounce backs on this email address.  Judging on that, and the fact that Matt's github account indicates he works for Moon Creative Lab in Palo Alto CA, I'm guessing he no longer works at Harvard, and thus his email address was deactivated, hence the bounce backs.  

Maybe @phillipsm's email should be removed, and @rebeccacremona's should be added, given that she appears to be doing the majority of the current commits.

I don't see Matt's email in the actual code, else I'd provide a PR.  So I am guessing its in some configuration file somewhere on the production server.

**Comment by rebeccacremona** [comment]
Thanks @arderyp! Rest assured, our team did receive your email regardless. Looks like we did accidentally leave Matt as one of the "registrar users" for your organization when he moved on to other adventures; now fixed. Thx.
