### ISSUE TITLE
private playbacks not working in Chrome

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/perma#2985]
there's some cookie-related problem

**Comment by rebeccacremona** [comment]
I think this is something up with how Perma (Django 2.2) handles `SameSite`. In Chrome, I can see that the session cookie's SameSite value is unset, as opposed to explicitly `None`, unlike cloudflare's cookie:
![image](https://user-images.githubusercontent.com/11020492/151860132-7cad2ced-d52e-4ebf-ba60-0d1a21f476c8.png)

I think that means Chrome is defaulting to `Lax`, which doesn't work for this particular complex iframe cookie-setting handshake route.

Both cookies look the same in Firefox:
![image](https://user-images.githubusercontent.com/11020492/151860359-9ba38387-8d53-47e4-b5f9-1a3d41852bec.png)

I think we can't fix this while using Django 2.2.

Observe, in 2.2, we can [`disable the flag by setting it to None`](https://docs.djangoproject.com/en/2.2/ref/settings/#session-cookie-samesite). In [3.2](https://docs.djangoproject.com/en/3.2/ref/settings/#session-cookie-samesite), you disable the flag by setting it to `False`, or can specify:
> 'None' (string): the session cookie will be sent with all same-site and cross-site requests.

![image](https://user-images.githubusercontent.com/11020492/151861324-6702fbea-9a89-40d1-8932-e75961d69c92.png)

**Comment by rebeccacremona** [comment]
from https://web.dev/samesite-cookies-explained/:

> To encourage developers to state their intent and provide users with a safer experience, the IETF proposal, Incrementally Better Cookies lays out two key changes:
>
>  - Cookies without a SameSite attribute will be treated as SameSite=Lax.
>  -  Cookies with SameSite=None must also specify Secure, meaning they require a secure context.
>
> Chrome implements this default behavior as of version 84. Firefox has them available to test as of Firefox 69 and will make them default behaviors in the future. To test these behaviors in Firefox, open about:config and set network.cookie.sameSite.laxByDefault. Edge also plans to change its default behaviors.

**Comment by matteocargnelutti** [comment]
This is another problem that client-side playback alleviates 😄 ! 
We should still review how our cookies are set up -- I'll move this discussion to another issue.
