### ISSUE TITLE
Making a record from an IA record results in a 404 during playback

### ISSUE THREAD

**Issue by ross-spencer** [harvard-lil/perma#3040]
For the link below, for a second it looks like the page will resolve to an archive of a BBC website I wanted to reference via perma.cc link. As it resolves it then returns a 404:

![image](https://user-images.githubusercontent.com/1880412/154271417-d444a943-a20f-496f-89d2-218025298c7a.png)

https://perma.cc/U3KM-RQLE

There is a JS console trace:

```
Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'.
wr.perma-archives.org/:1 Failed to load resource: the server responded with a status of 404 ()
DevTools failed to load source map: Could not load content for https://perma.cc/static/bundles/single-link-permissions.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://perma.cc/static/bundles/global.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://perma.cc/static/bundles/single-link.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

I don't know if this is considered a sensible use case. An IA link, for example, can be removed, and so this is why I was attempting to create a backup in perma. 

I don't want to second guess why this is happening. I don't have enough info under the hood. It'd be great to see it either resolved, or a bit more information provided about the relationship between IA and perma.cc. Perhaps some feedback via the UI if this isn't possible at all.

**Comment by rebeccacremona** [comment]
Very belatedly: it looks to me like this page 404s at the internet archive (https://web.archive.org/web/19991013081623/http://bbc.co.uk/):
![image](https://user-images.githubusercontent.com/11020492/184199946-adbbdbff-d53d-4079-b379-c54f3ee75878.png)

and it looks like Perma successfully captured the 404... albeit without the nice banner at the top that shows this is an internet archive page: https://perma.cc/U3KM-RQLE?view-mode=client-side&type=image

I'm not sure why the playback at https://perma.cc/U3KM-RQLE?view-mode=client-side looks like it does: you can see the playback working, and then it is very quickly replaced by a blank screen... some javascript run by the captured page running amok. We can look into that!

But, sounds like the 404, while not helpful if you are looking for content that once lived at http://bbc.co.uk/, is in this case correct.

**Comment by ross-spencer** [comment]
> I'm not sure why the playback at https://perma.cc/U3KM-RQLE?view-mode=client-side looks like it does: you can see the playback working, and then it is very quickly replaced by a blank screen... some javascript run by the captured page running amok. We can look into that!

Hi @rebeccacremona you have closed this one, but have you got a replacement issue for the behavior of the interface as it disappears? 

I don't know how perma has been upgraded since February, but yes, the experience is different today, I also see the page load (correctly) for a few seconds and then it disappears which is different to the first screenshot I show above. 

To clarify, the original issue seems to have been replaced with a slightly different, but equally, not so great issue:

![image](https://user-images.githubusercontent.com/1880412/184291551-4b9a6f74-9a65-4db4-b10e-3a74df00f225.png)

**Comment by rebeccacremona** [comment]
Yes, we are looking into why the playback of this Perma Link blinks out instead of sticking around; in the meantime, we suggest relying on the screenshot view.

In a new capture of the same page, the IA banner shows up fine (https://perma.cc/VW75-DHGP?view-mode=client-side&type=image), so alas, there must have been a blip during this particular Link's capture process: my best guess is that the JS that renders the banner was slow to load, and hadn't loaded/rendered when we stopped capturing.
