### ISSUE TITLE
Ordering of organization root folders in folder tree

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/perma#3045]
What is determining what order these come back in? It seems to be repeatable, but I don't immediately see how they are sorted: it's not by org name, org creation timestamp, folder id....

I could have sworn this used to be alphabetical.......

**Comment by kilbergr** [comment]
Hi @rebeccacremona I remember discussing this with you but want to make sure I'm capturing.

I believe this is an issue exclusively on the admin site. I took a picture having signed in as an admin running the site locally:
<img width="231" alt="Screen Shot 2022-10-25 at 12 01 17 PM" src="https://user-images.githubusercontent.com/7401870/197824226-c5690d40-e49c-4da0-99ce-aabb817f4fdc.png">

I see the `perma_link_folders` and `perma_folders` models. I believe this ticket is in reference to the latter. 

From what I understand, an example would be:
admin user id `1` with email `test_admin_user@example.com` and root folder `22`
a `perma_folders` object with id `22` called `Empty root folder`

Which of the following is what this ticket is targeting:

If there were more than 1 root folder associated with the admin user `1`, you'd want those returned alphabetically (these folders not represented in the image)

OR

Or is it within the various folders associated with admin user `1`, those folders should be returned alphabetically (these folders represented in the image)

**Comment by rebeccacremona** [comment]
> I believe this is an issue exclusively on the admin site.

With nothing expanded, that folder tree shows users [top level folders](https://github.com/harvard-lil/perma/blob/69724bd37fc9fe02c7d0855027ea3130cdd912ff/perma_web/perma/models.py#L863). "Personal Links" is always first. If a user is sponsored, "Sponsored Links" is next. Then comes the [shared folder](https://github.com/harvard-lil/perma/blob/69724bd37fc9fe02c7d0855027ea3130cdd912ff/perma_web/perma/models.py#L1175) of every org the user is allowed to see. Lots of users can see multiple orgs: admin users can see all orgs; registrar users can see all the orgs associated with the registar; org users can see any orgs to which they have specifically been added. 

The org folders are not being returned in any useful order. (I swear `self.get_orgs()` used to come back alphabetically by `name`, but there's no evidence that was the case.) I think we need to change the various queries there to sort asc by name.

**Comment by rebeccacremona** [comment]
> I see the perma_link_folders and perma_folders models

There's only just the [`Folder` model](https://github.com/harvard-lil/perma/blob/69724bd37fc9fe02c7d0855027ea3130cdd912ff/perma_web/perma/models.py#L1162), but every `Link` is associated with a `Folder`. In fact, the models are set up such that any given `Link` can actually be in multiple `Folders`: here's [where the many-to-many relationship is defined](https://github.com/harvard-lil/perma/blob/69724bd37fc9fe02c7d0855027ea3130cdd912ff/perma_web/perma/models.py#L1370). The database table called `perma_folder` is where the fields for `Folder` are kept; the table called `perma_link` is where the fields for `Link` are kept; the table called `perma_link_folders` is the join table for the many-to-many relationship.
```
perma=# select * from perma_link_folders limit 1;
 id |  link_id  | folder_id 
----+-----------+-----------
  2 | 75FY-EY6J |        66
```

**Comment by kilbergr** [comment]
> The org folders are not being returned in any useful order. (I swear `self.get_orgs()` used to come back alphabetically by `name`, but there's no evidence that was the case.) I think we need to change the various queries there to sort asc by name.

So is what this ticket is asking is for this line to return a list ordered alphabetically: https://github.com/harvard-lil/perma/blob/develop/perma_web/perma/models.py#L870
?

**Comment by rebeccacremona** [comment]
> So is what this ticket is asking is for this line to return a list ordered alphabetically: https://github.com/harvard-lil/perma/blob/develop/perma_web/perma/models.py#L870
?

No, Personal Links should still always be first, and if a user is sponsored then their Sponsored Links folder should still always be second, but the shared org folders that come afterwards should be alphabeticallly by name.

**Comment by kilbergr** [comment]
OK got it. Thanks.

**Comment by kilbergr** [comment]
https://github.com/harvard-lil/perma/pull/3197

**Comment by kilbergr** [comment]
https://github.com/harvard-lil/perma/pull/3236
