### ISSUE TITLE
Client-side playback: unsupported browsers

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/perma#3141]
Let's get (and document) a clearer picture of which browsers we support and which we don't, and let's make sure the experience is as good as it can be for visitors whose browsers are too old: link to help page? informative `<noscript>` tag? The replayweb.page JS already does some of this, but let's double check.

**Comment by matteocargnelutti** [comment]
Prioritized as discussed.

**Comment by matteocargnelutti** [comment]
Implemented in https://github.com/harvard-lil/perma/pull/3203 leaving this issue open until the feature deployed to prod 😄 .
