### ISSUE TITLE
Display subscriptions' and purchases' reference numbers

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/perma#3149]
After this information is [exposed by Perma Payments](https://github.com/harvard-lil/perma-payments/issues/153), display subscriptions' and purchases' reference numbers on a user's [usage plan page](https://github.com/harvard-lil/perma/blob/develop/perma_web/perma/views/user_management.py#L1186) to smooth out customer service.

**Comment by matteocargnelutti** [comment]
Congrats @kilbergr 👏 !!!
