### ISSUE TITLE
Create a calendar view

### ISSUE THREAD

**Issue by phillipsm** [harvard-lil/perma#336]
If multiple users have archived the same URL, it would be useful to see different versions over time. A calendar view could work, like how the Wayback Machine does it.
![cal-view](https://f.cloud.github.com/assets/196089/1586560/576279e8-522a-11e3-9aa9-9774348e504b.png)

**Comment by anastasia** [comment]
Basic structure is done — calendar exists, displaying only public links, showing search results for fuzzy urls. Need feedback on what we want our calendar UX to look like

**Comment by anastasia** [comment]
This is done? I think?

**Comment by rebeccacremona** [comment]
See https://github.com/harvard-lil/perma/issues/1728

**Comment by jcushman** [comment]
So done.
