### ISSUE TITLE
Link to library partners on website is dead

### ISSUE THREAD

**Issue by ThisIsMissEm** [harvard-lil/perma#3374]
Hi, I just happened to come across perma.cc whilst reading an academic paper, and I happened to notice that the link on the website to the library partners (`https://perma.cc/about#partners`) appears to be dead, as that anchor does not exist on the about page anymore.

(I was trying to see if a specific university was a partner before sending a contact at said university information about the service)

**Comment by cmsetzer** [comment]
Resolved in https://github.com/harvard-lil/perma/pull/3552. The code we used to display specific partners was removed a while back, but as @ThisIsMissEm noted, we had not updated links to the removed section. Thanks for catching this.
