### ISSUE TITLE
Broken link at https://perma.cc/docs

### ISSUE THREAD

**Issue by jp-tosca** [harvard-lil/perma#3385]
Good evening! 

I just noticed that under the section "[Using links](https://perma.cc/docs#using-links)" the link An example from the [Harvard Law Review](http://cdn.harvardlawreview.org/wp-content/uploads/2014/06/vol127_west.pdf) shows Error 1016 when clicked but the link works [without "cdn" ](https://harvardlawreview.org/wp-content/uploads/2014/06/vol127_west.pdf) 

Best,
J.P.

**Comment by cmsetzer** [comment]
Fixed in https://github.com/harvard-lil/perma/pull/3552; this update should be visible in production soon. Thanks for flagging, @jp-tosca!
