### ISSUE TITLE
Duplicate backslashes after pasting a password

### ISSUE THREAD

**Issue by arkare** [harvard-lil/perma#3407]
**Description:**
When attempting to create a new account, verify the email address, and set a password, an issue arises when pasting the password from a password manager using the CTRL+V shortcut. The problem occurs during the input of the password, resulting in unintended backslash duplication.

**Steps to Reproduce:**
1. Create a new user account.
2. Verify the email address.
3. During the password creation step, paste the following password: `AUE:aild>WC\$Wp=Ao@H`.
4. Attempt to log in.

**Observed Behavior:**
Upon careful investigation, it was discovered that the input in the third step duplicates backslashes when pasting the password using CTRL+V. Consequently, the password is transformed from `AUE:aild>WC\$Wp=Ao@H` to `AUE:aild>WC\\$Wp=Ao@H`. 

This results in the following sequence:
- Original: `AUE:aild>WC\$Wp=Ao@H`
- First Paste: `AUE:aild>WC\\$Wp=Ao@H`
- Second Paste: `AUE:aild>WC\\\\$Wp=Ao@H`

This behavior is unexpected and can potentially lead to login issues for users relying on password managers.

**Expected Behavior:**
The system should accurately accept and store the pasted password as it is, without introducing additional backslashes, ensuring that `AUE:aild>WC\$Wp=Ao@H` remains unchanged.

**Comment by mdellabitta** [comment]
Thanks for the report, @arkare. We've added an issue for this in our internal task tracker!

**Comment by mdellabitta** [comment]
@arkare can you tell me which password manager you're using?

**Comment by arkare** [comment]
It's KeePassXC. Thanks for the fast reply.

**Comment by mdellabitta** [comment]
Hello @arkare,

Unfortunately, I wasn't able to replicate your issue. Is it possible you're making use of some script or functionality to auto paste from KeePassXC that may be causing trouble?
