### ISSUE TITLE
reddit.com doesn't work

### ISSUE THREAD

**Issue by minhtrancccp** [harvard-lil/perma#3612]
i tried to archive this reddit post: https://old.reddit.com/r/RBI/comments/15csn2w/validating_a_quote/

when i passed it to perma, i was shown with an error message (at one moment it showed the error code of 503):
![image](https://github.com/user-attachments/assets/8e3e4240-dc0e-4b64-ae70-d25f85a87954)

but the same post was saved without issues using internet archive: https://web.archive.org/web/20241004162222/https://old.reddit.com/r/RBI/comments/15csn2w/validating_a_quote/

**Comment by rebeccacremona** [comment]
Hello! Yes, this is frustrating. 

Many websites block incoming traffic that they don't like. When I visit old.reddit.com from an AWS IP address, this is what I see: 

![image](https://github.com/user-attachments/assets/e993eb54-f020-494d-9bd5-b205455be4ac)

(HTTP 403: Forbidden)

That is also happening to Perma: it is being blocked.

Unfortunately there is nothing we can do about it at this time; we are thinking through strategies for trying to address this type of issue in general.

In the meantime, you can click "upload your own" to save a PNG or PDF of the page in question.

Best,
