### ISSUE TITLE
follow javascript redirects when indexing

### ISSUE THREAD

**Issue by phillipsm** [harvard-lil/perma#428]
We currently use Python Requests to get the location of the document we want to archive. This is true for source downloads, text indexing, and pdf downloads. Requests does great for HTTP redirects (in the HTTP response header) but has no way to follow a JS redirect (it doesn't execute JS). 

Redirects like the one below are unfollowed and often times produce unexpected behavior for the user (their browser will follow these types of redirects.)

```
document.location = 'librarylab.law.harvard.edu';
```

We should investigate what it looks like if we work with PhantomJS or some other headless browser to work through JS redirects. (Maybe node has something nice?)

http://www.fsis.usda.gov/PDF/Strategic_Plan_2011-2016.pdf is an example of location that relies on JS (without any hint in the HTTP response header) to do a redirect.

**Comment by jcushman** [comment]
Fixed by warc capture.
