### ISSUE TITLE
Detect PDFs in embed or object tags

### ISSUE THREAD

**Issue by phillipsm** [harvard-lil/perma#429]
Some PDFs are embedded using an embed or an object element in markup, with the content coming from CGI (?)

An example: 

```
<embed width="100%" height="100%" name="plugin" src="http://lawdigitalcommons.bc.edu/cgi/viewcontent.cgi?article=1440&amp;context=lsfp" type="application/pdf">
```

The above comes from http://lawdigitalcommons.bc.edu/cgi/viewcontent.cgi?article=1440&context=lsfp

Do we want to detect this and index it? How many corner cases are there like this?

**Comment by jcushman** [comment]
Warc branch has been deployed for a little while now ...
