### ISSUE TITLE
Check the safe browsing list prior to archive creation

### ISSUE THREAD

**Issue by phillipsm** [harvard-lil/perma#557]
When a user asks Perma to create an archive, we should check the name against the Safe Browsing API, https://developers.google.com/safe-browsing/

If it's on the list, we should let the user know and not create the archive. At this point, we should kindly instruct the user to upload a capture of the site.

**Comment by matteocargnelutti** [comment]
Probably no longer relevant because of how the capture process evolved since 2014.
