### ISSUE TITLE
Create darchive request system

### ISSUE THREAD

**Issue by phillipsm** [harvard-lil/perma#586]
When an archive is placed in the darchive a reader should be able to request access to it through a librarian.

On the archive landing page place a form (or a link to a form) to request access to the archive. The user enters their email and name to request access (if the user is logged in, this is of course prepopulated). They hit the "Request access" button.

The form generates a request that is sent to the owning registrar (the creating user's, vesting org's library). Maybe there's a new admin panel that manages this and emails the registrar email contact weekly with any pending requests? The registrar can communicate with the user directly and can print or email an image of the archive.

We should also add a section to the user guide that helps the registrar user with this process.

**Comment by matteocargnelutti** [comment]
Note for future us: this question is still relevant, just hard to prioritize.
