### ISSUE TITLE
Change "pending" treatment when archive processing is killed for an item

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#599]
Right now we leave database flag as "pending" even if we kill the archiving process for an item. 

Per Jack: Next steps would probably be to have the archiving process detect failure and run X times until it succeeds (this is a simple celery tweak); plus add a celerybeat process to check for existing links that have been pending for an unreasonably long period of time and mark them as failed.

**Comment by jcushman** [comment]
Superseded by https://github.com/harvard-lil/perma/issues/1668 and https://github.com/harvard-lil/perma/issues/1597
