### ISSUE TITLE
Allow timed/delayed redirects to run before screen capture

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#629]
Some sites use timed/delayed redirects to show interstitial before browser loads intended page. Currently, our screen capture grabs the interstitial. Should we investigate detecting delayed redirects and waiting for redirect to run?

**Comment by jcushman** [comment]
This is still a good idea -- detect `<meta http-equiv="refresh" content="3;url=http://www.google.com/" />` and trigger the redirect ourselves.

**Comment by matteocargnelutti** [comment]
Scope of the problem evolved since 2016.
