### ISSUE TITLE
Archive with no active tabs

### ISSUE THREAD

**Issue by phillipsm** [harvard-lil/perma#673]
http://perma.cc/0HskU5FCiUt seems to be totally broken. It looks like it should be going to http://scholarship.law.marquette.edu/cgi/viewcontent.cgi?article=5093&context=mulr  (a weird PDF that might be throwing our PDF archive task for a loop?)

**Comment by jcushman** [comment]
Archiving that PDF currently works. Is there anything else to do for this bug?

**Comment by phillipsm** [comment]
@jcushman Thanks for verifying. I think this bug's done. Closing.
