### ISSUE TITLE
Create logic to scramble a set of prod data for testing

### ISSUE THREAD

**Issue by phillipsm** [harvard-lil/perma#682]
It sure would be handy to shave off a slice (or grab in whole) prod data, scramble it, and let it safely sit around on testing machines. Create a fab method for this.

**Comment by phillipsm** [comment]
Related to #720

**Comment by rebeccacremona** [comment]
We now have a script for stripping user passwords from a db and replacing them all with the right hash for `password`.... but it's for postgres only. So, we'll be able to do this once we migrate Perma to postgres.
