### ISSUE TITLE
Delete unvested archive - not working

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#690]
Logged in as registrar user. Links view.

Steps
1. Access My Links
2. Select random link
3. Link view opens in new tab
4. Select delete
5. Perma rendes confirm "Yahowza" page
6. Confirm "really want to delete forever"
7. 500 Error

**Comment by anniejocain** [comment]
I can't reproduce this. @abziegler is this still broken?

**Comment by jcushman** [comment]
Confirmed, can't reproduce.
