### ISSUE TITLE
Add content relative metadata / Facebook OpenGraph / Twitter Card tags to the HTML head

### ISSUE THREAD

**Issue by leppert** [harvard-lil/perma#699]
Presently, most social services will end up showing this static `description` for every perma link shared:

> Broken links are everywhere. Perma helps authors and journals create permanent links for citations in their published work.

Ideally this description would take into account the content being shared to give users a way to differentiate various perma links within the context of these social sites. Additional information added in the form of Facebook OpenGraph or Twitter Card tags would also be welcomed.

**Comment by anastasia** [comment]
https://perma.cc/A3DF-4UHW should we add a "share" button on link pages? Or twitter and facebook icons that make it easy for people to share?
