### ISSUE TITLE
Revise Perma email text

### ISSUE THREAD

**Issue by phillipsm** [harvard-lil/perma#711]
The email that goes to new users is a little rough.
![screen shot 2014-10-29 at 6 00 17 pm](https://cloud.githubusercontent.com/assets/196089/4835429/1cbbce20-5fb7-11e4-8b35-cd9a4b83e005.png)

**Comment by jcushman** [comment]
We think it might also help with spam filters if our new account emails looked more like other new account emails and less like spam (single line of unformatted text).

**Comment by jcushman** [comment]
Next actions: Becky will poke Adam when the email templates are ready for editing.
