### ISSUE TITLE
Vested link in "Temporary Archive" banner should vest if user has vesting privs

### ISSUE THREAD

**Issue by phillipsm** [harvard-lil/perma#718]
If the user is logged in and has vesting privs, the link should vest (and not link to the manual).

**Comment by phillipsm** [comment]
Or, remove the link if you're logged in.
![screen shot 2015-03-16 at 12 08 14 pm](https://cloud.githubusercontent.com/assets/196089/6670476/2f04b72e-cbd5-11e4-8239-b7190ab592e1.png)

**Comment by anniejocain** [comment]
Closed in 2287ff91c3cc8a2e4eeaf940dea9c81c2c056439
