### ISSUE TITLE
Header should be consistent across all pages

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#759]
Main page header is slightly different than internal page header - logo is different size, element location is   slightly different

**Comment by phillipsm** [comment]
These look identical to me. Is it possible that this was an issue and now it's fixed? Closing, but please let me know if things look off to you @abziegler

**Comment by abziegler** [comment]
This is home screen logo as a logged in user

![screenshot 2015-03-03 12 56 59](https://cloud.githubusercontent.com/assets/2140548/6468700/d9695b9c-c1a4-11e4-816b-cb59adb49dfa.png)

This is MyLinks screen as a logged-in user

![screenshot 2015-03-03 12 57 44](https://cloud.githubusercontent.com/assets/2140548/6468710/f0fabc06-c1a4-11e4-9d35-2ac7cca8c659.png)

All in Chrome

**Comment by abziegler** [comment]
It's subtle but the infinity loop is in a different spot relative to the word "CREATE." Also, if you open both the home screen and the MyLinks screen in side-by-side tabs, you'll see that the header width or something is different too.

**Comment by phillipsm** [comment]
That top button does look broken, @abziegler 

My Chrome, Version 40.0.2214.115 renders the images and the button the same. See attached.

![screen shot 2015-03-03 at 2 49 27 pm](https://cloud.githubusercontent.com/assets/196089/6470919/27f2bb7c-c1b5-11e4-9450-d18b0c2a70c8.png)
![screen shot 2015-03-03 at 2 49 12 pm](https://cloud.githubusercontent.com/assets/196089/6470918/27f1a32c-c1b5-11e4-89cf-f7a094474a17.png)


@anniejocain, how do things look for you?

**Comment by anniejocain** [comment]
Things look fine for me too.
