### ISSUE TITLE
Add PDF capture format for web pages

### ISSUE THREAD

**Issue by jcushman** [harvard-lil/perma#765]
We should try out PDF as an alternative capture format to PNG for long web pages. On phantomjs 1.9.7, with the example rasterize.js script, this seems to produce selectable-text PDFs:

phantomjs rasterize.js 'http://www.icty.org/x/cases/prlic/trans/en/090928IT.htm' test.pdf Letter

The advantage (especially if we save in PDF/A archival format) is this will have the same long-term archival properties as PNG, but with the file size and selectability of the HTML capture (or even smaller).

**Comment by jcushman** [comment]
Update: seems fine to make it look like the print view rather than web view, which is easier with current capture engines. Let's do it.

**Comment by matteocargnelutti** [comment]
Discussed: This should probably be a `perma-capture` discussion.
