### ISSUE TITLE
Restart server upon certain unexpected conditions

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#768]
- No logins for X period
- No link creation for X period

Any others?

**Comment by jcushman** [comment]
Leaving as a provocation for Ben ...

**Comment by bensteinberg** [comment]
We are monitoring link creation (but not auto-restarting) -- from my [comment](https://github.com/harvard-lil/perma/issues/1908#issuecomment-349658031) to https://github.com/harvard-lil/perma/issues/1908: 

> We're already doing part of this (recency of links created) at https://status.perma.cc/monitor, by virtue of https://github.com/bensteinberg/perma-status/blob/master/monitor.py, and keeping an eye on it with https://uptimerobot.com/. (The statistic we're watching is the ratio of time from now to the last completed capture, to the time from now to 20 captures ago.) This system has the merit of using the public API -- tracking user signups/logins would need special privileges, presumably.

**Comment by rebeccacremona** [comment]
This feels obsolete, given the current set up. We might need more/different monitoring in the new world, but let's retire this ticket.
