### ISSUE TITLE
User guide styling broken. Buttons.

### ISSUE THREAD

**Issue by phillipsm** [harvard-lil/perma#775]
Something's up with the styling on the buttons/menu on the user guide.
![screen shot 2015-01-21 at 3 46 55 pm](https://cloud.githubusercontent.com/assets/196089/5844817/e35eba38-a184-11e4-93dc-9ae7716f3f88.png)

**Comment by abziegler** [comment]
I'd like to amp up our user guide/docs to hopefully help manage some of the inbound email traffic. Any objection to me taking a run at it, including a single page restyling approach using this template with our styles: http://codyhouse.co/gem/css-faq-template/ ?

**Comment by kdulin** [comment]
None from me

**Comment by phillipsm** [comment]
Go for it.

A couple of notes:
1. I used the basics of the manual for the API docs (/docs/developer on the staging server). We may or may not want to keep the doc navigation consistent.
2. It can be really nice to provide an anchors into the FAQ/user guide. We do this with the FAQ now, https://perma.cc/docs/faq#delete-links
