### ISSUE TITLE
Beta interest page for non-academic/court users

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#802]
Let's gather contact info for those interested in using Perma beyond academic and court realms.

We'll likely want to create a page that asks folks to enter an email address, a name, and a segment (law firm, publisher, ...). This form can funnel straight into MailChimp, or into a new model.

**Comment by jcushman** [comment]
@abziegler: is this bug still live?

**Comment by abziegler** [comment]
We've evolved past this bug
