### ISSUE TITLE
Vesting button missing.

### ISSUE THREAD

**Issue by phillipsm** [harvard-lil/perma#806]
I'm signed in as a registry member and I'm not getting a Vest button on the single link page. I really, desperately need to vest a picture of an exercise bike.
![screen shot 2015-02-12 at 9 33 26 pm](https://cloud.githubusercontent.com/assets/196089/6181396/1b370230-b300-11e4-9f39-c70163b069e8.png)

**Comment by jcushman** [comment]
I just sent a pull to fix this. Basically staff (registry) users weren't being recognized as staff outside of the dashboard. This does not affect non-staff users.
