### ISSUE TITLE
New PhaontomJS 2.0. Update.

### ISSUE THREAD

**Issue by phillipsm** [harvard-lil/perma#814]
The new PhantomJS is out. Install it. 

http://phantomjs.org/releases.html

**Comment by leppert** [comment]
2.0 breaks the capture task, throwing a JS error. Investigate!

**Comment by phillipsm** [comment]
Thanks for the note @leppert . Kicking this issue down the road until an easy-to-use, official build is available for download. 
![screen shot 2015-03-23 at 11 58 57 am](https://cloud.githubusercontent.com/assets/196089/6784104/138c94d8-d154-11e4-8ea1-10277cad6f76.png)
