### ISSUE TITLE
Squash the create and my links page together.

### ISSUE THREAD

**Issue by phillipsm** [harvard-lil/perma#820]
These things belong together. Feels like good UX to me and our discussion with users didn't present any warnings.

It might look something like the attached. (We may or may not want to go with the tall textbox.

We can likely close #795 if we implement this.  
![batch-on-create](https://cloud.githubusercontent.com/assets/196089/6400571/b95a1a84-bdc7-11e4-9f95-2b352ecc61f7.png)

**Comment by jcushman** [comment]
Matt squashed this.
