### ISSUE TITLE
build status.perma.cc

### ISSUE THREAD

**Issue by phillipsm** [harvard-lil/perma#823]
Or something similar.

https://status.github.com/ and http://status.voxmedia.com/ are a couple of examples.

**Comment by phillipsm** [comment]
And when we get it built, and we're experiencing an issue, link to it from the contact page. Maybe we say something like "We know that we're experiencing a problem. Find details at status.perma.cc/#some-current-issue."

**Comment by bensteinberg** [comment]
now see https://status.perma.cc/ -- still needs to be added to the contact page and/or elsewhere

**Comment by bensteinberg** [comment]
ea051cb
