### ISSUE TITLE
Can we handle/detect multi-page articles?

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#843]
It would be great to detect multi-page resources and capture the whole thing. Possible?

**Comment by phillipsm** [comment]
Like following pagination?

I wonder how broad the support is for rel=”next”? 

I can see this going either way. It might help the user archive the full target, or it might create confusion "hey, that archive doesn't look like what I see on my screen. It's way longer."

**Comment by jcushman** [comment]
We think this is not a great fit for our current capture process -- might be best addressed by interactive capture.
