### ISSUE TITLE
Registry members should be able to bump regular users up

### ISSUE THREAD

**Issue by anniejocain** [harvard-lil/perma#851]
Either from the 'Users' tab or from the 'Vesting users' tab.

Probably also from the 'Registrar users' tab.

**Comment by jcushman** [comment]
Note that, from any of those lists, you can click "edit in admin" and bump up a user by setting their registrar or vesting org setting in the Django admin.

**Comment by anniejocain** [comment]
@phillipsm is this getting fixed with your multi vesting users update? Otherwise I'll get to it.

**Comment by phillipsm** [comment]
@anniejocain I don't think I patched that up. Go for it.
