### ISSUE TITLE
Patch up sauce tests

### ISSUE THREAD

**Issue by phillipsm** [harvard-lil/perma#856]
There are a coupe of sauce tests that fail consistently. Investigate.

There are also nondeterministic sauce failures. Maybe they timeout when the load gets high on the Sauce servers? Maybe we should try a couple of times before returning a failure?

**Comment by jcushman** [comment]
Greg, I have the sauce tests disabled for now -- I was having some issues getting them to run with PhantomJS, and wasn't sure about the Firefox dependency. Let's talk about it.

**Comment by jcushman** [comment]
Integration tests are now working and enabled when pointed at PhantomJS. Still some random errors in some browsers when pointed at Sauce.
