### ISSUE TITLE
Links in FAQ go to old user docs

### ISSUE THREAD

**Issue by phillipsm** [harvard-lil/perma#886]
Some links in the FAQ, https://perma.cc/faq#track-links, go to the old user manual. https://perma.cc/docs/perma-link-creation#organize-links is an example.

Are there other spots in Perma that might go to the old user manual? Maybe we should remove the old user manual and redirect anything that goes to /docs/something to /docs ?

**Comment by abziegler** [comment]
Plan to revise FAQ to better fit common inquiries. Will fix this too.
