### ISSUE TITLE
Fix account creation date/time error

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#890]
Looks like app is recording date/time user becomes a vesting user as date/time account is created. For example, this test account I created months ago is showing creation this morning, which was when I changed account's vesting status:
![screen shot 2015-05-28 at 10 19 53 am](https://cloud.githubusercontent.com/assets/2140548/7862359/59be6014-0523-11e5-9261-f9842b3327f3.png)

**Comment by phillipsm** [comment]
This was fixed in v0.51.1
