### ISSUE TITLE
Give each vesting user a named folder for each vesting org she belongs to

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#891]
By default we give each vesting user a folder with her name on it, within her vesting org. Now that we've added multi-vesting org capability, should we do the same for each vesting org she's in?

**Comment by jcushman** [comment]
Correct me if I'm wrong, but I don't think we've been doing this in general -- it was a one-time thing. When we first added shared folders, we created folders for each user within the shared folder so we'd have somewhere to put their existing links, which up to that point couldn't be shared.

My feeling is we shouldn't add something to create user-name folders within the shared folders -- lots of orgs won't want to use the shared folder that way. But I'm open to it if others think it would be valuable.
