### ISSUE TITLE
Wrong timemap header for some WARC endpoints.

### ISSUE THREAD

**Issue by jcushman** [harvard-lil/perma#906]
Our /warc/guid/ endpoint has the wrong timemap URL in the Link header.

First, here's a *correct* header (using the /warc/datetime/ endpoint):

```
$ curl -I https://user-content.perma.cc/warc/20150527192804/http://cnn.com/
HTTP/1.1 200 OK
...
Memento-Datetime: Wed, 27 May 2015 19:28:04 GMT
Link: <https://user-content.perma.cc/warc/20150527192804/http://www.cnn.com/>; rel="memento"; datetime="Wed, 27 May 2015 19:28:04 GMT", <http://www.cnn.com/>; rel="original", <https://user-content.perma.cc/warc/timemap/*/http://www.cnn.com/>; rel="timemap"; type="application/link-format", <https://user-content.perma.cc/warc/http://www.cnn.com/>; rel="timegate"
```

Now here's an *incorrect* header (using the /warc/guid/ endpoint):

```
$ curl -I https://user-content.perma.cc/warc/89QJ-Y632/http://www.cnn.com
HTTP/1.1 200 OK
...
Memento-Datetime: Fri, 11 Jul 2014 22:11:16 GMT
Link: <https://user-content.perma.cc/warc/89QJ-Y632/http://www.cnn.com/>; rel="memento"; datetime="Fri, 11 Jul 2014 22:11:16 GMT", <http://www.cnn.com/>; rel="original", <https://user-content.perma.cc/warc/*/http://www.cnn.com/>; rel="timemap"; type="application/link-format", <https://user-content.perma.cc/warc/http://www.cnn.com/>; rel="timegate"
```

Note the missing `/timemap/` in the second example. Seems like our custom guid route is confusing pywb's timemap link-generating code.

**Comment by leppert** [comment]
Looks like it's due to `mod` getting replaced with an empty string here:

https://github.com/harvard-lil/perma/blob/develop/perma_web/warc_server/pywb_config.py#L82

Which was introduced here:

https://github.com/harvard-lil/perma/commit/45a520bc4794a71ccc3fb088a57a8ce0b51d6f73#diff-4b7741d4dd737baa878554951fe35c2fR17

I need to look into what the intent of that code is (beyond what's in the comment), then I'll look for a work around for this header specifically.

**Comment by jcushman** [comment]
I remember adding that to stop some sort of cruft being added to the rewritten URLs, but I don't remember why I thought the additional cruft was a problem. (And pywb itself has changed a lot since then.)

First thing I'd try is just removing the override -- if things still work we're probably happy. The one thing to check would be that subassets still use the /warc/GUID/ endpoint so they all come from the same warc.
