### ISSUE TITLE
Support upload of "Save as -> Webpage, complete ..." ?

### ISSUE THREAD

**Issue by jcushman** [harvard-lil/perma#908]
For our alternate upload path, we could allow users to upload the files that result from "Save As -> Webpage, complete" in a browser. The format seems to be the same for all browsers, and the captures are pretty high quality. Could be a good zero-tech-support option to give courts that don't want to create Perma Links in advance.

**Comment by matteocargnelutti** [comment]
This feature is likely going to be phased out from Chrome & Safari - at least in its current version - in the near future.
