### ISSUE TITLE
Django admin error

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#912]
Thought maybe we had fixed previously, but I saw this problem again - trying to delete an account via admin counsel. Got 502 error screen, although change apparently still wen through

**Comment by jcushman** [comment]
This has been fixed in the dev branch for a while; just waiting to push to
prod.

**Comment by phillipsm** [comment]
We should probably jam that out, right? Cool if I do that today?

**Comment by jcushman** [comment]
Yeah, sounds good.

On Wed, Jun 17, 2015 at 11:47 AM, Matthew Phillips <notifications@github.com

**Comment by jcushman** [comment]
Deployed.
