### ISSUE TITLE
Combine user list views into single user list view with filters for user type

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#926]
Should we limit the dropdown to:
- Manage links
- Manage users
- Settings
- Logout

Right now, we include sub-links for all the different user types the loggedIn user can access, and we have separate links for tools and settings. If views/options are available from an on-page menu, do we also need to include them in the dropdown?

**Comment by jcushman** [comment]
@abziegler: is this still a live question?

**Comment by jcushman** [comment]
New version of this bug: combine all user pages (Reg Users, Org Users, Users) into a single user page with filters; remove multiple menu items.
