### ISSUE TITLE
The Archived page tab reports complete when not complete

### ISSUE THREAD

**Issue by phillipsm** [harvard-lil/perma#928]
The spinner on the Archive page tab disappears indicating that the WARC archive is available. When you click on it, you get a 404 because it's not ready yet.

<img width="1483" alt="screen shot 2015-07-13 at 10 32 16 pm" src="https://cloud.githubusercontent.com/assets/196089/8665210/5f64da4c-29af-11e5-9f52-493fb3cdb425.png">

**Comment by jcushman** [comment]
I believe this is fixed ...
