### ISSUE TITLE
Favicons are sometimes not displayed

### ISSUE THREAD

**Issue by phillipsm** [harvard-lil/perma#930]
On the single link page (and maybe the My Links page?) , the favicon is sometimes not displayed. It seems like we should display a favicon or nothing. Not a broken image.

![screen shot 2015-07-14 at 1 55 43 pm](https://cloud.githubusercontent.com/assets/196089/8681220/3b338a44-2a34-11e5-936e-52848c1a34ae.png)

**Comment by jcushman** [comment]
Looks like this is fixed on prod.
