### ISSUE TITLE
Dynamic content?

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#962]
Good question from a library today - can we do more/anything to preserve dynamic pages, such as a page that changes based on user's input or preferences?

**Comment by jcushman** [comment]
There's two easy strategies for nice user uploads I'd like to implement:

1) allow upload of files from browsers' "Save as -> webpage, complete";
2) allow upload of warc captures from e.g. webrecorder.io.

Both of those would be easy to do, and solve a lot of edge cases. First one
is good for low-tech private captures - no extra tools required. Second one
should work for basically any kind of complex user-driven capture.

(Still on vacation, but we're stuck in traffic on our way to see a
waterfall near Portland, so.)

**Comment by abziegler** [comment]
Cool. Let's add it to the feature list ... maybe aim for the fall after we're done with vesting work, etc.
