### ISSUE TITLE
Unable to create archive from gnu.gl address 

### ISSUE THREAD

**Issue by phillipsm** [harvard-lil/perma#981]
Perma doesn't like ```https://www.gnu.gl/blog/Posts/multiple-vulnerabilities-in-pocket/``` 

We should invetigate.
![imgres](https://cloud.githubusercontent.com/assets/196089/9334649/c73a5ee4-459d-11e5-8f40-625f25fcb287.jpg)

**Comment by jcushman** [comment]
This appears to be an issue with the SSL implementation fixed in Python 2.7.9. I sent an email asking ITS to upgrade.
