### ISSUE TITLE
Archive and screenshot tabs not appearing sometimes

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#986]
On stage ... 

Both archive and screenshot tabs initially not appearing for capture of sec.gov. Works fine on another site.

![screen shot 2015-08-18 at 4 05 08 pm](https://cloud.githubusercontent.com/assets/2140548/9341248/b35e4122-45c2-11e5-9802-75190104299d.png)

But when you click the "live view" tab, the other two tabs suddenly appear.

![screen shot 2015-08-18 at 4 05 49 pm](https://cloud.githubusercontent.com/assets/2140548/9341254/bc75ba38-45c2-11e5-99d0-66a1a11a1ad7.png)

**Comment by abziegler** [comment]
Also - link-action buttons (vest, delete, darchive) not visible either.

**Comment by jcushman** [comment]
This is the same issue as #987 -- closing.
