### ISSUE TITLE
Action buttons not visible on record view screen

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#987]
On stage...
Logged in as vesting user ...

Action buttons (e.g. vest, delete, darchive) should be visible

![screen shot 2015-08-18 at 4 09 38 pm](https://cloud.githubusercontent.com/assets/2140548/9341370/5908ec1c-45c3-11e5-9961-294a93d201bc.png)

**Comment by jcushman** [comment]
@abziegler, we think maybe this is stage-specific and you have an old login cookie. Can you try logging out and back in and see if that fixes it? (And make sure you're on perma-stage.org rather than the old stage URL, of course.)

**Comment by abziegler** [comment]
Seems to fix it - I was not on perma-stage.org. Why does the old perma-stage still work?

**Comment by jcushman** [comment]
Good call -- I set the old URL to forward to the new one. Closing this.
