### ISSUE TITLE
Dynamically generate list of registrars for "about" page

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#997]
Very good idea from @kdulin ...

Stop manually updating partners list and just dynamically build a table of registrars.

Questions/Issue to address:
* Probably should have a public/private flag that's default private, so we don't display people before they've given permission. This matters most for courts, etc., that are testing. We should be able to flip the flag to public in the admin console, which will include the registrar in the public table.
* Should make name a link to registrar website
* Should make table sortable/searchable so people can find their place

**Comment by jcushman** [comment]
This is up.
