### ISSUE TITLE
Give bookmarklet some flair

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#998]
Our bookmarklet (which is used, as recent user feedback confirmed), doesn't have any perma-specific icon/favicon. It's just the blank doc icon.

Can we give this thing a blue infinity icon or something?

**Comment by abziegler** [comment]
On Firefox ... the bookmarklet adds just a blank box to toolbar ... not even the "Create Perma link" text you get in Chome. Definitely should do a little something here.

**Comment by rebeccacremona** [comment]
Executive summary: Unfortunately it doesn't sound like we can tweak this behavior. I'll look into how easy it is to make/maintain browser extensions, which will be significantly more powerful and feature-rich.

With a normal bookmark, with a url of type "http://mysite.here", the browser gets an image and text by follows the HTML spec: it looks for a <link rel="icon"> tag in the bookmarked page and uses that if found, and if not, looks in a conventional spot at the website's root. It gets the text from the <title> tag in the bookmarked page.

But bookmarklets have a url of type "javascript://my.code.here;". There's no provision for specifying where to grab a favicon from, or to unambiguously give the bookmarklet a title. The fact that in some/most browsers, our bookmarklet is getting the title "Create a Perma link" is, I believe, more of a happy accident than anything else. Research suggests that's pretty finicky, and might work with one version of a browser, break on update, and the work again at a later date. (For instance, in Firefox 48.0.2, you do in fact get the "Create Perma Link" text, which Adam did not experience with his Firefox in Aug 2015. For instance, https://bugs.chromium.org/p/chromium/issues/detail?id=91624)

Some people have proposed hacks that try to give you the best of both worlds: a bookmarket that serves up an html page (which can have a favicon and title), but that runs your javascript just like a bookmarklet. For example: http://www.tapper-ware.net/blog/?p=267, http://stackoverflow.com/questions/5952387/adding-favicon-to-javascript-bookmarklet-uses-window-open. But, I haven't found the hacks (even their provided examples) to be successful with any of the browsers on my computer today.

**Comment by rebeccacremona** [comment]
Styling ("flair") added via Extensions  instead. https://github.com/harvard-lil/perma/pull/1689
